### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by Kikobeats** [suren-atoyan/monaco-react#100]
**Describe the bug**

While all is working as expected `3.4.2`, if I update to `3.5.6` I can't render monaco editor properly

```

09:56:48.557 | > Build error occurred
-- | --
09:56:48.558 | ReferenceError: document is not defined
09:56:48.558 | at Object.<anonymous> (/vercel/19c883f1/node_modules/@monaco-editor/react/lib/utils/monaco.js:86:43)
09:56:48.558 | at Module._compile (internal/modules/cjs/loader.js:1156:30)
09:56:48.558 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
09:56:48.558 | at Module.load (internal/modules/cjs/loader.js:1000:32)
09:56:48.558 | at Function.Module._load (internal/modules/cjs/loader.js:899:14)
09:56:48.558 | at Module.require (internal/modules/cjs/loader.js:1042:19)
09:56:48.558 | at require (internal/modules/cjs/helpers.js:77:18)
09:56:48.558 | at Object.<anonymous> (/vercel/19c883f1/node_modules/@monaco-editor/react/lib/utils/index.js:47:38)
09:56:48.558 | at Module._compile (internal/modules/cjs/loader.js:1156:30)
09:56:48.558 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
09:56:48.558 | at Module.load (internal/modules/cjs/loader.js:1000:32)
09:56:48.558 | at Function.Module._load (internal/modules/cjs/loader.js:899:14)
09:56:48.558 | at Module.require (internal/modules/cjs/loader.js:1042:19)
09:56:48.558 | at require (internal/modules/cjs/helpers.js:77:18)
09:56:48.558 | at Object.<anonymous> (/vercel/19c883f1/node_modules/@monaco-editor/react/lib/Editor/Editor.js:22:14)
09:56:48.558 | at Module._compile (internal/modules/cjs/loader.js:1156:30)
```

This is how monaco is loaded from the code: https://github.com/microlinkhq/cards/blob/38f3bac85536de9caac9bb8d61f97d136bb45a60/packages/app/src/components/live-editor.js#L74

**To Reproduce**

https://github.com/microlinkhq/cards/pull/87

**Comment by suren-atoyan** [comment]
Hi @Kikobeats,

hmmm, very strange, because I see (in your message) it complaints about something in the file `@monaco-editor/react/lib...` which no longer exists. It should be `@monaco-editor/react/dist...`. May I ask you to try to install the last version manually? (Plus, maybe, try to remove the prev version).

And sorry for inconvenient.

**Comment by Kikobeats** [comment]
The error trace is referencing to 

```
var injectScriptsIntoBody = injectScripts(document.body);
```

it can't access to `document` because it's too early.

I can see this change was introduced at 3.5.0 version:

https://github.com/suren-atoyan/monaco-react/commit/7d9d60a1b808a4a580a7c9fd32d2ff179860c17b#diff-a4eae6565e84365bc04e825bbe14f193R27

from my code, I'm using `editorDidMount` to ensure I access to editor when is ready

https://github.com/microlinkhq/cards/blob/325cb9defba838901e884a199ea6637b088e5641/packages/app/src/components/live-editor.js#L92

The thing is, this error is happening before `editorDidMount` is evaluated, so something in the way `monaco-react` applies the helper should be changed to be delayed to the right moment

**Comment by suren-atoyan** [comment]
Ok, at first let me reproduce it, could you please tell me about your environment? I guess it's not a CRA app, because it's tested in CRA.

**Comment by Kikobeats** [comment]
It's a Next.js app; if you clone [this](https://github.com/microlinkhq/cards/pull/87) you can reproduce it

**Comment by suren-atoyan** [comment]
Hi @Kikobeats,

The problem was `Next.js`, it doesn't "accept" `document` in server-side rendering. There are many issues out there about that. I've just modified my functions a little bit to avoid interacting with `document` during lazy parsing.

Please, check the new version - v3.5.7
Let me know if it works.

**Comment by Kikobeats** [comment]
hey 3.5.7 is working fine! 🙂
