### ISSUE TITLE
How to use theme from the demo

### ISSUE THREAD

**Issue by bobbui** [suren-atoyan/monaco-react#107]
Just a quick question. How to use a theme for example **Github** similar to what you have on the demo.
I tried to set it in **theme** option but no luck 
Thanks in advance.

**Comment by suren-atoyan** [comment]
Hello @bobbui.

By default, there are two themes - light/dark. But you can define as many as you want. [Here](https://github.com/suren-atoyan/monaco-react/blob/277c249ffef6a6a4bb5ea12e2a20fa78abdbddea/demo/src/store/effects/index.js) is the code segment (from the demo you've seen) where new themes are being defined.

**Comment by bobbui** [comment]
to anyone who looking for the same information, take a look at this package : https://github.com/brijeshb42/monaco-themes

**Comment by adarshaacharya** [comment]
@suren-atoyan I've used these themes but problem is why can't we use themes having space ' ' as you have done in timeof filtering theme use only theme which doesn't have white space.

**Comment by adarshaacharya** [comment]
[This section of code](https://github.com/suren-atoyan/monaco-react/blob/fb75b4a06ab02a78d139e71b563f92c67af398a9/demo/src/sections/Editor/Settings/Settings.js#L97)

Why can't we map all the themes ?

**Comment by suren-atoyan** [comment]
@adarshaacharya There was a problem with theme names, I've already fixed it, now you can use all of them.

**Comment by Prottoy2938** [comment]
I can't figure it out, can't implement a custom theme.

My Code:

```jsx
import React from "react";
import { Props } from "./github-mardown.model";
import { ControlledEditor, monaco } from "@monaco-editor/react";

monaco
  .init()
  .then((monaco) => {
    import("monaco-themes/themes/Blackboard.json").then((data) => {
      monaco.editor.defineTheme("Blackboard", data);
    });
  })
  .catch((error) =>
    console.error("An error occurred during initialization of Monaco: ", error)
  );

const MarkdownContent: React.FC<Props> = (props: Props) => {
  const { content, setContent } = props;

  const handleChange = (event: any, value: string) => {
    setContent(value);
  };

  return (
    <div>
      <ControlledEditor
        width="100%"
        height="calc(100vh - 154px)"
        value={
          content.length ? content : "### Title\n > Concept and Description"
        }
        onChange={handleChange}
        theme="dark"
        language="markdown"
      />
    </div>
  );
};

export default MarkdownContent;


```

**Comment by suren-atoyan** [comment]
Hello @Prottoy2938. You load and define a theme called ``Blackboard`, but you use theme `dark` in the editor.

[Here](https://codesandbox.io/s/monaco-editorcustom-theme-quhcg?file=/src/index.js) is an equivalent of your code.

**Comment by Prottoy2938** [comment]
The [codesandbox](https://codesandbox.io/s/monaco-editorcustom-theme-quhcg?file=/src/index.js) you shared doesn't have the `Blackboard` theme.  The theme in there is plain white.

Example of a `Blackboard` theme can be found [here](https://codesandbox.io/s/monaco-editorcustom-theme-quhcg?file=/src/index.js)


What to do now?

Also, thanks for your response

**Comment by suren-atoyan** [comment]
Hey @Prottoy2938, the problem was that we tried to use a theme, which is not loaded yet. In the example, we did two jobs simultaneously. First, we tried to load monaco, after that a custom theme, and after that set it to the editor. And second, we tried to render an editor. So, when we rendered an editor, the theme not being loaded yet. I've fixed it. Please check it.

**Comment by Prottoy2938** [comment]
That fixes it. Thanks
