### ISSUE TITLE
how to add custom tag?

### ISSUE THREAD

**Issue by alikomijani** [suren-atoyan/monaco-react#111]
hi, i use monaco-react as email html editor so i need some tag like as {{first_name}} to replace it on server side,

so my question is how can i add custom tag to monaco-react editor?

tnx

**Comment by suren-atoyan** [comment]
Hi @alikomijani

I don't understand what exactly `tag` means in this context. Maybe you want it to be highlighted? Like custom token. For that purpose, you can read [this](https://github.com/microsoft/monaco-editor/issues/1927) discussion. Please let me know if it helps.

**Comment by alikomijani** [comment]
thank you so much it help me
