### ISSUE TITLE
Cannot read property 'create' of undefined

### ISSUE THREAD

**Issue by ffMathy** [suren-atoyan/monaco-react#114]
> textModel.ts:50 Uncaught TypeError: Cannot read property 'create' of undefined
>     at I (textModel.ts:50)
>     at o.setValue (textModel.ts:289)
>     at t.setValue (codeEditorWidget.ts:396)
>     at Editor.js:73
>     at commitHookEffectListMount (react-dom.development.js:19731)
>     at commitPassiveHookEffects (react-dom.development.js:19769)
>     at HTMLUnknownElement.callCallback (react-dom.development.js:188)
>     at HTMLUnknownElement.dispatchEvent (<anonymous>)
>     at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
>     at invokeGuardedCallback (react-dom.development.js:292)
>     at flushPassiveEffectsImpl (react-dom.development.js:22853)
>     at unstable_runWithPriority (scheduler.development.js:653)
>     at runWithPriority$1 (react-dom.development.js:11039)
>     at flushPassiveEffects (react-dom.development.js:22820)
>     at performSyncWorkOnRoot (react-dom.development.js:21737)
>     at react-dom.development.js:11089
>     at unstable_runWithPriority (scheduler.development.js:653)
>     at runWithPriority$1 (react-dom.development.js:11039)
>     at flushSyncCallbackQueueImpl (react-dom.development.js:11084)
>     at flushSyncCallbackQueue (react-dom.development.js:11072)
>     at discreteUpdates$1 (react-dom.development.js:21893)
>     at discreteUpdates (react-dom.development.js:806)
>     at dispatchDiscreteEvent (react-dom.development.js:4168)

**Comment by ffMathy** [comment]
When I click on `Editor.js:73`, this is the line: `editorRef.current.setValue(value);`

**Comment by ffMathy** [comment]
It seems to happen here:

```
export function createTextBuffer(value: string | model.ITextBufferFactory, defaultEOL: model.DefaultEndOfLine): model.ITextBuffer {
	const factory = (typeof value === 'string' ? createTextBufferFactory(value) : value);
	return factory.create(defaultEOL); //this is where it happens.
}
```

**Comment by ffMathy** [comment]
If attaching the debugger in Chrome, here's what `factory` is:

![image](https://user-images.githubusercontent.com/2824010/94150928-0e716880-fe7a-11ea-9934-9e61d8e9ed2e.png)

**Comment by ffMathy** [comment]
`factory` here does not have a `create` method, hence the failure.

**Comment by ffMathy** [comment]
Ah, it seems to happen if I set `value` of the `ControlledEditor` to `null` and then have it be destroyed.

**Comment by suren-atoyan** [comment]
> Ah, it seems to happen if I set `value` of the `ControlledEditor` to `null` and then have it be destroyed.

Yes, you are right, the value [should be](https://github.com/suren-atoyan/monaco-react#editor) a string.

**Comment by Flavyoo** [comment]
I'm also seeing this issue. How come your examples don't result in this issue?

**Comment by suren-atoyan** [comment]
@Flavyoo the value prop is not required and also can an empty string; but if it is something, it should be a string.

**Comment by ffMathy** [comment]
That just seems like odd behavior. So `undefined` is allowed but not `null`? Why not fall back to a sane default?
