### ISSUE TITLE
TypeDef not work , Refused to execute script from ... because its MIME type ('text/html') is not executable. nwjs

### ISSUE THREAD

**Issue by djmisterjon** [suren-atoyan/monaco-react#115]
**Describe the bug**
hi, i success to make it run., but i have a small issue !
When mouse hover a symbole, i get a loading window to infinite !

**To Reproduce** 
You can try with this boiler-plate.
https://github.com/djmisterjon/nw-Parcel-hmr-boilerplate

* fork and open folder in Vscode or other IDE
* `npm i`  to build env (it can long)
* `npm install @monaco-editor/react -S` 
* download `https://registry.npmjs.org/monaco-editor/-/monaco-editor-0.21.2.tgz` and put in forlder `/res`
The folder `res` are moving in `dist` folder for electron or nwjs , when `npm run start-nw`
* add  somewhere in `/src/index.js `
```js
import Editor, { monaco } from '@monaco-editor/react';
monaco.config({ paths: { vs: 'res/myMonacoFolder/dev/vs' } });
```
* `npm run start-nw`

**Expected behavior**
make IntelliSense work !

**Screenshots**
![image](https://user-images.githubusercontent.com/24865815/94530753-8ab4d480-0209-11eb-9d0e-4ec644f9fead.png)
![image](https://user-images.githubusercontent.com/24865815/94530867-b932af80-0209-11eb-991b-933a8e61d420.png)
![image](https://user-images.githubusercontent.com/24865815/94531533-aff61280-020a-11eb-837f-09f6e3605ded.png)

**Desktop (please complete the following information):**
 - **OS**: win10
 - **Browser**: chromium nwjs
 - **Version** : 
```
ares: "1.16.0"
brotli: "1.0.7"
chromium: "85.0.4183.83"
icu: "67.1"
llhttp: "2.0.4"
modules: "83"
napi: "6"
nghttp2: "1.41.0"
node: "14.9.0"
node-webkit: "0.48.1"
nw: "0.48.1"
nw-commit-id: "4b0166c-40685d1-91cbe7b-93785c4"
nw-flavor: "sdk"
openssl: "1.1.1g"
unicode: "13.0"
uv: "1.39.0"
v8: "8.5.210.20"
zlib: "1.2.11"
```

**Additional context**
if look in moduleManager scope ? i dont know if we can have revelant stuff?
JSON.stringify(moduleManager,null,'\t')
```json
{
	"_env": {
		"_detected": true,
		"_isWindows": true,
		"_isNode": true,
		"_isElectronRenderer": false,
		"_isWebWorker": true
	},
	"_scriptLoader": {
		"_env": {
			"_detected": true,
			"_isWindows": true,
			"_isNode": true,
			"_isElectronRenderer": false,
			"_isWebWorker": true
		},
		"_scriptLoader": {},
		"_callbackMap": {
			"../../../vs/base/common/worker/simpleWorker.js": [
				{}
			]
		}
	},
	"_loaderAvailableTimestamp": 36230.7799999835,
	"_moduleIdProvider": {
		"_nextId": 5,
		"_strModuleIdToIntModuleId": {},
		"_intModuleIdToStrModuleId": [
			"exports",
			"module",
			"require",
			"===anonymous1===",
			"vs/base/common/worker/simpleWorker"
		]
	},
	"_config": {
		"_env": {
			"_detected": true,
			"_isWindows": true,
			"_isNode": true,
			"_isElectronRenderer": false,
			"_isWebWorker": true
		},
		"options": {
			"baseUrl": "../../../",
			"isBuild": false,
			"paths": {},
			"config": {},
			"catchError": true,
			"recordStats": false,
			"urlArgs": "",
			"ignoreDuplicateModules": [],
			"cspNonce": "",
			"preferScriptTags": false,
			"nodeModules": []
		},
		"ignoreDuplicateModulesMap": {},
		"nodeModulesMap": {},
		"sortedPathsRules": []
	},
	"_modules2": [
		null,
		null,
		null,
		{
			"id": 3,
			"strId": "===anonymous1===",
			"dependencies": [
				{
					"id": 4
				}
			],
			"moduleIdResolver": {
				"fromModulePath": ""
			},
			"exports": {},
			"error": null,
			"exportsPassedIn": false,
			"unresolvedDependenciesCount": 1,
			"_isComplete": false
		}
	],
	"_knownModules2": [
		null,
		null,
		null,
		null,
		true
	],
	"_inverseDependencies2": [
		null,
		null,
		null,
		null,
		[
			3
		]
	],
	"_inversePluginDependencies2": {},
	"_currentAnnonymousDefineCall": null,
	"_recorder": {},
	"_buildInfoPath": [],
	"_buildInfoDefineStack": [],
	"_buildInfoDependencies": []
}
```
tanks for any help or suggest.
tell me if missing sowmthing

**Comment by djmisterjon** [comment]
ok so i succed to make it work in vanilla with same project structure
![image](https://user-images.githubusercontent.com/24865815/94657397-66bbc680-02cf-11eb-8567-b53c9dca1f88.png)
Now why is not work when integrate with react ! ?? dont know.
I will therefore use Monaco without React and instead open a new Nwjs instance window with mixed Context and listened change between 2 window.
So I couldn't integrate it into my React applications, waiting for a solution to be found.
for the moment these OK for me.

**Comment by djmisterjon** [comment]
@suren-atoyan 
Haaaa EUREKA !!! ok is not related to Monaco-react or MonacoJs itself, is related to arguments passed to chromium engine.
Now types work work with integrate react - parcel bundler! no need need new instance of window.
![image](https://user-images.githubusercontent.com/24865815/94666540-9a9ce900-02db-11eb-8095-6e048bcfd5f9.png)

so here the tips if you want add to doc to prevent others from having a serious headache !
So example mine in package.json look like this
```json
	"chromium-args": "--enable-node-worker --enable-webvr --webxr --enable-gamepad-extensions --enable-gamepad-vibration --enable-spell-checking --remote-debugging-port=9222 --load-extension='./plugins/pixi_devtools_0.9.3_0','./plugins/React_Developer_Tools_4.7.0_0'",
	"permissions": ["chrome-extension://*", "file:///*", "http://*/*", "https://*/*"],
```
Just remove `--enable-node-worker` 
Why, i dont know, but it work now with nwjs and maybe same for electron if your pass arguments to chromium.
am happy now. :) and thanks for your awsome work on Monaco-react.

**Comment by suren-atoyan** [comment]
Hello @djmisterjon. Very glad to hear that it's solved now. I'll a link to this conversation in docs (README); after, I'll close it.
