### ISSUE TITLE
Question on Accessing Language Formatting?

### ISSUE THREAD

**Issue by frastlin** [suren-atoyan/monaco-react#119]
Hello,
How do I access [language formatting?](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.formattingoptions.html)
I would like to change spaces to tabs.
Thanks,

**Comment by suren-atoyan** [comment]
Hello @frastlin, sorry for the late answer.

You can use `editor.getModel().updateOptions({ tabSize: ..., })`

`editor` instance is exposed from `editorDidMount` method.

[Here is a working example](https://codesandbox.io/s/monaco-editorreact---editor-instance-forked-8tq9b?file=/src/index.js)

**Comment by frastlin** [comment]
Hello,
I don't want to change the size of tabs, I want to use the tab character, \t (ASCII character 9), "	". Changing the tab size just adds more spaces.
Thanks,

**Comment by suren-atoyan** [comment]
@frastlin that's the second option of `updateOptions` and called `insertSpaces`. The documentation (like you've shared) said `prefer spaces over tabs` - so, if you set `insertSpaces: false`, it will convert spaces to tabs.

[check the previous example](https://codesandbox.io/s/monaco-editorreact---editor-instance-forked-8tq9b?file=/src/index.js) with the new option

**Comment by ChristopherHButler** [comment]
Thanks for all your hard work @suren-atoyan !! The above example does not seem to be working with version `4.6.0` (althought I am trying to do it in the onMount callback.)

Do you happen to see what I am doing wrong here:

```ts
// only showing relevant code
const Editor = () => {
  const onEditorDidMount = useCallback(async (editor: editor.IStandaloneCodeEditor, monaco: Monaco) => {

    editor.getModel()!.updateOptions({ tabSize: 4 });

  }, []);

  return (
      <Editor
        height="100%"
        loading={loading}
        value={value}
        language={language}
        theme={theme}
        options={{
          ...editorOptions,
        }}
        onMount={onEditorDidMount}
        onChange={onEditorChange}
      />
);
};
```
