### ISSUE TITLE
Unable to actually get the monaco instance

### ISSUE THREAD

**Issue by pcross616** [suren-atoyan/monaco-react#120]
**Describe the bug**
It looks like the documentation is not right or I am just missing something.  

https://github.com/suren-atoyan/monaco-react#editor-instance says editorDidMount will give a reference to the monaco editor when in fact per the code it looks like it give a editiorRef vs the monacoRef which is not used.  If that was intended then I can create a PR that adds that monacoRef to the editorDidMount as a third parameter.  Just wanted to see if you had a idea on the best way to defineThemes and I cant use the editorRef to do so.

https://github.com/suren-atoyan/monaco-react/blob/fa34a7e29b8844a467c3eec79810d7dba85b6086/src/Editor/Editor.js#L90

**Comment by suren-atoyan** [comment]
Hello @pcross616.

There are `editorRef` and `monacoRef`. [Editor Instance](https://github.com/suren-atoyan/monaco-react#editor-instance) section says that you can get `editorRef` from `editorDidMount`. But it's `editorRef` (as the documentation says), it's not a `monacoRef`. To get `monacoRef` you need to use `monaco` utility (exported from the library). Read more [here](https://github.com/suren-atoyan/monaco-react#monaco-instance).

**Comment by pcross616** [comment]
Perfect, I don't know how I missed that in the docs.  Thanks
