### ISSUE TITLE
Can't edit?

### ISSUE THREAD

**Issue by pakhavan23** [suren-atoyan/monaco-react#121]
Hey! I'm trying to use this library on my website, I use the exact same code that you wrote in the usage, but I only get the basic layout of Monaco. what could be the reason?
Thank you!

**Comment by suren-atoyan** [comment]
Hello @pakhavan23, could you please provide an example? or a reproducible snippet (you can use codesandbox.io)

**Comment by pakhavan23** [comment]
Yeah sure! 
This is the component that contains monaco, it's a functional component that exports to index.js, and index.js is where I used react router to organize my components.

import React from "react";
import Editor from '@monaco-editor/react';
 
const QuestionCode = () => <Editor height="90vh" language="javascript" />;

export default QuestionCode;

and this is index.js:
import React from 'react';
import ReactDOM from 'react-dom';
import { BrowserRouter , Route } from 'react-router-dom';
import { Provider } from 'react-redux';
import { createStore , applyMiddleware} from 'redux';
import promiseMiddleware from 'redux-promise';
import reducers from './reducers';
import Home from './components/Home';
import SignUp from './components/SignUp';
import Login from './components/Login';
import Courses from './components/Courses';
import AdminPanel from './components/AdminPanel';
import CourseLessons from './components/CourseLessons';
import Lesson from './components/Lesson';
import Question from './components/Question';
import AddProf from './components/AddProf';
import AddTa from './components/AddTa';
import AddCourse from './components/AddCourse';
import AddLesson from './components/AddLesson';
import CoursePanel from './components/CoursePanel';
import AddQuiz from './components/AddQuiz';
import OnlineClass from './components/OnlineClass';
import Quiz from './components/Quiz';
import QuizStore from './components/QuizStore';
import QuestionStore from './components/QuestionStore';
import ProfQualification from './components/ProfQualification';
import QuestionCode from './components/QuestionCode'

const createStoreWithMiddleware = applyMiddleware(promiseMiddleware)(createStore);

const App = () => {
    return(
        <Provider store={createStoreWithMiddleware(reducers)}>
            <BrowserRouter>
                <Route path="/codeyar-front" exact component={Home} />
                <Route path="/codeyar-front/sign-up" exact component={SignUp} />
                <Route path="/codeyar-front/log-in" exact component={Login} />
                <Route path="/codeyar-front/courses" exact component={Courses} />
                <Route path="/codeyar-front/admin-panel" exact  component={AdminPanel} />
                <Route path="/codeyar-front/courses/python/panel" exact component={CoursePanel} />
                <Route path="/codeyar-front/courses/python/lessons" exact component component={CourseLessons} />
                <Route path="/codeyar-front/courses/python/lessons/lsn1" exact component={Lesson} />
                <Route path="/codeyar-front/courses/python/add-lesson" exact component={AddLesson} />
                <Route path="/codeyar-front/courses/python/quiz" exact component={QuizStore} />
                <Route path="/codeyar-front/courses/python/quiz/q1" exact component={Quiz} />
                <Route path="/codeyar-front/courses/python/question" exact component={QuestionStore} />
                <Route path="/codeyar-front/courses/python/question/qu1" exact component={Question} />
                <Route path="/codeyar-front/add-prof" exact component={AddProf} />
                <Route path="/codeyar-front/add-ta" exact component={AddTa} />
                <Route path="/codeyar-front/add-course" exact component={AddCourse} />
                <Route path="/codeyar-front/courses/python/add-quiz" exact component={AddQuiz} />
                <Route path="/codeyar-front/qualify-prof" exact component={ProfQualification} />
                <Route path="/codeyar-front/courses/python/online-class" exact component={OnlineClass} />
                <Route path="/codeyar-front/monaco" exact component={QuestionCode} />
            </BrowserRouter>
        </Provider>
    )
}

ReactDOM.render(<App/> , document.getElementById("root"));

**Comment by suren-atoyan** [comment]
> ...but I only get the basic layout of Monaco

What does it mean?

**Comment by pakhavan23** [comment]
I only get the theme, I can't type anything or when I give it a value I can't see it 😅

**Comment by suren-atoyan** [comment]
Is it deployed somewhere? Is it possible to check it?
