### ISSUE TITLE
Loading... in Electron

### ISSUE THREAD

**Issue by vcgupta** [suren-atoyan/monaco-react#122]
**Describe the bug**
I have tried to setup Electron with this package. As provided in Setup intruction I have added `vs` path. Still I get three errors in console and It continue to show "Loading..." indicator

**To Reproduce**
1. Clone [the repo](https://github.com/vcgupta/monaco-react-test/)
2. Run in terminals:
Terminal 1: `npm run server`
Terminal 2: `npm start`

**Expected behavior**
It should load into Electron

**Screenshots**
In Same repo under screenshot folder

**Desktop (please complete the following information):**
 - Electron, MAC machine

**Comment by suren-atoyan** [comment]
Hello @vcgupta, sorry for the late answer. You don't need a special boilerplate for the electron to use monaco with it.

However, there can be some tricky cases. Read about those cases [here](https://github.com/suren-atoyan/monaco-react#for-electron-users)
