### ISSUE TITLE
Webpack Bundler Companion Repo?

### ISSUE THREAD

**Issue by philcockfield** [suren-atoyan/monaco-react#123]
Thanks so much for putting this "webpack bundler free" library together.  
Getting Monaco to bundle with Webpack is an exercise in head-banging frustration. 😳🥺

That said, I see [this configuration option](@monaco-editor/react):

```js
import { monaco } from '@monaco-editor/react';

// you can change the source of the monaco files
monaco.config({ paths: { vs: '...' } });
```

Which if I'm not mistaken, allows me to redirect where these bundles are pulled from over to my own CDN.  
Is this a correct reading?

If so, I'm wondering, is there a companion repository where you have the `webpack.config.js` setup that creates the files you are putting on your CDN?  I need to be able to host these internally to my system.

Again - thanks so much for this library - it's a bit of sanity in an otherwise nightmarish bundling scenario with Monaco!! 🤯😀

**Comment by suren-atoyan** [comment]
Hello @philcockfield. Thank you for your feedback.

`monaco.config({ paths: { vs: '...' } });` this line gives you an opportunity to download monaco wherever you want; it can be another CDN or local files.

For example, you can install the `monaco-editor` package

```bash
yarn add monaco-editor # (npm install monaco-editor)
```

copy/move monaco sources from `node_modules` to your "public" (where your static files are located) folder

```bash
mv node_modules/monaco-editor/min/vs/ ./public
```

and load monaco from that folder

```javascript
monaco.config({ paths: { vs: '/vs/' } });` 
```

**Comment by philcockfield** [comment]
Woah! Wait!! What??!!

# Thats awesome Suren

Thanks a lot.  Really really helpful bit of work here man!

**Comment by suren-atoyan** [comment]
> Woah! Wait!! What??!!
> 
> # Thats awesome Suren 🍰
> Thanks a lot. Really really helpful bit of work here man!

Glad to hear that 🙂
