### ISSUE TITLE
DiffEditor Configuration: Choose Split, Colours, Editabillity

### ISSUE THREAD

**Issue by ColmanHumphrey** [suren-atoyan/monaco-react#125]
**Is your feature request related to a problem? Please describe.**

Well basically I want to show a diff, but **not** allow editing of it, the same way you can't edit the original side of it. This is the primary desire.

Secondary, it would be nice to:

- Choose the initial view split, or even just show the modified side!
- Choose the colours of the diffs (maybe this is already in themes somewhere?)

**Describe the solution you'd like**

I guess it wouldn't be good to use the `options` input, since this comes straight from the original api. So I suppose it would have to be another input into the `DiffEditor` component, like `parameters` etc.

**Describe alternatives you've considered**

I tried seeing if I could somehow inject some config into `monaco-editor` directly, but I'm not yet familiar enough with it (or Javascript!)

**Additional context**

The reason for this is that I want to show a diff that is the result of an input elsewhere.

Also - thanks for the excellent package!

**Comment by suren-atoyan** [comment]
Hello @ColmanHumphrey.

To be able to restrict editing you can use the `options` property of the `DiffEditor` component, which is the reflection of the original `options`. ([here](https://github.com/suren-atoyan/monaco-react#diffeditor) is the all props for `DiffEditor` component, and [here](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.idiffeditorconstructionoptions.html) are the all options).

I've just created an example for you, to show how does it look. [Here](https://codesandbox.io/s/monaco-editordiff-p6b3v?file=/src/index.js) it is.

And thank you for your feedback 🎉

**Comment by ColmanHumphrey** [comment]
Oh nice one! I had stared at that page of DiffOptions before but somehow didn't see `readOnly`... that's perfect!

I see that indeed setting the theme can work for the colours, nice: https://github.com/microsoft/monaco-editor/issues/368#issuecomment-312835039

Lastly, the default split might not be currently possible yet either: https://github.com/microsoft/monaco-editor/issues/2202

Thanks again!
