### ISSUE TITLE
Compare content

### ISSUE THREAD

**Issue by FranciscoImanolSuarez** [suren-atoyan/monaco-react#126]
Hello, I wanted to make a query, or if you have a better example, how can I get the content that the user writes in the editor and it compares it with what I have in a .js file. In case this is the same, send a message to the console and in case it is false the same.

Thank you very much already!

**Comment by suren-atoyan** [comment]
Hi @FranciscoImanolSuarez, to get the content that the user writes in the editor, you can use [editor instance](https://github.com/suren-atoyan/monaco-react#editor-instance) (look at the function called `listenEditorChanges`) or you can use a [controlled editor](https://github.com/suren-atoyan/monaco-react#controlled-editor) (and use `onChange` prop)

**Comment by FranciscoImanolSuarez** [comment]
Thanks !

**Comment by FranciscoImanolSuarez** [comment]
Hello again, sorry for the new question, but I have no idea how to compare the value that the user writes with an X value.

For example
Input User
`console.log("Hello")`

Code to compare
`console.log("Hello World")`

I don't know if you could give me help

**Comment by suren-atoyan** [comment]
Hello @FranciscoImanolSuarez 

Please check [this](https://codesandbox.io/s/monaco-editorreact---controlled-editor-issue-126-fo5fd?file=/src/index.js)

**Comment by FranciscoImanolSuarez** [comment]
@suren-atoyan  Wow You're a genius! I thank you very much!!!
