### ISSUE TITLE
React 17.0.1

### ISSUE THREAD

**Issue by nsisodiya** [suren-atoyan/monaco-react#127]
Getting this error

```
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.6" from @monaco-editor/react@3.6.3
npm ERR! node_modules/@monaco-editor/react
npm ERR!   @monaco-editor/react@"3.6.3" from the root project
```

**Comment by suren-atoyan** [comment]
Hello @nsisodiya, could you please give me more information about your environment?

I've just checked it and everything seems okay. [Here](https://codesandbox.io/s/with-react-17-nxii8) is an example with React 17.0.1 version.

**Comment by nsisodiya** [comment]
@suren-atoyan Might be some error from my side.
Thanks.

**Comment by amarant** [comment]
The problem is not from your side, with npm v7 peer dependencies resolution are lo longer optional, and "^16.8.6" is not compatible with the use of react 17, you should change it to ">=16.0.0" or something like that.

**Comment by bobbui** [comment]
> The problem is not from your side, with npm v7 peer dependencies resolution are lo longer optional, and "^16.8.6" is not compatible with the use of react 17, you should change it to ">=16.0.0" or something like that.

happen to me as well, we need to update the peerDependencies declaration

**Comment by suren-atoyan** [comment]
@nsisodiya @amarant @bobbui 

Hello guys, I have already updated the `deerDependencies` in the `package.json`; now, it looks like this:

<img width="468" alt="Screen Shot 2020-12-05 at 21 55 23" src="https://user-images.githubusercontent.com/13118722/101259811-99a58f00-3744-11eb-9a62-3d7d1d8f5c4d.png">

Please, if it is possible, check (and let us know) the new version of the package - `v3.7.2`

Thank you for your support.
