### ISSUE TITLE
ControlledEditor starts off with all text highlighted

### ISSUE THREAD

**Issue by joshuacheng** [suren-atoyan/monaco-react#129]
**Describe the bug**
I am using the ControlledEditor as part of a larger page. When opening the page, I have to scroll down to see the monaco editor, and when I get to it, all the text starts off highlighted. This is not so much a functional issue as much as just being a little annoying, but I'd still like to figure out why it's happening. 

**To Reproduce**

My code looks like
```
<ControlledEditor
     height={props.height}
     width={props.width}
     value={props.value}
     onChange={props.onChange}
     language="mylanguage"
     theme="dark"
/>
```
It's not a problem with any of my custom language settings I've created bc I can comment those out and the issue remains. In fact I can remove everything except for the height, width, and value and I still have the issue. Has anyone else run into this?

**Comment by joshuacheng** [comment]
@albingroen I also recently figured out it was due to programmatically switching the value of the `ControlledEditor`, and my solution was simply to wait until I had the API response value I wanted, and then start rendering the Editor. Also a hacky workaround on my part.

**Comment by suren-atoyan** [comment]
Hello guys, sorry for the late answer.

**About multi-file editors:** by changing key property we force the Editor component to mount/unmount, which leads to a new model creation (it is logical when you want to create a multi-file editor). But, I agree, it's not the most elegant way, and in the new version, a new API will be provided for multi-file editors.

**About highlighted text:** may I ask you to create a simple code snippet? (for example in [codesandbox.io](codesandbox.io)) to be able to reproduce it.

**Comment by albingroen** [comment]
@suren-atoyan Thanks for getting back to us. I'm glad to hear that there's a upcoming version which will better support multi file editors.

Regarding the selection of code, here's a [codesandbox demo](https://codesandbox.io/s/busy-darwin-djxc5?file=/src/App.js) where you should see the issue occur. I've tested in all 3 major browsers (Chrome, Safari, Firefox) and it's acting the same way in all of them.

**Comment by suren-atoyan** [comment]
@albingroen  Thank you!

I see, okay, I'll test it and come back to you!

**Comment by albingroen** [comment]
@suren-atoyan @joshuacheng I've made another observation. The highlighting issue only seems to occur when you go from a value of `""` to a value that has content. If you go between 2 or more values that has more than one character it doesn't seem to highlight anything.

**Comment by suren-atoyan** [comment]
Hello guys

I've already fixed the issue. Please check the new version v3.7.3 (@albingroen it is not the one with multi-file editor API).

You can check @albingroen's [codesandbox demo](https://codesandbox.io/s/monaco-react-issue-129-u8mpt?file=/src/App.js) with the updated version of the package.

@joshuacheng could you please check the new version in your app?

Thank you for your support!

**Comment by albingroen** [comment]
I suppose we can close this issue now?

**Comment by suren-atoyan** [comment]
Sure, I just waited for you to check in your projects. If everything is okay in the cases you've mentioned earlier, so, we can close it

**Comment by albingroen** [comment]
> Sure, I just waited for you to check in your projects. If everything is okay in the cases you've mentioned earlier, so, we can close it

Ah sorry, forgot to mention. It works great in my projects now 👍

**Comment by suren-atoyan** [comment]
Great, let's also wait for @joshuacheng and, after, I'll close it

**Comment by joshuacheng** [comment]
@albingroen @suren-atoyan looks good, thanks for all your help!
