### ISSUE TITLE
Use monaco-react from cdn

### ISSUE THREAD

**Issue by ChristopherHButler** [suren-atoyan/monaco-react#130]
Is it possible to use from a cdn? I would like to use this editor in an online editor which requires loading from a cdn.

**Comment by suren-atoyan** [comment]
Hello @ChristopherHButler. Unfortunately, officially it's not supported yet. But by default, it loads monaco sources from CDN. Check it [here](https://github.com/suren-atoyan/monaco-react/blob/master/src/config/index.js#L3) and [here](https://github.com/suren-atoyan/monaco-react/blob/master/src/utils/monaco.js#L80)

**Comment by ChristopherHButler** [comment]
Ok thanks 👍  Please post an update if this changes :)  
![a459775f026e1dc6032f7c342b80ee40](https://user-images.githubusercontent.com/29358086/98779943-b1fbe580-23f4-11eb-9d0a-bc145801e15d.jpg)

**Comment by suren-atoyan** [comment]
Hey @ChristopherHButler 

Your request came true

[check this out](https://codesandbox.io/s/cdn-example-hrzv2)

I'll add a section about this in docs, but for now, here it is:

[unpkg](https://unpkg.com/@monaco-editor/react@3.8.2/lib/umd/monaco-react.min.js)
[jsdelivr](https://cdn.jsdelivr.net/npm/@monaco-editor/react@3.8.2/lib/umd/monaco-react.min.js)

Be sure, that dependencies and peer dependencies are loaded - `react`, `prop-types`, `@monaco-editor/loader`
So, it should look like this:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>@monaco-editor/react - CND demo</title>
    <script
      src="https://unpkg.com/react@17/umd/react.development.js"
      crossorigin
    ></script>
    <script
      src="https://unpkg.com/react-dom@17/umd/react-dom.development.js"
      crossorigin
    ></script>
    <script
      src="https://unpkg.com/prop-types@15.7.2/prop-types.js"
      crossorigin
    ></script>
    <script
      src="https://unpkg.com/@monaco-editor/loader@0.1.2/lib/umd/monaco-loader.min.js"
      crossorigin
    ></script>
    <script
      src="https://unpkg.com/@monaco-editor/react@3.8.2/lib/umd/monaco-react.min.js"
      crossorigin
    ></script>
  </head>
  <body>
    <div id="app" style="height: 100vh;"></div>

    <script type="text/javascript">
      const e = React.createElement;

      function App() {
        const Editor = monaco_react.default;

        return e(Editor, {
          value: "// some other comment",
          language: "javascript"
        });
      }

      const domContainer = document.querySelector("#app");
      ReactDOM.render(e(App), domContainer);
    </script>
  </body>
</html>
```

**Comment by ChristopherHButler** [comment]
Awesome!! Thank you so much. I've used it already 😄
