### ISSUE TITLE
scala syntax highlighting not working.

### ISSUE THREAD

**Issue by nsisodiya** [suren-atoyan/monaco-react#131]
I tried passing following option to Editor
```
language='scala'
```
but syntax highlighting is not working.

**Comment by nsisodiya** [comment]
I checked - browser is trying to load -
```
https://cdn.jsdelivr.net/npm/monaco-editor@0.20.0/min/vs/basic-languages/scala/scala.js
```
and v0.20.0 don't have scala support.
However, `0.21.0` has scala support.
```
https://cdn.jsdelivr.net/npm/monaco-editor@0.21.0/min/vs/basic-languages/scala/scala.js
```

where I can change this behaviour? where i can specify mocaco-editor version?

**Comment by suren-atoyan** [comment]
Hello @nsisodiya. Sure you can change the version, use the [config](https://github.com/suren-atoyan/monaco-react#config) for that purpose. [Here](https://codesandbox.io/s/monaco-editorsimple-usage-config-sg797?file=/src/index.js) is an example of how you can use version 0.21.0.

**Comment by suren-atoyan** [comment]
@nsisodiya, in the new version released today, the monaco version is updated to 0.21.2. Check please v3.7.0
