### ISSUE TITLE
Get Syntax Marker Errors from Monaco

### ISSUE THREAD

**Issue by AustinMutschler** [suren-atoyan/monaco-react#132]
**Is your feature request related to a problem? Please describe.**
I would like to prevent my users from saving if they have monaco syntax errors in their code. I could implement my own check but was wondering if monaco had any way of outputting the already found syntax errors.

**Describe the solution you'd like**
I would like to see a way to get the validation errors inside of monaco so I can prevent the user from saving code that is invalid without putting a custom syntax validation on Save.

Is there a way to tap into monaco to extract the current highlighted syntax errors so that I can use them in the component that wraps my monaco editor?

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by AustinMutschler** [comment]
Update: I know it is possible to get as they added it with getModalMarkers. I am unsure how to access this data from the editor. https://microsoft.github.io/monaco-editor/api/modules/monaco.editor.html#getmodelmarkers

**Comment by suren-atoyan** [comment]
Hello @AustinMutschler, I am sorry for coming back to you so late.

To get model markers you need to access monaco instance by using `monaco` utility:

```javascript
monaco.init().then(monacoInstance => {
  console.log(monacoInstance.editor.getModelMarkers());
});
```

BTW; if you happen to remember our last discussion about exposing monaco instance from `editorDidMount`, so, I just would say that in the next major version I'll expose it; the API will be slightly different, but the general idea of your request will be done 🙂

**Comment by mzvast** [comment]
Will the onValidate support languages such as Lua？

**Comment by suren-atoyan** [comment]
> Will the onValidate support languages such as Lua？

no, check [this](https://github.com/suren-atoyan/monaco-react#onvalidate)
