### ISSUE TITLE
Any plans to upgrade monaco-editor peerDependencies to 0.21.x?

### ISSUE THREAD

**Issue by hacker0limbo** [suren-atoyan/monaco-react#133]
**Describe the bug**
I see [this issue](https://github.com/suren-atoyan/monaco-react/issues/73) mentioned about diff editor layout bug with `monaco-editor` version 0.20.0. However, i checked monaco-editor [release](https://github.com/microsoft/monaco-editor/releases) and looks like the latest version is 0.21.x. So i am wondering is there any plans to upgrade this lib's peerDependencies to the latest version as well?

I know i can use cdn link to downgrade or upgrade to use 0.21.x or 0.19.x as mentioned in the [issue](https://github.com/suren-atoyan/monaco-react/issues/73#issuecomment-620545425), however due to some personal issue i am not allowed to do that.

Cheers!

**Comment by suren-atoyan** [comment]
Hello @hacker0limbo. Please check the new version; v3.7.0. Monaco is already updated to 0.21.2
