### ISSUE TITLE
Vim :)

### ISSUE THREAD

**Issue by LydiaF** [suren-atoyan/monaco-react#136]
Dear Suren,

Thank you so much for the wonderful package. I installed yesterday and so far it is working perfectly.

I am wondering if you or anyone knows how to get a vim version of it? I found this [package](https://github.com/brijeshb42/monaco-vim) and it seems like it might be possible to integrate with yours? I apologise in advance if the answer is obvious from the docs!

Best,

Lydia

**Comment by suren-atoyan** [comment]
Hello @LydiaF 

The package you've shared has some incompatibilities with this library due to its technical implementation, to be able to use it in an elegant way. But there is nothing impossible - I've found not good, but an acceptable way. [Here](https://codesandbox.io/s/monaco-editorvim-jy8ox?file=/src/index.js) it is.

**Comment by LydiaF** [comment]
Dear Suren,

Thank you SO SO SO much! I can't overstate how helpful this is to my work. It works perfectly. Thank you so much for this huge help and also for looking into it so quickly. 

Best wishes,

Lydia

**Comment by LydiaF** [comment]
Dear Suren,

I apologise for coming back to you again looking for help, please feel free to ignore this question... !

Is it possible to add custom key bindings to your code sandbox? (Like what is suggested [here](https://github.com/brijeshb42/monaco-vim#adding-custom-key-bindings).) I am trying to connect `:w` to a save operation.

If not, it is no problem at all. Your package is working wonderfully for me, thank you so much again.

Lydia

**Comment by suren-atoyan** [comment]
Hello @LydiaF 

That's okay, no problem. Check [this](https://codesandbox.io/s/monaco-editorvim-jy8ox?file=/src/index.js) out

**Comment by suren-atoyan** [comment]
@LydiaF The previous example is about custom key bindings for monac in general, and [this](https://codesandbox.io/s/monaco-editorvim-forked-7go6h?file=/src/index.js) one is monaco-vim specific key bindings

**Comment by LydiaF** [comment]
Dear Suren,

I am so grateful to you for your help with this. Thank you so much for both examples!! I will be using both of them :)

I wish you all the best with your projects.

Lydia

**Comment by wrightwriter** [comment]
Maybe add this solution to README.md? Quite a bunch of people would appreciate this.

**Comment by MarufSharifi** [comment]
Dear @suren-atoyan, thank you so much for solution, you saved lots of my time!!!!

**Comment by nilehmann** [comment]
Hi, sorry to revive this thread once again, but I would appreciate some help.

I tried doing exactly what was written [here](https://codesandbox.io/s/monaco-editorvim-jy8ox?file=/src/index.js), i.e., using `window.require` and `https://unpkg.com/monaco-vim/dist/monaco-vim`, and that works for me. But if I try installing `monaco-vim` with `npm` and then importing `initVimMode` I get a weird behavior in which you cannot enter into insert mode. Any ideas? I seem to be using monaco-vim v0.3.5 in both situations

**Comment by suren-atoyan** [comment]
if you import `monaco-vim` as an `npm` then you should do the same thing with `monaco-editor`. Check [use monaco-editor as an npm package](https://github.com/suren-atoyan/monaco-react#use-monaco-editor-as-an-npm-package)
