### ISSUE TITLE
`setCompilerOptions({lib:['es6']})` makes lib empty.

### ISSUE THREAD

**Issue by heroboy** [suren-atoyan/monaco-react#137]
**Describe the bug**

**To Reproduce**

https://codesandbox.io/s/monaco-editorreact---get-value-forked-4pbq0?file=/src/index.js

```javascript
monaco
  .init()
  .then((monaco) => {
    const opts = monaco.languages.typescript.javascriptDefaults.getCompilerOptions();
    monaco.languages.typescript.javascriptDefaults.setCompilerOptions({
      ...opts,
      lib: ["es6"]
    });
  })
  .catch((error) =>
    console.error("An error occurred during initialization of Monaco: ", error)
  );
```

1. input "'abc'."

**Expected behavior**
should show completition list for string type.

**Screenshots**
nothing

**Desktop (please complete the following information):**
 - OS: windows
 - Browser firefox
 - Version see codesandbox.io

**Additional context**
I try this code in https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-javascript-defaults
It works.
```
let opts = monaco.languages.typescript.javascriptDefaults.getCompilerOptions();
monaco.languages.typescript.javascriptDefaults.setCompilerOptions({...opts,lib:['es6']});
```

**Comment by suren-atoyan** [comment]
Hello @heroboy, sorry for the late answer.

Just update the library version.

https://user-images.githubusercontent.com/13118722/104378566-a1293680-5541-11eb-8907-03ca57d5a179.mov
