### ISSUE TITLE
Change the language will make text to original value.

### ISSUE THREAD

**Issue by heroboy** [suren-atoyan/monaco-react#138]
**Describe the bug**
In uncontrolled mode editor, the text will revert to original value when language changed.
But some other options like `wordWrap` won't do this.

**To Reproduce**

https://codesandbox.io/s/monaco-editorreact---get-value-forked-1k7g0?file=/src/index.js

1. type some code
2. click 'ts' 'js' button
3. the text revert to original value.

**Comment by suren-atoyan** [comment]
Hello @heroboy 

I assume it works as expected, I mean to say when you click the button, you to `setLang` wich updates the component, the component update means re-rendering of children, so, Editor component renders with prop `value` which is the same; in your case it is "// write your code here". I reckon it's a normal behavior of React.

To solve your problem you need to "remember" the previous value before the update. You can use `valueGetter` to store the previous value before `setLang` or you can use `ControlledEditor` to track all value changes. [Here](https://codesandbox.io/s/monaco-editorreact---get-value-forked-yguz1?file=/src/index.js:167-178) is an example of ControlledEditor adopted for your case.

**Comment by heroboy** [comment]
But it is strange that if I change other options that will update the component and cause it reredering, it will not revert the value.
see this: https://codesandbox.io/s/monaco-editorreact---get-value-forked-1k7g0?file=/src/index.js

**Comment by heroboy** [comment]
I think in uncontrolled mode, it should use `defaultValue` for property name. 
And the `value` should be only be used when it being mounted.

**Comment by suren-atoyan** [comment]
> But it is strange that if I change other options that will update the component and cause it reredering, it will not revert the value.
> see this: https://codesandbox.io/s/monaco-editorreact---get-value-forked-1k7g0?file=/src/index.js

I guess it's the previous example

**Comment by heroboy** [comment]
try this, I add a 'word wrap' checkbox.
https://codesandbox.io/s/monaco-editorreact---get-value-forked-qt2ft

**Comment by heroboy** [comment]
hello @suren-atoyan
Any feedback?

**Comment by suren-atoyan** [comment]
@heroboy your examples are not equivalent, in one you give a prop fixed value (value="something"), in the other one variable from local state. It works as expected. Sorry if I miss something. And also, I've already given examples of how to keep value.

**Comment by heroboy** [comment]
hello @suren-atoyan 
I know how to solve this problem by using the controlled mode.
In my second example I just add an option for word wrap. 
The second example, I want to demonstrate:
1. re-rendering doesn't cause value revert.
2. change other props like `options` doesn't cause value revert.
3. only change `language` cause value revert.

Here is the second example code. I don't think the `value` prop is from a local state.
```tsx
import React, { useRef, useState } from "react";
import ReactDOM from "react-dom";

import Editor, { monaco } from "@monaco-editor/react";

function App() {
  const valueGetter = useRef();
  const [lang, setLang] = useState("javascript");
  const [wordWrap, setWordWrap] = useState(false);
  function handleEditorDidMount(_valueGetter) {
    valueGetter.current = _valueGetter;
  }

  return (
    <>
      <button onClick={() => setLang("javascript")}>js</button>
      <button onClick={() => setLang("typescript")}>ts</button>
      <input
        id="ww"
        type="checkbox"
        onChange={(e) => setWordWrap(e.target.checked)}
      />
      <label htmlFor="ww">word wrap</label>
      <Editor
        height="90vh"
        language={lang}
        value={"// write your code here"}
        editorDidMount={handleEditorDidMount}
        options={{ wordWrap: wordWrap }}
      />
    </>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);

```

**Comment by suren-atoyan** [comment]
@heroboy, ah, ok, that was my fault, sorry. Now I see the problem, let me understand the reason, I'll come back to you soon.

**Comment by suren-atoyan** [comment]
I've found the problem, I'll fix it in the next version. It will happen this week, does it sound good to you?

**Comment by heroboy** [comment]
@suren-atoyan thanks. I said I know how to solve it. I just wonder why.

**Comment by suren-atoyan** [comment]
The problem is in [this](https://github.com/suren-atoyan/monaco-react/blob/master/src/Editor/Editor.js#L69) line. It has "historical" reasons. during the modification, I missed this part, it should have been removed.

**Comment by heroboy** [comment]
So as mentioned above, it is better to use `defaultValue` for uncontrolled component like others input control. But because it is `value` now, it's not good to rename it. Maybe you can use whether `onChange` is set to distinguish controlled or uncontrolled.

**Comment by suren-atoyan** [comment]
Hello @heroboy 

I've already fixed the issue you have. Please check version 3.7.1
