### ISSUE TITLE
Focus not working

### ISSUE THREAD

**Issue by bluenote10** [suren-atoyan/monaco-react#141]
**Describe the bug**

It looks like calling `editor.focus()` does not work.

**To Reproduce**

Here is a minimal example (in TypeScript). The code tries to give the editor focus in the `onEditorDidMount` callback. The goal is that the user can start typing in the editor immediately.

```ts
import React from 'react';
import ReactDOM from 'react-dom';

import Editor from "@monaco-editor/react";
import * as monacoEditor from 'monaco-editor/esm/vs/editor/editor.api';

type IStandaloneCodeEditor = monacoEditor.editor.IStandaloneCodeEditor

const EditorWrapper = () => {

  const onEditorDidMount = (_: () => string, editor: IStandaloneCodeEditor) => {
    editor.setPosition({lineNumber: 1, column: 6})
    editor.focus()
  }

  return (
    <Editor
      height="90vh"
      theme="dark"
      language="markdown"
      value={"Hello world"}
      editorDidMount={onEditorDidMount}
    />
  );
}

ReactDOM.render(
  <React.StrictMode>
    <EditorWrapper/>
  </React.StrictMode>,
  document.getElementById('root')
);
```

**Expected behavior**

The editor should get focused.

**Desktop (please complete the following information):**

 - OS: Ubuntu 18.04
 - Browser: Firefox 83, Chrome 80.0.3987.162
 - monaco-editor 0.21.2
 - @monaco-editor/react: 3.7.0

**Additional context**

I was using Monaco editor before in a non-React context, and there the editor focusing was working fine. Therefore I would assume this is not an upstream Monaco editor issue, but rather an issue in the React integration?

**Comment by suren-atoyan** [comment]
Hello @bluenote10 

The problem is in the sequence of the execution of the commands on the editor instance. I assume your command works fine, but after that, some other processes still remain for editor instance which take place after your command and lose the focus. So, there are two ways to fix this:

1) the short way to execute your command in the next tick - make a task or microtask in terms of the event loop. I've already created a working example for you. [Check it](https://codesandbox.io/s/monaco-editorsimple-usage-config-sg797?file=/src/index.js)
2) the long term way should be done from my side, I'll investigate the problem, and solve it in the next version; technically, I reckon, `editorDidMount` should be triggered a little bit later.

**Comment by bluenote10** [comment]
Cool thanks, I can confirm that focusing works if I do:

```ts
const onEditorDidMount = (_: () => string, editor: IStandaloneCodeEditor) => {
  editor.setPosition({lineNumber: 1, column: 6})
  window.requestAnimationFrame(() => {
    editor.focus()
  })
}
```

> I've already created a working example for you. Check it

You link points to a version that seem to be exactly my original issue, but no problem. Just out of curiosity: Did you use `requestAnimationFrame` as well?

> I assume your command works fine, but after that, some other processes still remain for editor instance which take place after your command and lose the focus.

So that seems to be the case. I'm wondering what these "other processes [...] taking place after your command" could be. From the user side it looks like there is nothing else, and it would be natural to assume that the editor is fully ready at `onDidMount` time.

**Comment by suren-atoyan** [comment]
> You link points to a version that seem to be exactly my original issue, but no problem. Just out of curiosity: Did you use requestAnimationFrame as well?

I am sorry, I forgot to save. [Check](https://codesandbox.io/s/monaco-editorsimple-usage-config-sg797?file=/src/index.js) it one more time, please.

> So that seems to be the case. I'm wondering what these "other processes [...] taking place after your command" could be. From the user side it looks like there is nothing else, and it would be natural to assume that the editor is fully ready at onDidMount time.

I haven't checked it yet, but surely the editor has to be ready onDidMount time. BTW the Editor component implementation is [here](https://github.com/suren-atoyan/monaco-react/blob/master/src/Editor/Editor.js)

**Comment by suren-atoyan** [comment]
@bluenote10 
Here is the problem. In [this](https://github.com/suren-atoyan/monaco-react/blob/master/src/Editor/Editor.js#L95) line. After we trigger `editorDidMount` we call `setIsEditorReady(true)`, which cause a re-rendering the [MonacoContainer](https://github.com/suren-atoyan/monaco-react/blob/master/src/Editor/Editor.js#L107) component. The last one re-renders the root of the editor, which leads to losing the focus.

**Comment by suren-atoyan** [comment]
Hello @bluenote10 

The issue is fixed. Please check version - v3.7.4

[Here](https://codesandbox.io/s/monaco-editorsimple-usage-config-forked-rhpfn?file=/src/index.js) is the example you've mentioned earlier with the new version 🙂 

Thank you for your support!

**Comment by bluenote10** [comment]
Great, thanks for the fix!
