### ISSUE TITLE
Icons are not displaying while use the editor in a existing project using themes of material-ui

### ISSUE THREAD

**Issue by jeevaengg21** [suren-atoyan/monaco-react#147]
The icon of the editor is displaying fine when trying out the library in a standalone Reactjs project. But the icons are just appearing as a square box when integrating this library in my existing project. Seems like I am missing something or best practices, can you please assist me in getting the icons displayed in the editor. Thanks

![image](https://user-images.githubusercontent.com/17171744/102312335-82f90680-3f94-11eb-80c0-8ac77865356d.png)

**Comment by suren-atoyan** [comment]
Hello @jeevaengg21 

It seems like there are some global styles in your project (or in the libraries that your project uses) which conflicts with the monaco styles. Or your project code somehow blocks some requests. I would suggest checking styles first and after the network. Or if you can provide me a link of your repo I can take a look.

**Comment by suren-atoyan** [comment]
I am closing this because of insufficient information and inactivity. Feel free to re-open it if the issue exists.
