### ISSUE TITLE
Tabs / multiple files example

### ISSUE THREAD

**Issue by evanfrawley** [suren-atoyan/monaco-react#148]
Hi! Thank you so much for building this library. Definitely the best wrapper for Monaco out there. 

Do you have a quick example that enables multiple files/tabs for the ControlledEditor?

**Comment by suren-atoyan** [comment]
Hello @evanfrawley, thank you for your feedback!

In the next major version, a new API will be provided for a multi-file editor.

Currently, you should do it manually, you have access to [monaco-instance](https://github.com/suren-atoyan/monaco-react#monaco-instance) and [editor-instance](https://github.com/suren-atoyan/monaco-react#editor-instance); the implementation depends on what you exactly want to achieve.

A short solution for a well-known problem: if you have a problem with models, which stills the same through different files/folders, you can change the `key` property according to file/folder (`<Editor key={file.id} />`), it forces the component to mount/unmount which leads to new model creation.

**Comment by evanfrawley** [comment]
@suren-atoyan thank you for the quick reply! I'll give that a shot and update here with the boilerplate code when I get it working for other folks in the future who would want to use multiple files

**Comment by evanfrawley** [comment]
Here's the editor file that I got working :) Note: it uses `theme-ui` for `Flex`, but that's just a fancy pre-css'd `flex` div. 

```jsx

import Editor, { monaco } from "@monaco-editor/react";
import React, { useEffect, useRef, useState } from "react";
import { Flex } from "theme-ui";

const indexCSS = `body {
  background-color: black;
}`;

const indexMD = `# hi there`;

function BasicEditor() {
    const editorRef = useRef();
    const monacoRef = useRef();
    const [initialized, setInitialized] = useState(false);
    const [isEditorReady, setIsEditorReady] = useState(false);
    const [currentModel, setCurrentModel] = useState("urn:index.md");

    useEffect(() => {
        async function runOnLoad() {
            monacoRef.current = await monaco.init();
            monacoRef.current.editor.createModel(indexMD, "markdown", "urn:index.md");
            monacoRef.current.editor.createModel(indexCSS, "css", "urn:index.css");

            monacoRef.current.languages.typescript.javascriptDefaults.setEagerModelSync(
                true
            );
            setInitialized(true);
            if (editorRef && editorRef.current) {
                editorRef.current.setModel(
                    monacoRef.current.editor.getModel(currentModel)
                );
            }
        }
        runOnLoad();
    }, []);

    function handleEditorDidMount(_, editor) {
        editorRef.current = editor;
        setIsEditorReady(true);
        if (monacoRef && monacoRef.current) {
            editorRef.current.setModel(monacoRef.current.editor.getModel(currentModel));
        }
    }

    const setMD = () => {
        setCurrentModel("urn:index.md");
    };

    const setCSS = () => {
        setCurrentModel("urn:index.css");
    };

    useEffect(() => {
        if (isEditorReady && initialized) {
            editorRef.current.setModel(monacoRef.current.editor.getModel(currentModel));
        }
    }, [currentModel]);

    if (!initialized) {
        return null;
    }

    return (
        <Flex sx={{ flexDirection: "column" }}>
            <Flex>
                <Flex onClick={setMD}>index.md</Flex>
                <Flex onClick={setCSS}>index.css</Flex>
            </Flex>
            <Editor
                height="80vh"
                theme="dark"
                value=""
                language="scss"
                editorDidMount={handleEditorDidMount}
            />
        </Flex>
    );
}

export default BasicEditor;
```

<img width="416" alt="CleanShot 2020-12-16 at 20 54 05@2x" src="https://user-images.githubusercontent.com/13992385/102445700-f4f73d00-3fe0-11eb-9512-b2f8bf7403cf.png">
<img width="418" alt="CleanShot 2020-12-16 at 20 53 59@2x" src="https://user-images.githubusercontent.com/13992385/102445703-f58fd380-3fe0-11eb-9701-d2da2228a079.png">

**Comment by suren-atoyan** [comment]
Hey @evanfrawley 

I reviewed your code. Everything is okay, I would just like to suggest some improvements/corrections:

1) You repeated this code segment 3 times

```
if (monacoRef && monacoRef.current) {
    editorRef.current.setModel(monacoRef.current.editor.getModel(currentModel));
}
```

One in `handleEditorDidMount`, another one in the first `useEffect`, and the last one in the last `useEffect`. The main aim of that code segment is to keep `currentModel` synchronized with `editor model` (only when the editor is ready). So, it should be a `useEffect` with dependencies `isEditorReady` and `currentModel`. See line 40 in the link below.

2) You can avoid having two different flags `isEditorReady` and `initialized`. The existence of both is connected with the fact that you've separated `handleEditorDidMount` and `monaco.init(...)`. See line 18 in the link below.

3) Don't use `language` and `value` props in the Editor component if you are going to manually change the model. It means in some cases the language prop will be `scss` but you will work with `markdown`. See line 54 in the link below.

[Here](https://codesandbox.io/s/monaco-editorreact---multi-file-editor-w468d?file=/src/index.js) is the improved version 🙂 

Glad to help!
