### ISSUE TITLE
Syntax highlighting breaks when using monaco-editor values in the code

### ISSUE THREAD

**Issue by Flavyoo** [suren-atoyan/monaco-react#151]
**Describe the bug**
Importing and using types from `monaco-editor/esm/vs/editor/editor.api` in the JS code causes the syntax highlighting to stop working.

**To Reproduce**
In a project with **monaco-react**, and the **monaco-editor** packages installed:

1. Render the Editor component
2. In a render function, reference a value from the editor namespace:

```
return (
<>
<p>lineHeight {editor.EditorOption.lineHeight}</p>
<Editor .../>
</>
)
```
I believe this issue is related to this: https://github.com/react-monaco-editor/react-monaco-editor/issues/161. I will try the Webpack plugin answer to see if that will fix it. I posted this issue here, since I thought with this package, monaco should work with React without extra webpack configurations.

**Note**: The sandbox has example of the code needed to reproduce it.
[Codesandbox example](https://codesandbox.io/s/friendly-cerf-ock7r?file=/src/App.tsx:0-951)

**Expected behavior**
Syntax highlighting should continue to work.

**Screenshots**
**With the language set to typescript**
![syntaxhighlighting](https://user-images.githubusercontent.com/14948074/103061340-11fbb500-4579-11eb-8518-f448e78e197e.png)

**Desktop (please complete the following information):**
 - OS: [Mac OS]
 - Browser: [Edge]
 - "monaco-editor": "^0.21.2",
 - "@monaco-editor/react": "^3.7.2",

**Additional context**

**Comment by suren-atoyan** [comment]
Hello @Flavyoo 

You can import types from `monaco-editor/esm/vs/editor/editor.api`, without needing to use webpack as documentation says. [Here](https://github.com/suren-atoyan/monaco-react/blob/master/src/index.d.ts#L4) is an example of how you can use types. In the example you've mentioned, you directly `import { editor } from monac-editor/...`, which causes the initialization of monaco which conflicts with the existing one.

If you need editor instance, [here](https://github.com/suren-atoyan/monaco-react#editor-instance) is a documentation part for that.

[Also, check the equivalent of your example](https://codesandbox.io/s/determined-wright-x0dmg?file=/src/App.tsx)

So, use `monaco-editor` only for type to avoid duplication.

**Comment by Flavyoo** [comment]
@suren-atoyan Your answer helped me fix it. I replaced my imports for the editor with your suggestion. However, just that didn't fix it, so Instead I had to reference the value from the monaco instance instead of the imported types.

Instead of `monacoEditor.editor.EditorOption.lineHeight` I used `this._monaco.editor.EditorOption.lineHeight` which caused the syntax highlighting to work again.
