### ISSUE TITLE
Syntax highlighting stops working when making direct use of monaco module

### ISSUE THREAD

**Issue by bluenote10** [suren-atoyan/monaco-react#155]
**Describe the bug**

I'm observing an interesting effect that syntax highlighting stops working if I make direct use of some Monaco editor types.

**To Reproduce**

My setup is based on create-react-app in Typescript. A minimal reproducing `index.tsx` would be this:

```ts
import React from "react";
import ReactDOM from "react-dom";

import Editor from "@monaco-editor/react";
import * as monacoEditor from "monaco-editor/esm/vs/editor/editor.api";

function unusedDummy() {
  // Commenting out these lines makes syntax highlighting work.
  new monacoEditor.Position(0, 0);
  new monacoEditor.Range(0, 0, 0, 0);
}

ReactDOM.render(
  <React.StrictMode>
    <Editor
      height="400px"
      theme="dark"
      language="javascript"
      value={"console.log('test')\n\nfunction test() {}\n\n// comment"}
    />
  </React.StrictMode>,
  document.getElementById("root")
);
```

The editor renders as:

![image](https://user-images.githubusercontent.com/3620703/103438412-3cadd380-4c33-11eb-8c34-1d7f0b182d46.png)

Commenting out the entire `unusedDummy` function verifies that in general everything works fine for me:

![image](https://user-images.githubusercontent.com/3620703/103438434-5cdd9280-4c33-11eb-8ea9-186ba9b06fbc.png)

**Edit:**

If I'm importing the native Monaco module via:

```ts
import * as monacoEditor from "monaco-editor";
```

the syntax highlighting seems to work for a few seconds, but then some internal error occurs:

![image](https://user-images.githubusercontent.com/3620703/103438572-6ca9a680-4c34-11eb-8f3b-fd86fa9aaa15.png)

The reason I was importing it from `monaco-editor/esm/vs/editor/editor.api` was that I saw that this is how `monaco-react` imports it internally.

**Expected behavior**

Syntax highlighting should continue to work.

**Desktop (please complete the following information):**

 - OS: Ubuntu 18.04
 - Browser: Firefox 83, Chrome 80.0.3987.162
 - monaco-editor 0.21.2
 - @monaco-editor/react: 3.7.0

**Additional context**

I'm not sure if this could be an upstream issue as well. The closest I have found is https://github.com/microsoft/monaco-editor/issues/854.

**Comment by suren-atoyan** [comment]
Hello @bluenote10 

You can use `monaco-editor` package only for types. You can't use it directly; this library loads monaco sources from CDN (default behavior, you can change it). Direct usage of monaco from `monaco-editor` will initialize new monaco instance, which will conflict with the existing one.

> The reason I was importing it from monaco-editor/esm/vs/editor/editor.api was that I saw that this is how monaco-react imports it internally.

Only types were used, and only in [index.d.ts](https://github.com/suren-atoyan/monaco-react/blob/master/src/index.d.ts) file.

For `Position` and for `Range`, you need to access to [monaco instance](https://github.com/suren-atoyan/monaco-react#monaco-instance)

**Comment by bluenote10** [comment]
I see, now it makes sense!

What do you think about adding the `monacoInstance` as a third argument to the `editorDidMount` callback? The motivation would be:
- I assume that the Monaco instance must be available at that point, considering that even the editor instance has been created. This would get rid of the need to obtain the Monaco instance asynchronously.
- That's where people start interacting with the editor instance, so there is a certain likelihood that they may need to instantiate types from the Monaco instance as well. At least in my case, this was the only point where I need to instantiate things like `Position` and `Range`.
- If people need both the editor + Monaco instances across the entire component, the `editorDidMount` would be a good place to store them both.

----

Off-topic: Taking the opportunity here to thank you for the nice bindings + great support! In case you are curious, your library is driving my just published note taking app [notemarks](https://github.com/notemarks/notemarks) :tada:

**Comment by suren-atoyan** [comment]
Hello @bluenote10 

We had couple of discussions about `monacoInstance` as a third argument in the `editorDidMount`. I'll have another look to it. Plus, I am planning to release a new major version, so, things can change.

<hr />

About `notemarks`. Well done app - open-source is great.
