### ISSUE TITLE
Strange Bug: ControlledEditor adds ". ." to value when pressing space key fast and pressing other keys at the same time.

### ISSUE THREAD

**Issue by cliid** [suren-atoyan/monaco-react#158]
**Describe the bug**
When using `ControlledEditor`, pressing the space key fast and pressing other keys at the same time, adds ` . . ` to text.

**To Reproduce**

1. Go to [https://codesandbox.io/s/monaco-editorreact---controlled-editor-yg5il?fontsize=14](https://codesandbox.io/s/monaco-editorreact---controlled-editor-yg5il?fontsize=14)
2. Press space key 3 times a second and also press any other key (ex) `k`).
3. See bug

**Expected behavior**
No ` . . ` added to text.

**Screenshots**
No screenshot, but easy to reproduce.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - Version: 84.0.1

**Additional context**

**Comment by suren-atoyan** [comment]
Hello @cliid 

Actually, it's not a bug and isn't related to the `monaco-editor`. It's a typing feature in MacOS (not sure about other operating systems). Just google `double space creates a period` or [check](https://osxdaily.com/2019/03/27/disable-period-typing-shortcut-mac/) this out. If you are using MacOS, just check it in any writable place, text input, browser's URL box, even devtools' console; write something (it's important, something should be written, before `double-space`) and do `double-space`

**Comment by cliid** [comment]
Oh, thanks. I've never known that feature. I'll close this issue.
