### ISSUE TITLE
Expose a `editorWillMount` callback

### ISSUE THREAD

**Issue by danielemesh** [suren-atoyan/monaco-react#162]
Hi,
first of all thanks for this wonderful lib!

Is it possible to expose a prop for a callback to fire after the `monaco.init()` and before the call to `monacoInstance.editor.create()` ?

something like:
```typescript
async function someFunc() {
  const monacoInstance = await monaco.init();

  // fire a callback that returns a promise here...
  if (props.editorWillMount) {
    await props.editorWillMount(monacoInstance);
  }

  const wrapper = document.getElementById('some-id');
  const editor = monacoInstance.editor.create(wrapper, options);

  if (props.editorDidMount) {
    props.editorDidMount(editor);
  }
}
```

Thing is, I need to do some async operations before the editor is being created.

Thanks!

**Comment by suren-atoyan** [comment]
Hello @danielemesh 

Thank you for your feedback 🙂 
Right now, I am planning a new major version and something like `editorWillMount` will be available in the new version. Now critical your case now? I mean, maybe it's possible to find some workaround before the new version release?

**Comment by suren-atoyan** [comment]
Technically, it's always possible. `monaco.init()` do initialization once, and returns the same promise for the further calls. The `Editor` component will use `monaco.init()` when you render it. I mean to say if it's essential to do some work before the editor is being created, you can use `monaco.init().then(...)`, do all the async work you need, and only after that render the `Editor` component. Something like this:

```javascript
function SomeComponent() {
  const [amIReady, setAmIReady] = useState(false);

  useEffect(() => {
    monaco.init().then(() => {
      // do everything you need
      // ...

      // and only after that say to the world that you are ready

      setAmIReady(true);
    });
  }, []);

  return amIReady
    ? <Editor height="100vh" language="javascript" value="// some comment" loading={null} />
    : 'We are working right now...'
}
```

**Comment by danielemesh** [comment]
Thanks for the quick response, I appreciate it!
What you suggested did the trick, thank you very much :)

Looking forward for the next version release 🥇

**Comment by suren-atoyan** [comment]
Hello @danielemesh 

The new version is here 🙂 And as I promised, there is something like `editorWillMount`, it's called `beforeMount`. I would love to get feedback about the new version.

**Comment by danielemesh** [comment]
Hi,
Thanks for the update, I'll post a feedback here as soon as I'll upgrade to v4.
I read the changelog, and seems like I'll be using most of the new additions!
Currently I have a wrapper around your Editor component which does all these new stuff 😀.

BTW your docs are also very well written, it's obvious you care a lot for your consumers!
