### ISSUE TITLE
[Question] best way to define themes

### ISSUE THREAD

**Issue by Kikobeats** [suren-atoyan/monaco-react#164]
Hello,

Thanks for shipping v4, it looks amazing!

I'm trying to determine the best way for registering some themes at Monaco instance.

code related: https://github.com/microlinkhq/cards/blob/master/packages/app/src/components/live-editor.js#L82

my question is, should I use a more friendly Monaco handler in order to register themes as soon as possible? is it okay to wait for the monaco instance provided by the loader, or there is a thing I can do to avoid delay the action?

**Comment by suren-atoyan** [comment]
Hello, @Kikobeats. Thank you for the feedback.

The way you did is also acceptable, however there other options too:

1) If you want to define themes as soon as possible (and maybe do some other work with `monaco` instance), you can call `loader.init()` function out of the `React` component. In the `loader`, there is nothing `React` specific, it's pure `js`. So, you can call it, for example, in your `index.js` file. (NOTE: the `Editor` component also uses the same `loader.init()` function)

2) you can use the newly released `beforeMount` prop. It exposes the `monaco` instance as a first argument and being called before the `editor` is mounted

3) also, you can use the newly released `useMonaco` hook, again, to gain access to `monaco` instance. In this case, the result will be similar to the above one, you've shared

**Comment by Kikobeats** [comment]
Thanks for the quick reply!

 I think `beforeMount` is great for my use case and it works perfect 🙂
