### ISSUE TITLE
Cannot import "useMonaco"

### ISSUE THREAD

**Issue by hckhanh** [suren-atoyan/monaco-react#165]
I get this error when upgrading the editor to `4.0.1`

```
TS2614: Module '"../../../node_modules/@monaco-editor/react/lib/types"' has no exported member 'useMonaco'. Did you mean to use 'import useMonaco from "../../../node_modules/@monaco-editor/react/lib/types"' instead?
```

![image](https://user-images.githubusercontent.com/6380436/104871004-82c99d80-597c-11eb-9147-630876eb0438.png)

**Comment by suren-atoyan** [comment]
Hello @hckhanh, sorry, it's my fault, missing type. It's already fixed, please check the version `v4.0.2`

And if you have any other feedback about the `v4`, please let me know.
