### ISSUE TITLE
Uncaught (in promise) Error: ENOENT: no such file or directory, open 'https:/cdn.jsdelivr.net/npm/monaco-editor@0.21.2/min/vs/editor/editor.main.js'

### ISSUE THREAD

**Issue by maifeeulasad** [suren-atoyan/monaco-react#166]
**Describe the bug**

I tried to use `monaco-react` in my react-electron project , then I encountered this : 
**Uncaught (in promise) Error: ENOENT: no such file or directory, open 'https:/cdn.jsdelivr.net/npm/monaco-editor@0.21.2/min/vs/editor/editor.main.js'**

**To Reproduce**

>> clone https://github.com/maifeeulasad/open-code-electron.git
>> checkout https://github.com/maifeeulasad/open-code-electron/tree/8d5bdd8c017b2cb5fe06298b56f171f9090db083
>> yarn
>> yarn start

Or, please add a minimal code snippet to reproduce the issue, for example in [codesandbox](https://codesandbox.io/).

**Expected behavior**
Well I guess a simple code editor, right ?

**Screenshots**
![Screenshot from 2021-01-18 17-32-47](https://user-images.githubusercontent.com/29339330/104910318-59783400-59b3-11eb-8eba-14c444550147.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chromium(electron-embedded)
 - Version ---

**Additional context**
monaco-react in [react-electron](https://github.com/electron-react-boilerplate/electron-react-boilerplate) boilerplate.

**Comment by suren-atoyan** [comment]
Hello @maifeeulasad 

It seems like your environment can't download files from `CDN`. By default `monaco` sources are being downloaded from `CDN` (you can change that behavior) Please, read [the section](https://github.com/suren-atoyan/monaco-react#for-electron-users) about `electron`

**Comment by maifeeulasad** [comment]
[This](https://github.com/suren-atoyan/monaco-react/issues/48#issuecomment-572249383) helped, actually worked.

**Comment by suren-atoyan** [comment]
@maifeeulasad that great, could you please tell me what was the actual problem?

**Comment by maifeeulasad** [comment]
@suren-atoyan I'm not quite sure, but I'm sure that, It was calling some resource from the internet. Although it existed, and I could load it from the browser, `electron` couldn't load it. Now its loading from local assets.

**Comment by suren-atoyan** [comment]
@maifeeulasad ah, I see, okay - thank you for letting me know

**Comment by maifeeulasad** [comment]
@suren-atoyan irrelevant to this topic, but have you done some project where you input file/select file from a react component, please let me know. Or some project you have seen. That would be really helpful. Thanks in advance.

**Comment by suren-atoyan** [comment]
I am sorry, but I didn't get `where you input file/select file from a react component` this part. May I ask you to explain it?

**Comment by maifeeulasad** [comment]
I'm trying to use IPC to communicate between *my react component* and *main electron process*.
In component :
```
export default class A extends React.Component{
.....
  openFile = () => {
    console.log('test');
    ipcRenderer.send('file-command', 'open');
  };
.....
}
```
And in main : 
```
  mainWindow.webContents.on('file-command', () => {
    console.log('file open request');
  });

  mainWindow.on('file-command', () => {
    console.log('file open request');
  });

  ipcRenderer.on('file-command', () => {
    console.log('file open request');
  });
```
Tried all separately. But none of these works.

**Comment by suren-atoyan** [comment]
@maifeeulasad unfortunately, I am not familiar with the topic. I work with IPC, with not in the context of the electron. The interprocess communications between renderers in the electron are a little bit different rather than the usual IPC.

**Comment by maifeeulasad** [comment]
@suren-atoyan ok thanks. And randomly asking, I'm just looking for some contributors in my project. Are you free ? Or do you know someone ? Please let me know.

**Comment by suren-atoyan** [comment]
No, thank you, I am not free
