### ISSUE TITLE
Multiple Editor instance sync content

### ISSUE THREAD

**Issue by skrypka** [suren-atoyan/monaco-react#167]
Hello, Suren!

Today I tried to upgrade to v4, but reverted
because I have 2 separate editors on page. and they started to have same content.

Have you already ported your demo page to v4, because you have 2 editors too there?

**Comment by suren-atoyan** [comment]
Hello @skrypka 

Could you please check the [section](https://github.com/suren-atoyan/monaco-react#multi-model-editor) multi-model editor? And also, if it's possible, share the code segment where you use the `Editor` component. Thank you!

**Comment by skrypka** [comment]
This is current(v3, I did not saved refactored for v4 version) App.js
it's just 2 simple Editor instances https://gist.github.com/skrypka/963fed22d2fa15dcac1dcce08c2ecd34#file-app-js-L310-L329
later I'm using `editorDidMount={handleEditorDidMount}` to get reference to editor, so I can get/change content.

Current deployed app with v3: https://play.disopt.com/

**Comment by suren-atoyan** [comment]
@skrypka Okay, for a quick fix just give them different `path`s. There is a new property called `path`.

And for the long term, please read [the doc](https://github.com/suren-atoyan/monaco-react/blob/master/v4.changes.md) describing the changes of `v4`. It's a major update, there are some breaking changes.

Let me know if it helps.

**Comment by skrypka** [comment]
Adding "path" helped. Thank you so much for the library!
