### ISSUE TITLE
The monaco editor fails to initialize.

### ISSUE THREAD

**Issue by icy-meteor** [suren-atoyan/monaco-react#169]
**Describe the bug**
The monaco editor fails to initialize.

**To Reproduce**
This seems to occur very randomly. Haven't been able to justify a pattern.
Have made sure no browser extensions or windows extensions are running during this behaviour.

**Expected behavior**
Editor getting mounted properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/22114682/105316070-5a44dc00-5be6-11eb-9f27-ff269e4da22d.png)

Is there any way to see what is causing this error to happen?

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: v87.0.4280.141

**Comment by suren-atoyan** [comment]
Hello @icy-meteor. Thank you for opening the issue.

Could you please tell me more about your environment? What boilerplate/builder you use - `create-react-app`, `vite`, `create-snowpack`, etc.

**Comment by icy-meteor** [comment]
Default create-react-app without ejecting.
    "react": "^16.8.5"
    "react-dom": "^16.8.5"
    "react-scripts": "^3.3.0"

**Comment by suren-atoyan** [comment]
Just tried with the latest `CRA`

```
"react": "^17.0.1",
"react-dom": "^17.0.1",
"react-scripts": "4.0.1",
```

and everything is ok, will try with your version too. Did you try it in incognito mode?

**Comment by icy-meteor** [comment]
So, I'll tell you what happens. It seems to work for me too, and for many of us here. 
But, some of the consumers on our client-facing application have complained regarding this issue where they see a white-screen in place of the editor. When I took a look at the console, I saw the error mentioned above.

This could mean that probably something is causing the editor to not get initialised. And most likely, I am feeling that it has something to do with the ISP. Does the package try to connect to any external server before initialisation?

**Comment by suren-atoyan** [comment]
@icy-meteor By default, it downloads monaco sources from `CDN` and you can change that behavior. There is no other connection to external servers and can't be.

[Here](https://github.com/suren-atoyan/monaco-loader/blob/master/src/config/index.js) is the default configuration of the loader. You can configure it to download from another CDN as well as from your local files. [Here](https://github.com/suren-atoyan/monaco-react#loader-config) is how you can configure it.

**Comment by suren-atoyan** [comment]
If you load it from your local files you need to do those steps:

1) `cd your_cra_project_directory`
2) `npm install monaco-editor # yarn add monaco-editor`
3) `cp -R node_modules/monaco-editor ./public`
4)

```javascript
import Editor, { loader } from '@monaco-editor/react';

loader.config({
  paths: {
    vs: '/monaco-editor/min/vs'
  }
});

function App() {
  return (
      <Editor
        defaultLanguage="javascript"
        defaultValue="// some comment"
        height="90vh"
      />
  );
}
```
That's all. Here is how you can check the result:

before

<img width="1089" alt="Screen Shot 2021-01-21 at 13 44 14" src="https://user-images.githubusercontent.com/13118722/105333251-f07d0000-5bee-11eb-8d26-5308fbfbbdd0.png">

after

<img width="1125" alt="Screen Shot 2021-01-21 at 13 45 05" src="https://user-images.githubusercontent.com/13118722/105333286-fa9efe80-5bee-11eb-9dab-3e7d38a975bb.png">

**Comment by icy-meteor** [comment]
Thank you so much for the detailed explanation!
Will try this and get back to you.

**Comment by icy-meteor** [comment]
BTW, asked the user to try with a different internet connection and it worked! 
So, it was the ISP :) 

Either way, I will be shifting to the method explained by you so that we don't face these issues.
Will close the issue after trying the above.

**Comment by icy-meteor** [comment]
Everything worked perfectly! Thanks, @suren-atoyan for the quick response.

**Comment by sabry-awad97** [comment]
import Editor, { loader } from '@monaco-editor/react';

loader.config({
  paths: {
    vs: 'https://www.unpkg.com/monaco-editor/min/vs',
  },
});

const CodeEditor = () => {
  return <Editor height="90vh" />;
};

export default CodeEditor;

**Comment by sKopheK** [comment]
> ```js
> import Editor, { loader } from '@monaco-editor/react';
> 
> loader.config({
>   paths: {
>     vs: 'https://www.unpkg.com/monaco-editor/min/vs',
>   },
> });
> 
> const CodeEditor = () => {
>   return <Editor height="90vh" />;
> };
> 
> export default CodeEditor;
> ```

fingers crossed for another ISP not blocking this domain...
