### ISSUE TITLE
Attempted import error: 'loader' is not exported from '@monaco-editor/react'

### ISSUE THREAD

**Issue by icy-meteor** [suren-atoyan/monaco-react#170]
**Describe the bug**
I get an error "Attempted import error: 'loader' is not exported from '@monaco-editor/react'." when I try import { loader } from "@monaco-editor/react";

**Expected behavior**
Followed the code given in docs, ideally it should allow me to customize the config.

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.7 Catalina
 - Browser: Brave

**Comment by suren-atoyan** [comment]
@icy-meteor  which version of `@monaco-editor/react` do you use? The `loader` utility is from `v4` (read more [here](https://github.com/suren-atoyan/monaco-react/blob/master/v4.changes.md))

**Comment by icy-meteor** [comment]
Oops, my bad. I was in v3. 
I will switch to v4. Thanks :)
