### ISSUE TITLE
How to get current code selection? 

### ISSUE THREAD

**Issue by PaperjetStudios** [suren-atoyan/monaco-react#171]
Hey guys, 

This library is truly amazing and has proven incredibly useful. 

I have a question though - how would one get currently selected code? I see in the actual microsoft project there's:

<code>window.editor.getModel().getValueInRange(window.editor.getSelection())</code>

But the editor reference only exposes getValue()

**Comment by suren-atoyan** [comment]
Hello, @PaperjetStudios, thank you for your feedback.

[Here](https://codesandbox.io/s/editor-instance-forked-pcdh3?file=/src/App.js) is an example of how you can get a selected value.

**Comment by PaperjetStudios** [comment]
Great thank you so much! I was using 3.8.something and not 4.0.4
