### ISSUE TITLE
Keep v3 doc and reference it in README

### ISSUE THREAD

**Issue by hacker0limbo** [suren-atoyan/monaco-react#173]
Hello:

I see recently this project just released v4, the migration guide is detailed as well. However, may i suggest we still keep a v3 doc in master branch and reference it in README so that we can directly open it in browser. Otherwise each time we have to manually checkout to v3.x tag branch and see its readme.

Really appreciate your effort for this excellent project, cheers!

**Comment by suren-atoyan** [comment]
Hello @hacker0limbo,

Thank you for your feedback, I've already added the old version README link, please check the "news" section. Does it look good?

<img width="903" alt="Screen Shot 2021-01-26 at 14 04 43" src="https://user-images.githubusercontent.com/13118722/105830968-96f64600-5fdf-11eb-810b-06a2da1b20ab.png">

**Comment by hacker0limbo** [comment]
Fantastic! It looks great!
