### ISSUE TITLE
onValidate callback might cause performance issue in v4?

### ISSUE THREAD

**Issue by hacker0limbo** [suren-atoyan/monaco-react#174]
I see in v4 there is a new API `onValidate ` exposed. And according to the doc:

> `onValidate` is an additional property. **An event is emitted when the content of the current model is changed** and the current model markers are ready. It will be fired with the current model markers

So the callback event will get fired each time the model is changed? Assuming in the `oValidate` callback, it will send a request to backend and get data and then set markers in editor. I am not sure if this will cause performance issue.

What i did in v3 is since there is no such api i add a debounce to avoid such case, the persuade code might like this:

```js
function handleEditorDidMount(_valueGetter, editor) {
  editor.getModel().onDidChangeContent(ev => {
    clearTimeout(timer);

   // debounce
    timer = setTimeout(() => {
      // validate function, will send request and set model markers
      validate();
    }, 1000);
  });
}
```

I did not test in v4, its just my personal concern.

Again thanks for your effort to this project.

**Comment by suren-atoyan** [comment]
Hello @hacker0limbo 

No, it's just a reflection of `set/getModelMarkers`. There is no overhead, plus an event isn't emitted when the content of the current model is changed, it's emitted when the content of the current model is changed and the current model markers are ready. It's already being done under the hood, I just expose it through API. If you want to prevent requests based on you application logic, you can do it inside the `onValidate` handler.

Please check the [codesandbox](https://codesandbox.io/s/onvalidate-4t5c2?file=/src/App.js) example.
