### ISSUE TITLE
vscode dark plus theme

### ISSUE THREAD

**Issue by ChristopherHButler** [suren-atoyan/monaco-react#175]
**Is your feature request related to a problem? Please describe.**
No problem, just a nice to have preference.

**Describe the solution you'd like**
I would like to be able to use the vscode dark plus default theme with monaco-react the same as using vs-dark.

**Comment by suren-atoyan** [comment]
Hello @ChristopherHButler, `vs-dark` is just one of the default themes of `monaco-editor`, I didn't choose it or define it myself. You can define your custom theme, check the [playground](https://monaco-react.surenatoyan.com/), there are lots of themes.

Maybe I missed something?

**Comment by ChristopherHButler** [comment]
Hey @suren-atoyan,
Maybe I am missing something too. In the [vscode repo](https://github.com/microsoft/vscode/tree/master/extensions/theme-defaults/themes) it seems that both `vs-dark` and `dark plus` are default themes so I just thought I would be able to pass a theme prop for `dark plus` the same as `vs-dark`. Maybe I don't have the right prop name ? 🤔
I did see that I can define my own theme so I can probably copy `dark plus` into my own repo and get it working. :)

**Comment by ChristopherHButler** [comment]
I take back my last comment 😬
After some searching I've learned a bit more about themes in vscode vs monaco editor... largely thanks to [this article](https://codesandbox.io/post/introducing-themes#how-it-works) by Ives van Hoorne where he explains the issue. I also found a [neat tool](https://github.com/Nishkalkashyap/monaco-vscode-textmate-theme-converter) that lets you convert a vscode theme to something monaco can understand however I was unable to get it working. I can close this issue but if you are interested I could let you know if I find a solution so you could provide more themes "out of the box".
