### ISSUE TITLE
onMount is not one of the EditorProps, as described in the README

### ISSUE THREAD

**Issue by Seanmclem** [suren-atoyan/monaco-react#176]
"@monaco-editor/react": "^3.7.2",
    "monaco-editor": "^0.21.2",

In the readme, Usage, GetValue, there is a section that describes setting up the <Editor> with the prop `onMount`

`onMount={handleEditorDidMount}`

However, the Type `EditorProps` does not contain an `onMount`. There are other areas where the mounting/lifecycle methods seem incorrect. I was going to make a PR to correct them all but I just keep finding more

**Comment by suren-atoyan** [comment]
Hello @Seanmclem 

You use version v3.x.x with v4.x.x docs

[Here](https://github.com/suren-atoyan/monaco-react/blob/master/v4.changes.md) is version 3.x.x docs
