### ISSUE TITLE
Which version of monaco editor does monaco-react support

### ISSUE THREAD

**Issue by ChristopherHButler** [suren-atoyan/monaco-react#178]
**Describe the bug**
I have made a project with create react app and want to override the webpack config and use monaco-editor-webpack-plugin. On their page they have a matrix showing which verion of the plugin supports which version of monaco-editor. When I try to use react-app-rewired to add the plugin I get a strange error: 

```
Failed to compile.

Cannot find module 'vs/editor/contrib/anchorSelect/anchorSelect'
```

**To Reproduce**

1. create app with create react app
2. install @monaco-editor/react
3. install monaco-editor-webpack-plugin
4. install react-app-rewired as a dev dependency
5. change the build and start scripts to `react-app rewired start` (and build)
6. create a config-overrides.js file in the top level of your project

In that file try to add the plugin: 

```
const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin');

module.exports = function override(config, env) {
  config.plugins.push(new MonacoWebpackPlugin({
    languages: ['json'],
  }));
  return config;
}
```

**Expected behavior**
it compiles and works...
Note: I would be happy to know which version of monaco-editor @monaco-editor/react wraps / uses (not sure how you do things internally) so that I can check the plugin matrix and make sure I have the correct versions.

**Desktop (please complete the following information):**
"@monaco-editor/react": "^4.0.9",
"monaco-editor-webpack-plugin": "^3.0.0",
"react-app-rewired": "^2.1.8"

**Comment by suren-atoyan** [comment]
Hello @ChristopherHButler 

This library has been created to avoid using webpack plugins. You don't need to use any webpack configuration file, you don't need to rewire CRA, just import and use the `Editor` component.

**Comment by suren-atoyan** [comment]
Please read the [`README`](https://github.com/suren-atoyan/monaco-react/blob/master/README.md) file

**Comment by ChristopherHButler** [comment]
Ok, thanks.
