### ISSUE TITLE
Property `line` does not update `Editor`

### ISSUE THREAD

**Issue by Ardeshir81** [suren-atoyan/monaco-react#185]
**Describe the bug**
Property `line` does not update the `Editor` scroll.

**To Reproduce**
https://codesandbox.io/s/sparkling-butterfly-3gnpd?file=/src/App.js

1. Make the data flow.
2. Assign property `line` so always `Editor` should autoScroll on lastLine.
x. It does not work!

Or just see https://codesandbox.io/s/sparkling-butterfly-3gnpd?file=/src/App.js

**Expected behavior**
I expected an `autoScroll` functionality work without problem.

**Screenshots**

![monaco-react](https://user-images.githubusercontent.com/5755214/107959041-16ac7a80-6fb8-11eb-849b-78dd03f01b33.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20
 - Browser FireFOx
 - Version 85

**Additional context**
I am using `Editor` as a searchable output of a process, so data is added continuously, stream flow. I want this behavior as an `autoScroll` functionality.

Thanks! This binding to react is amainzg :+1:

**Comment by Ardeshir81** [comment]
I'm taking a look at it. 

Seems like property `line` is treated as pixels being passed to `setScrollPosition`'s `scrollTop` property.

**Comment by suren-atoyan** [comment]
Hello @Ardeshir81 

Hmmm, quite strange, yes, you are right `line` is treated as pixels, but I remember we used it before. Whatever, for you particular case just do `line={data.length * LINE_HEIGHT}` instead of line={data.length}` (`const LINE_HEIGHT = 18`).

I'll fix it in the next version

**Comment by suren-atoyan** [comment]
Ah, I've just seen the `PR`. Thank you, I'll do some tests and will publish a new version.

Thank you for your support!
