### ISSUE TITLE
Snowpack and electron support

### ISSUE THREAD

**Issue by MrGreenTea** [suren-atoyan/monaco-react#187]
Thank your for these easy to use bindings.

Currently we are evaluating switching from `webpack` to `snowpack` and the major blocker currently Is getting `monaco-editor` to work correctly. I've had success with using this module, but we can't always rely on users being able to download `monaco-editor` from the CDN. 
Because of that I am trying to include the `monaco-editor` sources in some way and got it mostly working on development builds with a simple mount in `snowpack.config.js`
```js
module.exports = {
  mount: {
    'node_modules/monaco-editor/': {static: true, resolve:false, url: '/monaco-editor'},
  },
  ...
}
```
and then using `loader` like this in our root component:
```js
loader.config(
    {
       paths: {
         vs: "/monaco-editor/min/vs"
       }
     }
 )
```

This works fine but shows some errors in the console because it can't find the `min-maps`.

I can't get it to work with a production build, which is based on [this configuration](https://github.com/karolis-sh/electron-snowpack/tree/main/examples/react-typescript).
I have tried using the ESM examples shown in [this monaco-editor issue](https://github.com/microsoft/monaco-editor/issues/2227) but could not get it to work either.
Do you have any idea what might be needed? Any help would be greatly appreciated.

**Comment by suren-atoyan** [comment]
Hello @MrGreenTea 

> I can't get it to work with a production build, which is based on this configuration.

What error does it exactly show?

<hr />

BTW; did you check [those notes](https://github.com/suren-atoyan/monaco-react#for-electron-users) for `electron` users?

**Comment by MrGreenTea** [comment]
I get this error: 
![image](https://user-images.githubusercontent.com/9407731/108187933-48842500-710f-11eb-8e36-e6ef4660004c.png) which I don't get when running `yarn run dev`

I've checked those notes but they did not help me (yet).

I have this minimal example that reproduces it:

**Comment by martonlanga** [comment]
I could manage to make it work both in dev & production by mounting it like:
```ts
    '../external/monaco-editor/min/vs': { // downloaded & unzipped from monaco-editor website
      url: '/monaco-editor',
      static: true,
      resolve: false,
    },
```
and defining the path like:
```ts
loader.config({ paths: { vs: 'monaco-editor' } })
```

The source-maps still don't work like this, so I just disabled source map warnings in the electron instance.

But importing the built-in languages (html, json, ...) fails. It tries to import them from `/vs/language` and not `/monaco-editor/language`. Is there a way to define the paths for the languages @suren-atoyan?

**Comment by MrGreenTea** [comment]
@martonlanga Can you please share your production config? Do you build with `electron-builder`?

**Comment by martonlanga** [comment]
Yeah I'm using electron-builder. The config is just this: https://github.com/termyapp/Termy/blob/main/electron/package.json#L19-L33

> And how did you disable source map warnings?

In the dev-tools click on the gear icon and uncheck source-maps.

**Comment by suren-atoyan** [comment]
you also can try [this](https://github.com/suren-atoyan/monaco-react#use-monaco-editor-as-an-npm-package) approach
