### ISSUE TITLE
Failed to cancel using DiffEditor Mini Map

### ISSUE THREAD

**Issue by ningshunqiang** [suren-atoyan/monaco-react#189]
Failed to cancel using DiffEditor Mini Map

**Comment by suren-atoyan** [comment]
Hello @ningshunqiang 

Diff editor hasn't minimap, what you see on the right side of the editor is "diff overview ruler".

I also didn't know about it, I've just found [this](https://github.com/microsoft/monaco-editor/issues/598) discussion.
