### ISSUE TITLE
Console errors if editor is quickly removed

### ISSUE THREAD

**Issue by Andrew-web-coder** [suren-atoyan/monaco-react#190]
**Describe the bug**

I have a project where content is inside the tabs and editor is located inside one of them. Besides this, editor has multiple tabs, too (each tab toggles different content with different language). The issue is that, when user clicks tabs quickly enough, there are some error messages in the console output:

`TypeError: Cannot read property 'getModeId' of null at cssMode.js:7`

and

`TypeError: Cannot read property 'languageId' of null at a (cssWorker.js:7)`

**Additional context**

I found this pull request - https://github.com/microsoft/monaco-css/pull/10 - where one of this issues seems to be fixed.

**Comment by suren-atoyan** [comment]
Hello @Andrew-web-coder 

Could you please share the code segment where you use the `Editor` component? Which version of the library do you use? Do you use newly introduced [multi-model editor](https://github.com/suren-atoyan/monaco-react#multi-model-editor)?

**Comment by Andrew-web-coder** [comment]
To be honest, "multi-model editor" was a nightmare to implement in real world application. First, there are no demo of how to actually use it - how to, for example, retrieve data before saving. Data do not get updated on any change, as I expected. I somehow managed to overcome that by manually retrieving reference to monaco editor and looping through models, but ... uhh, what a nightmare, the data started to either mysteriously disappear or, quite the opposite, to appear out of nowhere. Then I ditched multi-model and managed to simply display stateful data that changes according to selected tab. Everything works fine now, except those error messages. I am using the latest version. I will try to create a demo that would produce these error messages.

**Comment by Andrew-web-coder** [comment]
OK, here is a demo demonstrating these issues - https://codesandbox.io/s/multi-model-editor-forked-9ul63?file=/src/App.js

As I said, try clicking all buttons and the error message will pop out in the console.

This is how I implemented multi-tab editor after failing to implement "multi-model editor" (see https://github.com/suren-atoyan/monaco-react/issues/194)

**Comment by Andrew-web-coder** [comment]
I guess one of the reasons is that this package loads monaco-editor@0.21.2 but the latest is 0.22.3

**Comment by AceLeeWinnie** [comment]
Hi, @Andrew-web-coder 
 Have you solve this problem? I also encounter the problem. And I can't use multi-editor in v4 cause some reason.

**Comment by suren-atoyan** [comment]
Hi @AceLeeWinnie 

What's the problem with multi-editor editor?
