### ISSUE TITLE
[Questions] How do you define a theme?

### ISSUE THREAD

**Issue by davidicus** [suren-atoyan/monaco-react#191]
How do you define a theme that you can pass to the monoco editor? Are there examples on how to do this?

**Comment by Andrew-web-coder** [comment]
I have the same question, I tried, but could not make it work (I would like to have a `github` theme).

**Comment by suren-atoyan** [comment]
Hello @davidicus @Andrew-web-coder 

[Here](https://codesandbox.io/s/monaco-theme-oijvt?file=/src/App.js) is the easiest way to do that.
