### ISSUE TITLE
Call `setDiagnosticsOptions` makes it stop validate json.

### ISSUE THREAD

**Issue by heroboy** [suren-atoyan/monaco-react#193]
**Describe the bug**
If I run this code:
```javascript
loader.init().then((monaco) => {
  monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
    enableSchemaRequest: true
  });
});
```
The editor will not show the red indicator for invalid json text.
**To Reproduce**

1. Go to https://codesandbox.io/s/onvalidate-forked-s48eb
2. You will see there's no red underline in the `b`
3. comment the `setDiagnosticsOptions` call, refresh.
4. You will see there's red underline in the `b`

**Expected behavior**
...

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome firefox
 - Version 4.0.7

**Additional context**

**Comment by suren-atoyan** [comment]
Ah, I guess it's because of the version of `monaco`, `monaco-loader` uses `0.21.x` by default, but the latest one is `0.22.3`. So, configuring loader to use the latest one fixes the issue. Please, check [this](https://codesandbox.io/s/onvalidate-forked-r3xg2) out.

**Comment by heroboy** [comment]
So the default one may be not the best one. I should use the latest?

**Comment by suren-atoyan** [comment]
Currently, configure it to use the latest one like I've shown in the example. I'll make the latest one default in the next version.

**Comment by suren-atoyan** [comment]
Now, it uses the latest one by default
