### ISSUE TITLE
 Dynamic localization support

### ISSUE THREAD

**Issue by IvanSavoskin** [suren-atoyan/monaco-react#198]
There is a need for dynamic localization of the monaco editor when switching the language in the application. Is it possible in the principle to implement this with existing means?
Also wondering if it is possible to use local monaco editor localization files instead of downloading them from an external resource?

Using react 17.0.1 + typescript + webpack

**Comment by suren-atoyan** [comment]
Hello @IvanSavoskin, sorry for the late answer.

You can change the localization by using the `loader` utility:

```js
import { loader } from "@monaco-editor/react";

loader.config({ "vs/nls": { availableLanguages: { "*": "de" } } });
```

Unfortunately, it will work only one time when you load the sources of monaco. So, the only way to change it "dynamically" is to reload the page after switching to another language. Here is the [example](https://codesandbox.io/s/simple-usage-forked-4vqgu?file=/src/App.js)
