### ISSUE TITLE
We need add fontSize in props

### ISSUE THREAD

**Issue by HypnosNova** [suren-atoyan/monaco-react#199]
We can change the font size by using following code:

`
monaco.editor.create(document.getElementById("container"), {
    ...options,
    fontSize: 20
});
`

However, the monaco-react doesn't have the fontSize in props so developers can't change the font size.

**Comment by suren-atoyan** [comment]
```
<Editor
  ...
  options={{ fontSize: 20 }}
/>
```

[codesandbox](https://codesandbox.io/s/simple-usage-forked-vixp2?file=/src/App.js)
