### ISSUE TITLE
Not being able to use with Electron - repo included to reproduce

### ISSUE THREAD

**Issue by tiagorp** [suren-atoyan/monaco-react#203]
Whenever I try to use the monaco-react editor, the web page gets tuck in Loading... and I get two console errors:

![image](https://user-images.githubusercontent.com/14852789/110215650-d51a3b80-7ea2-11eb-8c1b-8dd811dd1e65.png)

I've created a repo with the boilerplate I've created.

1. Go to 'https://github.com/tiagorp/electron-react-ts-monaco'
2. Download it.
3. Install dependencies ('npm install')
4. Start the project ('npm start')

Running on Windows 10.

I've tried several tactics described in the other issues but nothing has solved my problem so far. It seems for some reason the CDN URL path gets appended to the project path.

Any help would be very much appreciated.

**Comment by suren-atoyan** [comment]
Hello, @tiagorp did you try to download sources not from CDN? from your local files for example

**Comment by suren-atoyan** [comment]
please check [this](https://github.com/suren-atoyan/monaco-react#for-electron-users)

**Comment by tiagorp** [comment]
Hi, @suren-atoyan . Thanks for the quick response.

I've configured my content security policy on my electron renderer to allow scripts from the CDN where monaco is located, otherwise I would get a CSP error, so I don't think that is the issue.

I've checked other issues you have here and tried to apply the techniques described but so far without much luck. There is still one option I'm going to try which is to pass an absolute URL to the monaco-react loader you developed. I will keep you posted.

Thanks,
Tiago

**Comment by tiagorp** [comment]
Ok. Now it is working.

Two things were necessary:

`    loader.config({
        paths: {
            vs: './node_modules/monaco-editor/min/vs',
        },
    })`

And then on the webpack renderer config file we need to point the server /node_modules location to our file location.

`    devServer: {
        contentBase: [path.resolve(__dirname, 'dist'), path.resolve(__dirname, 'node_modules')],
        contentBasePublicPath: ['/', '/node_modules'],`

I will update the repo with these changes.

Thanks!

**Comment by jmc420** [comment]
This works for me but if you are using webpack with the Microsoft MonacoWebpackPlugin, do you think it would be possible to load monaco from the bundle rather than from node_modules?

what would loader.config({ paths: { vs: './node_modules/monaco-editor/min/vs', }, }) look like in this situation?
