### ISSUE TITLE
Editor Rerender

### ISSUE THREAD

**Issue by anubra266** [suren-atoyan/monaco-react#207]
Whenever I have my state in the parent of My editor. i.e.
```js
//Parent.tsx
const [code, setCode] = useState(' ')

<EditorComponentAsChild setCode={setCode} />

```
Triggering a change to the state completely rerenders my editor.
![Peek 2021-03-16 21-16](https://user-images.githubusercontent.com/30869823/111374070-f77b3880-869c-11eb-8603-bf40baeeb953.gif)

**Comment by suren-atoyan** [comment]
Hi @anubra266, we have never had such kind of problem; could you please provide a reproducible snippet?

**Comment by anubra266** [comment]
Thanks for your reply. After deeper investigation, I found out that the package responsible for splitting the editor from the preview, is causing this. Kinda repainting the DOM. Trying to figure it out. 

Thanks for your time though.
