### ISSUE TITLE
Multiple errors reported by Sentry

### ISSUE THREAD

**Issue by vtanciks** [suren-atoyan/monaco-react#210]
I have the latest version of monaco-editor/react installed and it's working as expected when we test it.  But when it used in production, we get lots of handled and unhandled errors logged by Sentry: 

```
TypeError: Cannot read property 'parent' of undefined
    at bT (https://cdn.jsdelivr.net/npm/monaco-editor@0.22.3/min/vs/language/typescript/tsWorker.js:21:1520827)

RangeError: Maximum call stack size exceeded
    at u (https://cdn.jsdelivr.net/npm/monaco-editor@0.22.3/min/vs/language/typescript/tsWorker.js:21:770316)

Canceled canceled(npm/monaco-editor@0.21.2/min-maps/vs/editor/vs/editor/file:/Users/alex/src

TypeError: Cannot read property 'kind' of undefined
    at Object.e.isNewExpression (https://cdn.jsdelivr.net/npm/monaco-editor@0.21.2/min/vs/language/typescript/tsWorker.js:21:730631)
```

I don't have clear ways of reproducing those errors, but we get them reported every day.

OS: WIndows 10
Browser: Chrome 89
monaco-editor/react version: 4.0.10

**Comment by suren-atoyan** [comment]
Hi @vtanciks, thank you for the report. Is there any pattern regarding to the environment? Maybe the same browser version or operating system

**Comment by vtanciks** [comment]
Hey! Thanks for reply.

It happens that all reported users use Chrome, but the OS ranges from Windows 10 to the latest Mac OS. According to Sentry traces, all errors are mostly thrown when the suggestion widget is active and users are interacting with it. Also noticed that errors are mostly thrown by tsWorker.js

ui.click `section > div > div.monaco-editor.no-user-select.showUnused.showDeprecated.vs`
ui.click `div.editor-widget.suggest-widget > div.tree > div.monaco-list.list_id_2`
ui.click `div.invisible.scrollbar.horizontal > div.slider`
ui.click `div.app-root > div.app-content > div.page-content > div.test-form > div.content`
ui.click `div.lines-content.monaco-editor-background`
ui.click div.view-lines.monaco-mouse-cursor-text > div.view-line > span > span.mtk7`

```exception
Error: Cannot read property 'kind' of undefined

TypeError: Cannot read property 'kind' of undefined
    at Object.e.isNewExpression (https://cdn.jsdelivr.net/npm/monaco-editor@0.22.3/min/vs/language/typescript/tsWorker.js:21:753000)
    at https://cdn.jsde...```

**Comment by suren-atoyan** [comment]
@vtanciks this should be fixed in the latest version. I'm closing this, but feel free to re-open it if it still exists in your case.
