### ISSUE TITLE
disable default js suggestions

### ISSUE THREAD

**Issue by naivefun** [suren-atoyan/monaco-react#211]
is there a way to disable the predefined suggestions?

![image](https://user-images.githubusercontent.com/10683378/111935994-a5547000-8aff-11eb-8542-886c93e4c6ed.png)

**Comment by suren-atoyan** [comment]
Hello @naivefun 

There are a couple of options related to suggestions and hints. Check [this](https://codesandbox.io/s/suggestions-and-hints-xow56?file=/src/App.js), please.

```js
<Editor
  height="90vh"
  defaultLanguage="javascript"
  defaultValue={code}
  options={{
    quickSuggestions: {
      other: false,
      comments: false,
      strings: false
    },
    parameterHints: {
      enabled: false
    },
    ordBasedSuggestions: false,
    suggestOnTriggerCharacters: false,
    acceptSuggestionOnEnter: "off",
    tabCompletion: "off",
    wordBasedSuggestions: false
  }}
/>
```

To see the list of possible options please check [IStandaloneEditorConstructionOptions](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.istandaloneeditorconstructionoptions.html)

**Comment by naivefun** [comment]
@suren-atoyan  yah I have tried all the options but still not working. In your codepen example, if you try `ctrl + space` it still list the options.

![image](https://user-images.githubusercontent.com/10683378/114262789-7f423180-9a14-11eb-99ab-0afd7fd0401e.png)

**Comment by naivefun** [comment]
@suren-atoyan it turns out it's LSP problem:

https://stackoverflow.com/questions/41581570/how-to-remove-autocompletions-for-monaco-editor-using-javascript
