### ISSUE TITLE
Ability to configure a custom min-maps path

### ISSUE THREAD

**Issue by mikeyshing88** [suren-atoyan/monaco-react#212]
Not quite sure if this should be raised as a bug or a feature but currently I am loading the editor files from node modules based on the discussion in https://github.com/suren-atoyan/monaco-react/issues/12.  That being said, it is working like a treat with the main editor files - my `publicPath` is set to `/assets/` so the below works fine:

```tsx
loader.config({
  paths: {
    vs: '/assets/vs',
  },
})
```

However, it appears that there is no way of editing the `min-maps` path which results in this error message (seems to be ignoring the `assets` path):

```
DevTools failed to load SourceMap: Could not load content for http://localhost:3000/min-maps/vs/loader.js.map:
HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

Is there perhaps a way to do this that I am unaware of?

**Comment by marekhanzlik** [comment]
Did you found the solution?

**Comment by vladtimss** [comment]
@MYKEU help me please resolve same problem
