### ISSUE TITLE
Disable minimap for React Monaco 

### ISSUE THREAD

**Issue by Jacqueline-ms** [suren-atoyan/monaco-react#213]
Hello! I see there is a disable minimap feature on the [MS Monaco Editor github](https://github.com/microsoft/monaco-editor/issues/598), but I am not sure I see one for your Monaco-React. 

I would love to disable the minimap here through the <Editor/> props. 
![image](https://user-images.githubusercontent.com/30805892/112246803-75e15880-8c10-11eb-8eed-4e3d5eb26dbd.png)

I successfuly display:none'd the .minimap class as a work around for now. 

Thanks!

**Comment by mikeyshing88** [comment]
```jsx
<Editor
  ...
  options={{
    minimap: {
      enabled: false,
    },
  }}
/>

**Comment by Jacqueline-ms** [comment]
Thank you!
