### ISSUE TITLE
updating `monaco-editor`

### ISSUE THREAD

**Issue by aghArdeshir** [suren-atoyan/monaco-react#216]
I try to always keep dependencies up to date in my project. But I can't update `moncao-editor` (from `0.21.3` to `0.23.0`) because it is specified as a peer dependency in `@monaco-editor/react` library I think. The reason this is an issue instead of PR is because I can't get my head around all `peerDependencies` and breaking changes in projects with `0.x.x` version.

![Screenshot from 2021-04-07 09-17-53](https://user-images.githubusercontent.com/5755214/113813458-3163ca00-9785-11eb-95d1-2079b9b41f4f.png)
(Excuse me for the blue marks)

Thanks!

**Comment by suren-atoyan** [comment]
Hello @aghArdeshir 🙂 

I'll publish a new version this week with updated peer-dependency

**Comment by ivan-prodanov** [comment]
@suren-atoyan yeah, would be great to update to latest. Lots of great upgrades in the newer versions.

**Comment by suren-atoyan** [comment]
Hi everyone

Guys, sorry for such a late answer. Please, check the new version - [v4.1.2](https://github.com/suren-atoyan/monaco-react/releases/tag/v4.1.2); the peer dependency `monaco-editor` is updated to the latest version (`0.23.0`)

**Comment by kambydyne** [comment]
Hi, I'm having this issue again with 4.1.3 (looking for 0.23.0, but getting 0.24.0). Could you bump the peer dependency please? (Wouldn't removing the ^ hat from the peer dependency give you the exact version you need?)

Anyway thanks for all your work!
