### ISSUE TITLE
Editor file loading gets hung, unable to display file content, due to loading config from CDN https://cdn.jsdelivr.net

### ISSUE THREAD

**Issue by rajiff** [suren-atoyan/monaco-react#217]
**Describe the bug**
Editor loading gets hung, as a result fails to display the content of the file on the UI

Issue seems to be in Deploying and running from secure environment, due to loading monaco-editor config from a CDN

Exact Error is 
`Refused to load the script 'https://cdn.jsdelivr.net/npm/monaco-editor@0.21.2/min/vs/loader.js' because it violates the following Content Security Policy`

Below is the screenshot

![image](https://user-images.githubusercontent.com/1080415/114011654-1d05f700-9883-11eb-974d-b8dd05e84115.png)

**To Reproduce**
Happens when u deploy the code in a prod like environment and URL is running as HTTPS 

```
import React from "react";
import ReactDOM from "react-dom";
import Editor, { loader } from "@monaco-editor/react";
import { loader } from '@monaco-editor/react';
loader.config({ paths: { vs: 'path-to-your-node_modules/node_modules/monaco-editor/min/vs' } });

function App() {
  return (
   <Editor
     height="90vh"
     defaultLanguage="javascript"
     defaultValue="// some comment"
   />
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

**Expected behavior**
Editor should be able to load the file content
There has to be more neater and easier way to load the config file

**Screenshots**
Even though above is what is prescribed in another [issue](https://github.com/suren-atoyan/monaco-react/issues/168), it does not work and gives below syntax error in loading 

![image](https://user-images.githubusercontent.com/1080415/114013336-0c568080-9885-11eb-8ad9-4f9602c7f0f0.png)

**Desktop (please complete the following information):**
I tried this on Mac, Chrome & Edge browser, but can confirm happening on all OS and browser

**Additional context**
I had to solve using a very nasty workaround
- `npm install monaco-editor`
- Copied entire node_modules/monaco-editor to `public` folder
- Copied entire node_modules/monaco-editor to `src/` folder load the file by referring from "src" folder

Can we have a easier fix for this, as this way it is very difficult to Dockerise and Deploy, a lot of security related issues as we have to copy an external module to application's source code

Please provide some pointers or direction too fix this clean way

**Comment by zoonman** [comment]
It would make a lot of sense to load editor from an npm/yarn package without using any CDN.
I'd prefer to let react-scripts to perform all necessary bundling etc.

**Comment by vadimshvetsov** [comment]
The best option to avoid storing minified monaco-editor in VCS I've found is to copy it at postinstall script.
``` json
{
  "scripts":  {
    "postinstall": "cp -R ./node_modules/monaco-editor/min/vs ./public/monaco-editor"
  },
}
```
And add this public path to .gitignore. 

Anyway this is looks like a workaround. 
The reason why we can't add it from npm right now is some css and ttf files there which should be processed with our bundler.

**Comment by ColmanHumphrey** [comment]
I'm not sure I'm 100% following, but mostly trying to solve basically the same issue. I'm using NextJS if that helps.

The solution to copy to public works. Are there any downsides to this? Ideally I guess the bundling with nextjs would take care of all this and we could just point the config in the right direction.

For types, I have `import * as monaco from "monaco-editor/esm/vs/editor/editor.api"` in one of my files, is there a way to do something along these same lines?

**Comment by suren-atoyan** [comment]
> It would make a lot of sense to load editor from an npm/yarn package without using any CDN.
> I'd prefer to let react-scripts to perform all necessary bundling etc.

@rajiff @zoonman @vadimshvetsov @ColmanHumphrey we did this intentionally, to avoid using additional webpack plugins. `react-scripts` is not able to bundle monaco editor sources without an additional webpack plugin. Which means you have to eject or rewire your CRA application.

The whole idea of this library is to make monaco editor work without using any webpack plugins (which is required in applications generated by CRA). The workaround we've used here is not ideal, sure, it would be great to have consistency across the maintenance of packages, but unfortunately, this was the best workaround we could find to solve the problem.

> I had to solve using a very nasty workaround

By using `loader` utility you can configure the library to load monaco sources from wherever you want. If you want to load it from your local files + you have only access to `/public` folder due to your setup/web-server configuration, it means that your mentioned "very nasty workaround" is the only way.

**Comment by keymandll** [comment]
I was so happy to see someone having created this library. Just what I needed - until I've noticed it was loading content remotely. I can foresee this being a problem for more people, like us, primarily for security reasons. We are not allowed to load any code from untrusted remote sources.
The proposed workaround is quite problematic as well. We have SCA (software composition analysis) running on our codebase and if we just put JS files under `/public` those will definitely be not picked up as they won't show up in the BOM. Probably we could hack something in into our pipeline that patches the generated BOM file, but then it's just hack on top of hack, and so on - which is not an option.

**Comment by creazy231** [comment]
same problem here
```
Refused to load the script 'https://cdn.jsdelivr.net/npm/monaco-editor@0.28.1/min/vs/loader.js' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

**Comment by suren-atoyan** [comment]
now, [this](https://github.com/suren-atoyan/monaco-react#use-monaco-editor-as-an-npm-package) is also available

**Comment by vishalsatam** [comment]
I'm so confused by this...
If I check the path
`https://cdn.jsdelivr.net/npm/monaco-editor@0.33.0/min/vs/editor/`

The `editor.main.js` file shows up as `2.78 MB`. 🐙 

But if I download it directly from jsdelivr using this path... The Network tab shows that the file is only `731 KB`  💯 
`https://cdn.jsdelivr.net/npm/monaco-editor@0.33.0/min/vs/editor/editor.main.js` 

WHAT SORCERY IS THIS??

Can someone please explain what is going on here?

**Comment by vishalsatam** [comment]
I just found out that jsdelivr is sending a compressed file over the wire
https://github.com/Microsoft/monaco-editor/issues/463#issuecomment-1422032797

I also confirmed it by running `gz -k editor.main.js` 

This brings me to an interesting thought. Is it possible for us to create your own CDN and transmit a `.gz` file? would that work? Like can the loader smartly fetch the `.js.gz` file instead of the `.js.gz` file?

**Comment by rajiff** [comment]
> I just found out that jsdelivr is sending a compressed file over the wire [microsoft/monaco-editor#463 (comment)](https://github.com/microsoft/monaco-editor/issues/463#issuecomment-1422032797)
> 
> I also confirmed it by running `gz -k editor.main.js`
> 
> This brings me to an interesting thought. Is it possible for us to create your own CDN and transmit a `.gz` file? would that work? Like can the loader smartly fetch the `.js.gz` file instead of the `.js.gz` file?
> 
> Its a good thought, but I guess another option could be to use a CDN that already supports gzip compressing your files automatically like AWS Cloudfront for example. https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html

You can also apply compression to your static filer server or the backend service

**Comment by xmsz** [comment]
any update?

**Comment by hmy529** [comment]
I also want to know how to solve it

**Comment by zhalice2011** [comment]
same problem

**Comment by SMKH-PRO** [comment]
Was facing the same issue on CRA based project. 

adding following meta tag resolved the issue for me 
```
 <meta http-equiv="Content-Security-Policy" content="default-src 'self' https://cdnjs.cloudflare.com https://fonts.googleapis.com; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com https://fonts.googleapis.com; script-src 'self' https://cdn.jsdelivr.net; font-src 'self' https://cdnjs.cloudflare.com https://fonts.googleapis.com; worker-src 'self' blob:">

```

**Comment by chanvmw** [comment]
Any Resolution?
Facing same issues with Netflix workbench workflow page. 
Issues observed :
- Nat'ed environment cdn.jsdelivr.net site is pingable but editor only not loading https://cdn.jsdelivr.net/npm/monaco-editor@0.43.0/min/vs/loader.js
