### ISSUE TITLE
How to use colorizeElement

### ISSUE THREAD

**Issue by nsisodiya** [suren-atoyan/monaco-react#218]
How to use colorizeElement
Example - https://microsoft.github.io/monaco-editor/playground.html#creating-the-editor-syntax-highlighting-for-html-elements

```js
// The colorizeElement-function will read the data-lang-attribute
// from the element to select the correct language mode. In this
// sample it is text/css.
monaco.editor.colorizeElement(document.getElementById('code'));
```

**Comment by suren-atoyan** [comment]
There are many ways to do that; first of all, you need to access the [monaco instance](https://github.com/suren-atoyan/monaco-react#monaco-instance)

[here is an example](https://codesandbox.io/s/colorize-yh3d5?file=/src/App.js)
