### ISSUE TITLE
 How to realize automatic completion?

### ISSUE THREAD

**Issue by baobao12356** [suren-atoyan/monaco-react#220]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Just like using vscode, is there an automatic completion function when writing code? What parameters can this component pass to achieve automatic completion? Similarly, we can pass in the sorted syntax package or automatically have a default, which can be passed in during configuration to achieve automatic completion

**Comment by suren-atoyan** [comment]
Hello @baobao12356 

There is an automatic completion by default. Here how it looks:

https://user-images.githubusercontent.com/13118722/114147948-4af24680-992a-11eb-9204-cbefc26f69e4.mov

And here is a [codesandbox](https://codesandbox.io/s/simple-usage-uyf5n?file=/src/App.js)

If you need some customization for completion check the official [API](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.completionitemprovider.html#providecompletionitems) of the `monaco-editor`.
