### ISSUE TITLE
如何实现自定义代码补全提示？

### ISSUE THREAD

**Issue by baobao12356** [suren-atoyan/monaco-react#222]
如何实现自定义代码补全提示？比如整理语法包，传入实现补全提示

How to implement custom code completion prompt? For example, organize the syntax package and pass in the completion prompt

**Comment by suren-atoyan** [comment]
you can use [provideCompletionItems](https://microsoft.github.io/monaco-editor/docs.html#interfaces/languages.CompletionItemProvider.html#provideCompletionItems)
