### ISSUE TITLE
How to resolve import statements locally?

### ISSUE THREAD

**Issue by Xyloboard** [suren-atoyan/monaco-react#226]
Answered my own quesion - using the multi-model editor. I guess separately I need to use the ts-transpiler and set the options in that (which isn't part of this project sorry!

![image](https://user-images.githubusercontent.com/40793144/114423566-35418300-9baf-11eb-9797-290d0aedd46b.png)

First of all - thanks so much for your work. It's ace.

I'm attempting to make a fully featured editor work entirely within the browser. I have a selection of code files held in memory as strings e.g.
{
  "index.ts": '...',
  "./someFile.ts": '...'
}

When it comes to import statements, Monaco naturally tries to resolve them. However, there is nothing in the network tab that I can intercept to pass my locally held module code back to Monaco so it throws an error... 

**Cannot find module './someFile'. Did you mean to set 'moduleResolution' or add aliases to the 'paths' option?**

How does the import resolution work in the browser? and is there a way I can override this behaviour to either make it resolve via http requests which I can intercept and deal with, or via code directly so that I can pass back the strings I have for the code files? I assume it tries to use the file system for this and fails as it's in a browser...

Any help would be great!

**Comment by Xyloboard** [comment]
Answered my own quesion - using the multi-model editor. I guess separately I need to use the ts-transpiler and set the options in that (which isn't part of this project sorry!

**Comment by puranjayjain** [comment]
@Xyloboard do you have an example for this?
