### ISSUE TITLE
Unable to preserve current model of modified DiffEditor

### ISSUE THREAD

**Issue by dehoward** [suren-atoyan/monaco-react#227]
**Describe the bug**
![image](https://user-images.githubusercontent.com/52973358/114912456-de1cf780-9dd4-11eb-855c-9b74e094d0cc.png)
We have a use-case, similar to Azure DevOps above, where we allow the user to flip between the normal Editor and the DiffEditor. 

This mostly works great except that when switching _from_ the DiffEditor _to_ the Editor, we are unable to use the DiffEditor's modified model as the model of the Editor. In the flip scenario, switching from the Editor to the DiffEditor, we can do this because of the `keepCurrentModel` prop allowed on the Editor, but it seems that the DiffEditor is lacking this ability.

We could benefit from one of two things:
1. Advice/Examples on how to implement this pattern. 
2. A `keepCurrentModifiedModel` prop (or something similar) for the DiffEditor that allows the consumer to prevent the modified model from being disposed on unmount.

**To Reproduce**
Our setup is similar to below. We keep a ref for the current model and set that ref in the `onMount` function of each editor.
```tsx
const isDiff = React.useState(false);
const model = React.useRef<monaco.editor.ITextModel>();
return {isDiff ? 
   <DiffEditor
      onMount={diffEditor => 
         model.current && diffEditor.setModel({ original: diffEditor.getModel().original, modified: model.current });
         model.current = diffEditor.getModel().modified;
   /> : 
   <Editor 
       keepCurrentModel
       onMount={editor => 
       // model.current && editor.setModel(model.current); <--- ERROR because at this point the DiffEditor's model is disposed!
        model.current = editor.getModel();
  />;
```

**Comment by suren-atoyan** [comment]
Hello @dehoward 

Thank you for opening this issue.

I see, actually, the multi-model editor and related parts are not fully supported by the `DiffEditor`, for now. But we can gradually implement it. So, I'll think about implementing `keepCurrentModifiedModel` (`keepCurrentOriginalModel`?) and let you know here.

**Comment by dehoward** [comment]
Awesome, thanks for the prompt response on this.

I'm wondering if the pattern I shared above is the best way to implement our desired outcome, or if there's a better way...

Originally, I expected that having the same value for `path` and `modifiedModelPath` in the `Editor` and `DiffEditor` respectively would produce what we want, but after looking at how `setModels` in the `DiffEditor` works, I see why this isn't the case.

So instead of having the consumer have to worry about setting both `keepCurrentModel` and `keepCurrentModifiedModel`, and then calling `setModel()` to keep the 2 editors in sync. 
I think a better approach may just be to have your internal `setModels` in `DiffEditor` be based on the `getOrCreateModel` function, rather than just `createModel`. This way, you can keep the models in sync internally, without consumers having to setup a `Ref` to do so

**Comment by suren-atoyan** [comment]
Hey @dehoward 

The `keepCurrentModifiedModel` is here. Check please the latest version - `v4.1.2`

[Here](https://codesandbox.io/s/keepcurrentmodifiedmodel-o6sk0?file=/src/App.js) is a working snippet with your example.

**Comment by dehoward** [comment]
Wow, that was fast. Thanks a lot!

One thing though, in the Sandbox you linked, `DiffEditorProps` doesn't have this prop? Am I missing something here?

**Comment by dehoward** [comment]
https://github.com/suren-atoyan/monaco-react/pull/235

**Comment by suren-atoyan** [comment]
@dehoward done

check the version - `v4.1.3`

Thank you for your support!
