### ISSUE TITLE
Example using electron-forge?

### ISSUE THREAD

**Issue by theogravity** [suren-atoyan/monaco-react#229]
I'm having issues trying to get this component to properly load under an electron forge (electron v12) project.

My project was created with:

`npx create-electron-app my-new-app --template=typescript-webpack`

I'm currently doing the following:

```
import Editor, { loader } from '@monaco-editor/react';
import monaco from 'monaco-editor';

loader.config({
  paths: {
    vs: Window.monacoPath,
  },
});

```

In my preload, i have the following:

```
import path from 'path';

function ensureFirstBackSlash(str) {
    return str.length > 0 && str.charAt(0) !== '/' ? `/${str}` : str;
}

function uriFromPath(_path) {
    const pathName = path.resolve(_path).replace(/\\/g, '/');
    return encodeURI(`file://${ensureFirstBackSlash(pathName)}`);
}

// @ts-ignore
Window.monacoPath = uriFromPath(
    path.join(__dirname, '../../node_modules/monaco-editor/min/vs')
);
```

But I will get in the renderer console:

```
index.js:70 Not allowed to load local resource: file:///Users/theo/projects/merman/.webpack/node_modules/monaco-editor/min/vs/loader.js
```

Even if I allowed `file:///`, the `.webpack` path does not contain `node_modules` at all.

If anyone knows how to make this work in electron forge, would love to know! It feels like it might be a webpack config thing to me.

**Comment by suren-atoyan** [comment]
Hello @theogravity 

I am not familiar with the setup you've mentioned, but you should setup your `webpacak` to be able to load it. In your particular case try `cp -R node_modules/monaco-edditor ./.webpack`. It will solve the import issue, but it wouldn't be considered as a long-term solution. (and remove `import monaco from 'monaco-editor'` line)

**Comment by pongstr** [comment]
> But I will get in the renderer console:
> ```
> index.js:70 Not allowed to load local resource: file:///Users/theo/projects/merman/.webpack/node_modules/monaco-editor/min/vs/loader.js
> ```
> Even if I allowed file:///, the .webpack path does not contain node_modules at all.
>
> If anyone knows how to make this work in electron forge, would love to know! It feels like it might be a webpack config thing to me.

`electron-forge` doesn't copy the `vs` files from `node_modules` even if you reference it,  a manual copy of the files to a static directory can solve this issue. like so:

```javascript
// package.json
{
 ...,
  "scripts": {
    ...
    "postinstall": "cp -R ./node_modules/monaco-editor/min/vs ./app/public"
  }
}
```

**Comment by suren-atoyan** [comment]
Above mentioned option works. Also, you can try [this](https://github.com/suren-atoyan/monaco-react#use-monaco-editor-as-an-npm-package) approach
