### ISSUE TITLE
TypeError: (0 , _stateLocal.create) is not a function

### ISSUE THREAD

**Issue by darda-ergo** [suren-atoyan/monaco-react#231]
![Screen Shot 2021-04-19 at 10 32 39 AM](https://user-images.githubusercontent.com/61325474/115423236-783ece80-a21f-11eb-9f09-e8afe16ada9c.png)

I am using react with typescript 

this is my code : 
import MonacoEditor from "@monaco-editor/react";

function CodeEditor() {
  return <MonacoEditor height="90vh" />;
}

export default CodeEditor;

**Comment by suren-atoyan** [comment]
Hello @darda-ergo 

which version you use?

**Comment by darda-ergo** [comment]
Version 3.7.4 but it seems the problems remains if i switched to latest
versions.

**Comment by UnkleTayo** [comment]
I am also getting this error on 3.7.4 I also tried using the latest version it still persists

**Comment by suren-atoyan** [comment]
@darda-ergo @UnkleTayo to be sure - the latest is `v4.1.2`, do you use that one? It seems you still use version 3 (v3.x.x), but with some features from version 4. I've just checked it one more time, everything works as expected. Could you please give me more information about your environment?

**Comment by darda-ergo** [comment]
Yeah with version 4.1.2. Its works fine . Thank you so much

**Comment by UnkleTayo** [comment]
Version 4.1.2 works fine too, thanks
