### ISSUE TITLE
Stuck at loading + Cannot read property 'env' of undefined

### ISSUE THREAD

**Issue by XC-** [suren-atoyan/monaco-react#236]
Hi,

I've been scratching my head for a while now and simply cannot figure out what is going wrong. I am using the component inside a webview in VS Code and for testing purposes permitted it to fetch the source from CDN. All is fine and dandy till that. But then I get stuck at watching the loading screen. In the dev tools console, there is a single error, stating that `Cannot read property 'env' of undefined`. When looking into it more carefully with the webview dev tools, it shows me the following:
![image](https://user-images.githubusercontent.com/7238703/116482296-934bb700-a88d-11eb-8554-12506140ff47.png)

which refers to:

![image](https://user-images.githubusercontent.com/7238703/116482353-afe7ef00-a88d-11eb-86b7-76b84b39269c.png)

I am using esbuild for both buildint the react application and the extension using config: 
`async function build() {
    let entryPoints = await glob("./ext-src/*.ts");
    return esbuild.build({
        entryPoints: ['src/index.jsx'],
        outfile: 'build/static/js/index.js',
        loader: {'.js': 'jsx', ".svg": "dataurl", ".png": "dataurl", ".ttf": "dataurl"},
        bundle: true,
        sourcemap: true,
        watch: true,
        format: "cjs",
        platform: "browser",
        target: "es2019",

    }).then(() => {
        return esbuild.build({
            entryPoints: entryPoints,
            outdir: 'build/ext-src',
            watch: true,
            platform: "node",
            target: "es2019",
            format: "cjs",
            sourcemap: true,
            bundle: true,
            external: ["vscode"]
        })
    })
};
`

The same happens when trying to use the source from locally installed npm package.

What am I doing wrong?

**Comment by suren-atoyan** [comment]
can you please share the code segment of the component usage?

**Comment by XC-** [comment]
Certainly. The only instance of monaco-react usage is:

`
<AccordionDetails>
                <Editor
                    theme="vs-dark"
                    height="500px"
                    width="100%"
                    defaultLanguage="yaml"
                    defaultValue={contentAsString}
                />
</AccordionDetails>
`

I tested loading from local files with `loader.config({ paths: { vs: window.monaco_loader_config } })` and though the loading seemed to be working, the result was the same, failing at the same place and same way.

**Comment by XC-** [comment]
So in the usage of the editor component there is nothing wrong and it seems that the problem is with bundling. I decided to do yet another bundling experiment and this time used webpack with babel and took basis for the webpack configuration from here https://github.com/microsoft/monaco-editor-samples/tree/main/browser-esm-webpack-monaco-plugin and added necessary react and babel stuff on top of it. And it worked. I just wonder why.

Maybe I move this question to esbuild issues?

**Comment by suren-atoyan** [comment]
you shouldn't use any `webpack` configuration file or do any builder-specific things; the idea of this library to avoid such kinds of setup. Could you please create a minimal reproducible repo - I want to try it. Plus the [playground](https://github.com/suren-atoyan/monaco-react/tree/master/playground) application uses `esbuild`, so, we've never seen problems with `esbuild`

**Comment by XC-** [comment]
Huh, well then this is even more curious and I admit I'm fascinated by the issue in that case. I'll see if I can reproduce is with as minimal project as possible.

**Comment by softmarshmallow** [comment]
Having similar on nextjs

```
decorators.ts:12 Uncaught TypeError: Cannot read property 'value' of undefined
    at C (decorators.ts:12)
    at M (decorators.ts:60)
    at eval (index.js?b7ab:36)
    at Array.forEach (<anonymous>)
    at decorateConstructor (index.js?b7ab:35)
    at Reflect.decorate (index.js?b7ab:10)
    at Me (globalMouseMoveMonitor.ts:41)
    at touch.ts:124
    at Function.r._invokeFactory (loader.js:1118)
    at r.complete (loader.js:1128)
    at r._onModuleComplete (loader.js:1754)
    at r._resolve (loader.js:1714)
    at r.defineModule (loader.js:1357)
    at _ (loader.js:1804)
    at globalMouseMoveMonitor.ts:41
    at fake:1
```

**Comment by XC-** [comment]
As an update. I've been quite busy for the past two weeks and haven't  had yet time for this. Hopefully soon I'll get the reproduction done.

**Comment by XC-** [comment]
Well, after trying to reproduce the issue, I can't. Even the actual project now seems to be working with esbuild and I even made sure that it is building with esbuild. Nothing has changed in the build system or in the project, but now it works for some reason. :thinking:

**Comment by suren-atoyan** [comment]
So, let's close it, if you face it again, feel free to re-open the issue
