### ISSUE TITLE
Expose other events

### ISSUE THREAD

**Issue by dustinlacewell** [suren-atoyan/monaco-react#240]
Please expose new events like `onDidChangeCursorPosition`, `onDidChangeCursorSelection`, etc

**Comment by suren-atoyan** [comment]
@dustinlacewell you always have access those events. [Here](https://codesandbox.io/s/ondidchangecursorposition-qv36i?file=/src/App.js) is an example. Check the [editor-instance](https://github.com/suren-atoyan/monaco-react#editor-instance).

**Comment by dustinlacewell** [comment]
Thanks :)
