### ISSUE TITLE
onChange function not called if value changes back to original value

### ISSUE THREAD

**Issue by Seanmclem** [suren-atoyan/monaco-react#241]
Description
the Editor `onChange` prop function is called every time the value in the editor changes. Like when typing. Unless that typing leads back to the original value, from the `value` prop, from when the Editor was first loaded

```typescript 
//...
  const handleEditorChange = (value: string | undefined, event: monaco.editor.IModelContentChangedEvent) => {
    console.log('Text change')
  }
//...
  return  ( 
    <Editor
      height="100%"
      value={text}
      onMount={handleEditorDidMount}
      onChange={handleEditorChange}
    />
  )
//...
```

**Expected behavior**
onChange should always be called. A change back to the original value  is still a change

`"@monaco-editor/react": "^4.1.3",`
`"monaco-editor": "^0.23.0",`

I understand the onChange prop is probably not called because, since the value is changed back to the original, then there "are no changes" anymore.
However, I need a way to know if the value has both, been changed, and been changed back to original. With no function running for the latter -how can I tell?

**Comment by suren-atoyan** [comment]
Hello @Seanmclem 

It should be fixed, but for now either replace `value` with `defaultValue` or handle `on change` manually; [check this](https://codesandbox.io/s/issue-241-26ior?file=/src/App.js)

**Comment by Seanmclem** [comment]
> Hello @Seanmclem
> 
> It should be fixed, but for now either replace `value` with `defaultValue` or handle `on change` manually; [check this](https://codesandbox.io/s/issue-241-26ior?file=/src/App.js)

switching to defaultValue worked for now. Thanks!

**Comment by rajiff** [comment]
The workaround is working, but it would be highly appreciated if this can be fixed

**Comment by obadakhalili** [comment]
> Hello @Seanmclem
> 
> It should be fixed, but for now either replace `value` with `defaultValue` or handle `on change` manually; [check this](https://codesandbox.io/s/issue-241-26ior?file=/src/App.js)

This won't work for me because the `onChange` event handler changes according to a stateful value in my component, so the event handler cannot be assigned only when the component is mounted, because it may change countlessly after that

**Comment by Seanmclem** [comment]
> > Hello @Seanmclem
> > 
> > It should be fixed, but for now either replace `value` with `defaultValue` or handle `on change` manually; [check this](https://codesandbox.io/s/issue-241-26ior?file=/src/App.js)
> 
> This won't work for me because the `onChange` event handler changes according to a stateful value in my component, so the event handler cannot be assigned only when the component is mounted, because it may change countlessly after that.
> 
> And I cannot re-assign the event handler on those stateful values change in an effect, because I need a reference to the editor instance, and when the effect hook runs, that reference isn't assigned yet. `useLayoutEffect` is not solving it either.

It worked for me, in the same scenario. I'll take a look at my code later and send you a more specific example

**Comment by obadakhalili** [comment]
> > > Hello @Seanmclem
> > > It should be fixed, but for now either replace `value` with `defaultValue` or handle `on change` manually; [check this](https://codesandbox.io/s/issue-241-26ior?file=/src/App.js)
> > 
> > 
> > This won't work for me because the `onChange` event handler changes according to a stateful value in my component, so the event handler cannot be assigned only when the component is mounted, because it may change countlessly after that.
> > And I cannot re-assign the event handler on those stateful values change in an effect, because I need a reference to the editor instance, and when the effect hook runs, that reference isn't assigned yet. `useLayoutEffect` is not solving it either.
> 
> It worked for me, in the same scenario. I'll take a look at my code later and send you a more specific example. I believe you can just use default value to set the initial value. And then still have on change run for your set value function

Thanks for replying so fast. Using the `defaultValue` prop isn't an option for me, because the value gets updated from 2 places:
- From updating the editor.
- Changing the active snippet (file).

**Comment by colramos-amd** [comment]
> >  Hello @Seanmclem
>  It should be fixed, but for now either replace value with defaultValue or handle on change manually; check this
> 
> switching to defaultValue worked for now. Thanks!

Could you share a complete snippet of the code you ended up using. Currently encountering a similar error #278 and think it could help! Thanks for the help

**Comment by colramos-amd** [comment]
> > Hello @Seanmclem
> > It should be fixed, but for now either replace `value` with `defaultValue` or handle `on change` manually; [check this](https://codesandbox.io/s/issue-241-26ior?file=/src/App.js)
> 
> switching to defaultValue worked for now. Thanks!

@Seanmclem Could you share a complete snippet of the code you ended up using. Currently encountering a similar error #278 and think it could help! Thanks for the help
