### ISSUE TITLE
How to add a node definitions for typescript?

### ISSUE THREAD

**Issue by byeze** [suren-atoyan/monaco-react#243]
Hello! I need to know how to add node type definitions to monaco editor, I tried following:
- https://stackoverflow.com/questions/52290727/adding-typescript-type-declarations-to-monaco-editor
- https://github.com/Microsoft/monaco-editor/issues/1415
- using dts-bundle-generator

But no success in any of my attempts to add @types/node definitions.

Would be very grateful if anyone can help me!
Thanks

**Comment by suren-atoyan** [comment]
Hi @byeze 

sorry for the late answer. I'll try to make a snippet for you

**Comment by byeze** [comment]
Thank you @suren-atoyan !

**Comment by suren-atoyan** [comment]
Hey, @byeze could you please check [this](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-javascript-defaults) example and [its implementation](https://codesandbox.io/s/simple-usage-forked-bsih4?file=/src/App.js) in monaco-react.
