### ISSUE TITLE
Uncaught TypeError: Cannot read property 'config' of undefined

### ISSUE THREAD

**Issue by petermikitsh** [suren-atoyan/monaco-react#248]
**Describe the bug**

<img width="1105" alt="Screen Shot 2021-05-20 at 9 54 53 AM" src="https://user-images.githubusercontent.com/1571918/119018907-787ed680-b951-11eb-942b-c1363ba9de13.png">

**To Reproduce**

`window.require` (discussed below) is undefined. Is there something about this webpack config that would be problematic? How/where is `window.require` defined?

<details>
  <summary>Webpack Config</summary>
<p>

```js
{
  mode: 'development',
  entry: './src/client/index',
  output: {
    filename: '[name].js',
    libraryTarget: 'system',
    path: '/Users/pmikitsh/git/apps/packages/data-query/dist',
    uniqueName: 'data-query',
    devtoolNamespace: 'data-query',
    publicPath: 'http://0.0.0.0:9010/'
  },
  module: {
    rules: [
      {
        test: /\.(js|ts)x?$/,
        exclude: /node_modules/,
        use: {
          loader: '/Users/pmikitsh/git/apps/node_modules/babel-loader/lib/index.js'
        }
      },
      {
        test: /\.css$/i,
        include: [ /node_modules/, /src/ ],
        use: [
          {
            loader: '/Users/pmikitsh/git/apps/node_modules/style-loader/dist/cjs.js'
          },
          {
            loader: '/Users/pmikitsh/git/apps/node_modules/css-loader/dist/cjs.js',
            options: { modules: false }
          }
        ]
      },
      {
        test: /\.(bmp|png|svg|jpg|jpeg|gif|webp)$/i,
        exclude: /node_modules/,
        type: 'asset/resource'
      },
      {
        test: /\.html$/i,
        exclude: /node_modules/,
        type: 'asset/source'
      },
      { test: /\.ttf$/, use: [ 'file-loader' ] }
    ]
  },
  devtool: 'source-map',
  devServer: {
    compress: true,
    historyApiFallback: true,
    headers: { 'Access-Control-Allow-Origin': '*' },
    firewall: false,
    client: { host: 'localhost' },
    port: 9010,
    https: false
  },
  externals: [],
  plugins: [
    BundleAnalyzerPlugin {
      opts: {
        analyzerMode: 'disabled',
        analyzerHost: '127.0.0.1',
        reportFilename: null,
        reportTitle: [Function (anonymous)],
        defaultSizes: 'parsed',
        openAnalyzer: true,
        generateStatsFile: false,
        statsFilename: 'stats.json',
        statsOptions: null,
        excludeAssets: null,
        logLevel: 'info',
        startAnalyzer: true,
        analyzerPort: 8888
      },
      server: null,
      logger: Logger {
        activeLevels: Set(4) { 'info', 'warn', 'error', 'silent' }
      }
    },
    SystemJSPublicPathWebpackPlugin {
      options: {
        systemjsModuleName: '@platform-ui/data-query',
        rootDirectoryLevel: undefined
      }
    },
    HtmlWebpackPlugin { userOptions: {}, version: 5 },
    StandaloneSingleSpaPlugin {
      options: {
        isParcel: false,
        activeWhen: [ '/' ],
        importMap: { imports: {} },
        disabled: true,
        HtmlWebpackPlugin: [class HtmlWebpackPlugin] {
          version: 5,
          getHooks: [Function: getHtmlWebpackPluginHooks],
          createHtmlTagObject: [Function: createHtmlTagObject]
        },
        appOrParcelName: '@platform-ui/data-query'
      }
    },
    ForkTsCheckerWebpackPlugin {
      options: { typescript: { mode: 'write-references' } }
    }
  ],
  resolve: {
    extensions: [
      '.mjs',  '.js',
      '.jsx',  '.wasm',
      '.json', '.ts',
      '.tsx'
    ],
    fallback: {
      assert: '/Users/pmikitsh/git/apps/node_modules/assert/assert.js',
      buffer: '/Users/pmikitsh/git/apps/node_modules/buffer/index.js',
      child_process: false,
      cluster: false,
      console: '/Users/pmikitsh/git/apps/node_modules/console-browserify/index.js',
      constants: '/Users/pmikitsh/git/apps/node_modules/constants-browserify/constants.json',
      crypto: '/Users/pmikitsh/git/apps/node_modules/crypto-browserify/index.js',
      dgram: false,
      dns: false,
      domain: '/Users/pmikitsh/git/apps/node_modules/domain-browser/source/index.js',
      events: '/Users/pmikitsh/git/apps/node_modules/events/events.js',
      fs: false,
      http: '/Users/pmikitsh/git/apps/node_modules/stream-http/index.js',
      https: '/Users/pmikitsh/git/apps/node_modules/https-browserify/index.js',
      module: false,
      net: false,
      os: '/Users/pmikitsh/git/apps/node_modules/os-browserify/browser.js',
      path: '/Users/pmikitsh/git/apps/node_modules/path-browserify/index.js',
      punycode: '/Users/pmikitsh/git/apps/node_modules/node-libs-browser/node_modules/punycode/punycode.js',
      process: '/Users/pmikitsh/git/apps/node_modules/process/browser.js',
      querystring: '/Users/pmikitsh/git/apps/node_modules/querystring-es3/index.js',
      readline: false,
      repl: false,
      stream: '/Users/pmikitsh/git/apps/node_modules/stream-browserify/index.js',
      _stream_duplex: '/Users/pmikitsh/git/apps/node_modules/readable-stream/duplex.js',
      _stream_passthrough: '/Users/pmikitsh/git/apps/node_modules/readable-stream/passthrough.js',
      _stream_readable: '/Users/pmikitsh/git/apps/node_modules/readable-stream/readable.js',
      _stream_transform: '/Users/pmikitsh/git/apps/node_modules/readable-stream/transform.js',
      _stream_writable: '/Users/pmikitsh/git/apps/node_modules/readable-stream/writable.js',
      string_decoder: '/Users/pmikitsh/git/apps/node_modules/string_decoder/lib/string_decoder.js',
      sys: '/Users/pmikitsh/git/apps/node_modules/node-libs-browser/node_modules/util/util.js',
      timers: '/Users/pmikitsh/git/apps/node_modules/timers-browserify/main.js',
      tls: false,
      tty: '/Users/pmikitsh/git/apps/node_modules/tty-browserify/index.js',
      url: '/Users/pmikitsh/git/apps/node_modules/url/url.js',
      util: '/Users/pmikitsh/git/apps/node_modules/node-libs-browser/node_modules/util/util.js',
      vm: '/Users/pmikitsh/git/apps/node_modules/vm-browserify/index.js',
      zlib: '/Users/pmikitsh/git/apps/node_modules/browserify-zlib/lib/index.js'
    }
  },
  stats: 'errors-warnings'
}
```
</p>

</details>

**Expected behavior**

No runtime error is thrown

**Screenshots**
If applicable, add screenshots to help to explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Latest

**Additional context**

In file `node_modules/@monaco-editor/loader/lib/es/loader/index.js`:

```js
function configureLoader() {
  var state = getState(function (_ref3) {
    var config = _ref3.config,
        resolve = _ref3.resolve,
        reject = _ref3.reject;
    return {
      config: config,
      resolve: resolve,
      reject: reject
    };
  });
  var require = window.require;

  require.config(state.config);
```

I am observing that `window.require` is undefined.

**Comment by suren-atoyan** [comment]
The `require` object should be globally available after [monaco-loader script execution](https://github.com/microsoft/monaco-editor-samples/blob/main/browser-amd-editor/index.html#L12). You may have some environmental problem with `require`. Could you please provide more info about your environment? Is it possible to have a reproducible snippet/repo?

**Comment by petermikitsh** [comment]
Here is the repo.

Live demo: https://petermikitsh.github.io/monaco-react-248/
Code: https://github.com/petermikitsh/monaco-react-248

The problem seems to be loading SystemJS here => https://github.com/petermikitsh/monaco-react-248/blob/bbe56cb73c1587f43a92bf916f9d596909055246/src/index.ejs#L14-L15

**Comment by dizys** [comment]
Encountering the same problem when bundling using Parcel v2.

**Comment by suren-atoyan** [comment]
Hi @petermikitsh @dizys 

The problem here is `SystemJS`, it conflicts with the `monaco` loader.

<img width="892" alt="Screen Shot 2021-05-23 at 14 40 19" src="https://user-images.githubusercontent.com/13118722/119257096-d5d68a00-bbd4-11eb-8a30-c4a2459581ae.png">

Why you load these scripts? You use `webpack`, there is no need to load `SystemJS`. I wonder how you came to this, seems like they are from another project, because they are not and can't be related to the setup you've sent me

**Comment by petermikitsh** [comment]
I am using SystemJS because I am load my apps via micro-frontend architecture via [single-spa](https://github.com/single-spa/single-spa). I didn't add that to my example, because I wanted the example to communicate the bug with as few distractions as possible. (It's a reasonable question, though, since you're correct that I'm not actively using SystemJS for anything in the reproduction: but in my actual project, I am).

**Comment by suren-atoyan** [comment]
@petermikitsh I see, the problem is that `systemJS` `define` function is conflicting with `monaco-loader` `define` function. To avoid it one option is doing something like [this](https://github.com/microsoft/monaco-editor/issues/90#issuecomment-243395277). So, try this instead of `index.js` of your example:

```js
import React from "react";
import ReactDOM from "react-dom";
import Editor from "@monaco-editor/react";

const systemJsDefine = window.define;
window.define = null;

function App() {
  function handleEditorMount() {
    window.define = systemJsDefine;
  }

  return (
    <Editor
      height="90vh"
      onMount={handleEditorMount}
    />
  )
}

const mount = document.createElement("div");
document.body.appendChild(mount);

ReactDOM.render(<App />, mount);
```

<hr />

Check the `monaco-loader` source. Search for `if (typeof AMDLoader.global.define !== 'function' || !AMDLoader.global.define.amd) {`. The existing `global.define` doesn't let it to initialize the `monaco-loader`

**Comment by joeldenning** [comment]
I help maintain SystemJS - here's an issue where I discussed a similar problem with other systemjs users. Deleting `window.define` and reinstating it later is a good option, or deleting the entire `amd.js` extra if you can.

**Comment by mssngr** [comment]
This still is an issue, and the workaround doesn't work for our Create React App, at least. Having to abandon Monaco Editor because of this.

**Comment by suren-atoyan** [comment]
@mssngr could you please provide a reproducible code snippet or more information about your environment? Usually, we have this issue when there are global `require/define` (the previous messages in this issue can be helpful) functions that are conflicting with the ones created by monaco.

**Comment by huangwentai** [comment]
![image](https://user-images.githubusercontent.com/19923827/163911211-b44d2488-3649-4fa5-a608-60c9883f7e24.png)
https://github.com/systemjs/systemjs/issues/2250
i find this , option 2 maybe a solution  ，i dont know witch file is ‘/wx.js’ ？

**Comment by josealvarez97** [comment]
@suren-atoyan why did you close this issue? I am encountering this issue after installing Monaco editor on a create-react-app with the Typescript template.

**Comment by josealvarez97** [comment]
> @suren-atoyan why did you close this issue? I am encountering this issue after installing Monaco editor on a create-react-app with the Typescript template.

Nevermind. I had placed the package on the root folder of the repo, not the root folder of the app, by accident.

**Comment by Pines-Cheng** [comment]
> @petermikitsh I see, the problem is that `systemJS` `define` function is conflicting with `monaco-loader` `define` function. To avoid it one option is doing something like [this](https://github.com/microsoft/monaco-editor/issues/90#issuecomment-243395277). So, try this instead of `index.js` of your example:
> 
> @ petermikitsh 我明白了，问题在于 systemJS 定义函数与 monaco-loader 定义函数是冲突的。为了避免这种情况，一种选择是这样做。因此，请尝试使用以下代码来代替示例中的 index.js:
> 
> ```js
> import React from "react";
> import ReactDOM from "react-dom";
> import Editor from "@monaco-editor/react";
> 
> const systemJsDefine = window.define;
> window.define = null;
> 
> function App() {
>   function handleEditorMount() {
>     window.define = systemJsDefine;
>   }
> 
>   return (
>     <Editor
>       height="90vh"
>       onMount={handleEditorMount}
>     />
>   )
> }
> 
> const mount = document.createElement("div");
> document.body.appendChild(mount);
> 
> ReactDOM.render(<App />, mount);
> ```
> 
> Check the `monaco-loader` source. Search for `if (typeof AMDLoader.global.define !== 'function' || !AMDLoader.global.define.amd) {`. The existing `global.define` doesn't let it to initialize the `monaco-loader`
> 
> 检查一下摩纳哥装载机的来源。搜索 if (typeof AMDLoader.global.Definition！= = ‘ function’| | ！定义){。现有的 global.Definition 不允许它初始化 monaco-loader

this solution probably bring out system amd loader not work.
