### ISSUE TITLE
Editor crashes when compiler options are set

### ISSUE THREAD

**Issue by anubra266** [suren-atoyan/monaco-react#253]
**Describe the bug**
When monaco compiler options are set in editorDidMount, hovering over any character in the editor crashes it.

```js
const handleEditorDidMount: OnMount = (editor, monaco) => {
    const compilerOptions = {
      allowJs: true,
      allowSyntheticDefaultImports: true,
      alwaysStrict: true,
      jsx: "React",
      jsxFactory: "React.createElement"
    };

    monaco.languages.typescript.typescriptDefaults.setCompilerOptions(
      compilerOptions
    );
    monaco.languages.typescript.javascriptDefaults.setCompilerOptions(
      compilerOptions
    );
  };
```

Reproduction here

https://codesandbox.io/s/peaceful-wilson-kjf47?file=/src/App.tsx

![Peek 2021-05-31 14-16](https://user-images.githubusercontent.com/30869823/120535213-a0068200-c3da-11eb-849b-cdb4d5a6bdfb.gif)

**Comment by suren-atoyan** [comment]
https://user-images.githubusercontent.com/13118722/120547165-cb509780-c401-11eb-89d1-5981fe8191f7.mov

hmmm, strange, it doesn't crash on my side, maybe some extension problem?

**Comment by anubra266** [comment]
Still stoked, but it stopped after I added som extra compilerOptions. Thanks for the fast reply.

**Comment by anubra266** [comment]
Hi! I wanted to know if you already run the editor language workers in this package.

**Comment by suren-atoyan** [comment]
> Hi! I wanted to know if you already run the editor language workers in this package.
> 
> ```
> monaco-editor/esm/vs/editor/editor.worker
> monaco-editor/esm/vs/language/typescript/ts.worker
> ```

they should be run by default

**Comment by suren-atoyan** [comment]
<img width="1196" alt="Screen Shot 2021-06-03 at 02 28 20" src="https://user-images.githubusercontent.com/13118722/120560225-6867fc00-c413-11eb-87e0-5b7fa486f1f6.png">

**Comment by anubra266** [comment]
I'm debugging, can't find them in any of my browser thread.

**Comment by anubra266** [comment]
> <img alt="Screen Shot 2021-06-03 at 02 28 20" width="1196" src="https://user-images.githubusercontent.com/13118722/120560225-6867fc00-c413-11eb-87e0-5b7fa486f1f6.png">

Oh...I'm on firefox.

**Comment by anubra266** [comment]
Thanks...I found it in Firefox's network tab too. I was checking the debug bar before.

**Comment by nurulakbaral** [comment]
> Refe

I have the same problem as you, can you give me a solution?
![image](https://user-images.githubusercontent.com/46098272/198976035-6df21616-0b38-4cca-bfe7-bb074609cea2.png)

**Comment by nurulakbaral** [comment]
> > Refe
> 
> I have the same problem as you, can you give me a solution? ![image](https://user-images.githubusercontent.com/46098272/198976035-6df21616-0b38-4cca-bfe7-bb074609cea2.png)

Solved this way:
``` // References for solve compiler options problem
    // Ref: https://github.com/suren-atoyan/monaco-react/issues/75#issuecomment-651406227
    // Ref: https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.typescript.CompilerOptions.html
    let options = monaco.languages.typescript.typescriptDefaults.getCompilerOptions()
    options.strictNullChecks = true
    monaco.languages.typescript.typescriptDefaults.setCompilerOptions(options)```
