### ISSUE TITLE
Support for Textmate grammar?

### ISSUE THREAD

**Issue by golmujik** [suren-atoyan/monaco-react#255]
How to use onigasm with monaco textmate please help

**Comment by suren-atoyan** [comment]
Hi @golmujik 

The question should be referred to the original library [monaco-editor](https://github.com/microsoft/monaco-editor) (not `React` wrapper). [This](https://github.com/microsoft/monaco-editor/issues/1915) can be helpful

**Comment by golmujik** [comment]
Okay let this issue be closed but can you help me please? I am really unable to find a solution since last 2 days
I already visited the link you sent but I am unable to setup onigasm and monaco-textmate in next with this @monaco/react binding.

Please can you help?

**Comment by suren-atoyan** [comment]
> Okay let this issue be closed but can you help me please? I am really unable to find a solution since last 2 days
> I already visited the link you sent but I am unable to setup onigasm and monaco-textmate in next with this @monaco/react binding.
> 
> Please can you help?

can you find a working example with a monaco-editor? I can "convert" it to monaco-react
