### ISSUE TITLE
Update monaco editor dependency to 0.25

### ISSUE THREAD

**Issue by ivan-prodanov** [suren-atoyan/monaco-react#256]
Microsoft pushed a massive VS Code update recently, some of the cool stuff is also available in monaco-editor 0.25.

Could you please update your package so this version is supported?

**Comment by suren-atoyan** [comment]
updated: please check v4.2.0

**Comment by 321ckatz123** [comment]
@suren-atoyan This doesn't appear to have changed in v4.2.0.
