### ISSUE TITLE
Extend peerDependency range to include monaco-editor 0.25.x

### ISSUE THREAD

**Issue by AviVahl** [suren-atoyan/monaco-react#258]
**Describe the bug**
When installing `@monaco-editor/react` alongside the latest `monaco-editor` version (currently 0.25.2), one gets a peerDependency warning.

**To Reproduce**

```
mkdir test-peer
cd test-peer
npm init -y
npm i monaco-editor @monaco-editor/react react react-dom
```

See warning: `npm WARN @monaco-editor/react@4.2.0 requires a peer of monaco-editor@^0.23.0 but none is installed. You must install peer dependencies yourself.`

**Expected behavior**
Support latest stable `monaco-editor` release.

**Comment by gperdomor** [comment]
I don't know if it's related to this but with 4.2.0 I can't type some characters like `{`, `}`, `[`, `]` using json language

**Comment by ritz078** [comment]
> I don't know if it's related to this but with 4.2.0 I can't type some characters like {, }, [, ] using json language

It has been fixed in https://github.com/microsoft/monaco-editor/issues/2533.

**Comment by suren-atoyan** [comment]
Hello everyone!

Could you please check the latest ([v4.2.1](https://github.com/suren-atoyan/monaco-react/releases/tag/v4.2.1)) version?

**Comment by AviVahl** [comment]
Issue is fixed. Thanks! :)
