### ISSUE TITLE
Support rego language of OPA

### ISSUE THREAD

**Issue by liavyona** [suren-atoyan/monaco-react#261]
I would like to see `rego` as a supported language.

**Comment by suren-atoyan** [comment]
Hello @liavyona, sorry for the late answer.

This question should have been referred to [monaco-editor](https://github.com/microsoft/monaco-editor), not to `monaco-react` (the last one is just a `React` wrapper around `monaco-editor`)

**Comment by dvh91** [comment]
@liavyona Were you able to find a `rego` monaco language definition?
