### ISSUE TITLE
How to generate different instances？

### ISSUE THREAD

**Issue by AshaLiu** [suren-atoyan/monaco-react#265]
**Describe the bug**
There are many places in my project where I need an editor. 
Because of the design of the UI map, some are white and some are black. 
But once I set one of them to black, all the others become black. 
It looks like everyone shared an instance. How can I solve it? Tanks a lot.

**To Reproduce**

here is my [code snippet in codesandbox](https://codesandbox.io/s/simple-usage-forked-kn0qi?file=/src/App.js)

**Expected behavior**

**Comment by AshaLiu** [comment]
https://github.com/Microsoft/monaco-editor/issues/338

**Comment by zl-sales** [comment]
Have you solved the problem？
