### ISSUE TITLE
[Nextjs/TS] Consume monaco types

### ISSUE THREAD

**Issue by moklick** [suren-atoyan/monaco-react#274]
First of all thanks for this great library! It saves us a lot of time and it works great with Nextjs :) 

The problem that I am facing is that I can't import types (for example `IEditorOption`). When I see it right the types are part of the monaco object but when I try to import monaco:

```js 
import * as monaco from 'monaco-editor/esm/vs/editor/editor.api';
```

I get the following error.

```
./node_modules/monaco-editor/esm/vs/base/browser/ui/actionbar/actionbar.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules/monaco-editor/esm/vs/base/browser/ui/actionbar/actionbar.js
```

There is an open issue in the monaco-editor repo https://github.com/microsoft/monaco-editor/issues/886 but no answer for this. Do you have an idea how we can fix this? Is there something integrated in this package that could help us to get the types?

Thanks in advance!

**Comment by thebearingedge** [comment]
```
.
├── components
│   └── editor.tsx
├── next-env.d.ts
├── next.config.js
├── package.json
├── pages
│   └── index.tsx
├── tsconfig.json
├── typings
│   └── monaco-editor
│       └── index.d.ts
└── workers
    └── eslint.worker.ts
```

##### `typings/monaco-editor/index.d.ts`

```ts
import * as monaco from 'monaco-editor'

declare module 'monaco-editor' {
  export type Monaco = typeof monaco
  export type MonacoTheme = monaco.editor.IStandaloneThemeData
  export type MonacoEditor = monaco.editor.IStandaloneCodeEditor
  export type MonacoEditorOptions = monaco.editor.IStandaloneEditorConstructionOptions
}
```

##### `components/editor.tsx`
```ts
import { Monaco, MonacoTheme, MonacoEditor, MonacoEditorOptions } from 'monaco-editor'
```

**Comment by moklick** [comment]
Thanks a lot @thebearingedge :)
