### ISSUE TITLE
Error on edit

### ISSUE THREAD

**Issue by colramos-amd** [suren-atoyan/monaco-react#278]
**Issue**
I've successfully loaded a Monaco editor instance into my web app, but encounter an error in the app whenever I change it.

Everything works as expected until I modify my `editor` instance in any way (i.e. add text, resize editor window, etc.)

The web application I'm using, [Grafana](https://grafana.com/), spits out this error whenever I attempt to interact with my editor

**The Error**

![Screenshot from 2021-08-17 12-25-30](https://user-images.githubusercontent.com/87152878/129788000-25c8b972-fa75-4aed-bd4f-e898e215eb46.png)

**Code**
I've tried to reference the [editor instance docs](https://www.npmjs.com/package/@monaco-editor/react#editor-instance) as much as possible. Does anyone know why the editor is failing to handle updates?

```react
import Editor from '@monaco-editor/react';
...

interface MonacoEditorProps {
  value: string;
  theme: string;
  language: string;
  onChange: (value?: string | undefined) => void;
}
class MonacoEditor extends React.PureComponent<MonacoEditorProps> {
  getEditorValue: any | undefined;
  editorInstance: any | undefined;

  onSourceChange = () => {
    this.props.onChange(this.getEditorValue());
  };
  onEditorDidMount = (getEditorValue: any, editorInstance: any) => {
    this.getEditorValue = getEditorValue;
    this.editorInstance = editorInstance;
  };
  updateDimensions() {
    this.editorInstance.layout();
  }
  render() {
    const source = this.props.value;
    if (this.editorInstance) {
      this.editorInstance.layout();
    }
    return (
      <div onBlur={this.onSourceChange}>
        <Editor
          height={'33vh'}
          language={this.props.language}
          theme={this.props.theme}
          value={source}
          onMount={this.onEditorDidMount}
        />
      </div>
    );
  }
}
```

**Info**
 - OS: Ubuntu 20.04.2 LTS
 - Browser: Chrome
 - Version: [@monaco-editor/react](https://www.npmjs.com/package/@monaco-editor/react) v4.2.2

**Comment by suren-atoyan** [comment]
Hello @colramos-amd. There is an error in your code:

```js
  onEditorDidMount = (getEditorValue: any, editorInstance: any) => {
    this.getEditorValue = getEditorValue;
    this.editorInstance = editorInstance;
  };
```

In the (that you've mentioned above) the `onEditorDidMount` will receive `editorInstance` as a first argument and `monacoInstance` as a second. In your example `editorInstance` is the section argument.


In the [editor instance docs](https://www.npmjs.com/package/@monaco-editor/react#editor-instance) (that you've mentioned above) the `onEditorDidMount` receives `editorInstance` as the first argument and `monacoInstance` as the second. In your example, `editorInstance` is the second argument.
