### ISSUE TITLE
Add a custom keyboard shortcut/handler?

### ISSUE THREAD

**Issue by icy-meteor** [suren-atoyan/monaco-react#280]
I wish to add a new keyboard shortcut handler and perform some action whenever the user presses that combination.
I couldn't find anything in the docs related to this.

Any idea how to go about this?

**Comment by suren-atoyan** [comment]
hello @icy-meteor 

yes, you can use [addCommand](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.istandalonecodeeditor.html#addcommand) and [addAction](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.istandalonecodeeditor.html#addaction) to achive that.

also check [this](https://codesandbox.io/s/addcommand-xsn9k?file=/src/App.js)
