### ISSUE TITLE
Unable to load without network

### ISSUE THREAD

**Issue by lin-mt** [suren-atoyan/monaco-react#282]
**Describe the bug**
Develop completion in the case of a network, then turn off the network, refresh your browser, and report an error.

![image](https://user-images.githubusercontent.com/58337359/132513465-661eefa8-cfd5-4c0e-904f-e0d48f96252d.png)

**Comment by suren-atoyan** [comment]
By default, the library downloads the monaco source code from CDN, which can be changed by using `monaco-loader`. Read about the [monaco-loader](https://github.com/suren-atoyan/monaco-react#loader-config)
