### ISSUE TITLE
NextJS multiple errors and warning with workers and duplicate definitions of modules 

### ISSUE THREAD

**Issue by makbeth** [suren-atoyan/monaco-react#284]
**Describe the bug**
Multiple errors and warnings in console when rendering Editor component with javascript language:

> defaultWorkerFactory.ts:27 
> Refused to create a worker from 'blob:http://localhost:3000/dc2ffd16-ac65-4982-8193-af575bb4f966' because it violates the following Content Security Policy directive: "script-src * 'unsafe-inline' 'unsafe-eval'". 
> Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback.

> Could not create web worker(s). Falling back to loading web worker code in main thread, which might cause UI freezes. Please see https://github.com/microsoft/monaco-editor#faq

When I try to set CSS, I receive these warnings additionally:

> Duplicate definition of module 'vscode-css-languageservice/parser/cssScanner'
> Duplicate definition of module 'vscode-css-languageservice/utils/strings'
> Duplicate definition of module 'vscode-css-languageservice/parser/cssNodes'
> ...

The editor works fine, but I think it's not normal behavior (mean errors and warnings).

I use React JS 17.0.2, NextJS 11.1.2, TypeScript 4.4.3

The code of my component is quite simple: 
```
import React, { FC } from 'react';
import { ITheme } from 'store/themes/types';
import Editor from '@monaco-editor/react';

interface SubTabCustomCssProps {
  element: ITheme;
}

const SubTabCustomCss: FC<SubTabCustomCssProps> = ({ element }) => (
  <div>
    <Editor language="css" />
  </div>
);

export default SubTabCustomCss;
```

**Screenshots**
For javascript:
![image](https://user-images.githubusercontent.com/7573343/134242705-a0cb2e69-13c7-438a-8053-f5da992f9abe.png)
For CSS
![image](https://user-images.githubusercontent.com/7573343/134243084-686fe9f5-c95a-43c2-b057-ed82983861b6.png)

**Desktop (please complete the following information):**
 - OS: Mac OS (Big Sur 11.6)
 - Browser Chrome  
 - Version 93.0.4577.82

**Additional context**
If you need any additional info, let me know, please.

**Comment by softmarshmallow** [comment]
@makbeth What was the problem? please share.

I'm getting this message.
`Duplicate definition of module '===anonymous2===' `

**Comment by corydeppen** [comment]
I'm seeing a similar `Duplicate definition of module '===anonymous1==='` warning when trying to render two different editors on the same page in a React app using Vite.
