### ISSUE TITLE
When loading the component on a SharePoint 2019 on premises, it is stuck on "loading..."

### ISSUE THREAD

**Issue by shaipetel** [suren-atoyan/monaco-react#295]
**Describe the bug**
When you try to load this component on a modern experience page in SharePoint 2019, the editor is stuck on "loading..."
Same page works on SharePoint online.

Seems like this is the broken flow:
the "configureLoader" function configures require, then calls:
```require(['vs/editor/editor.main'], function (monaco) {...}```

That gets the loader.js and the editor.main.js from the CDN on the page.

While on SPO it will then continue to load the rest of the needed files, on 2019 it will stop there and return "undefined" to the require handler function.

**To Reproduce**

1. Create an SPFx web part package that uses this component
2. Add it to a modern page on SharePoint 2019
3. The editor will remain stuck on "loading..."

For reproduction, I am more than happy to share login and code to a test-site.

**Expected behavior**
Editor should load correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/6225881/136587246-57e6696b-7190-441f-9daa-bded6a98b6bb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, 11
 - Browser Chrome, Edge
 - Version latest versions

**Comment by suren-atoyan** [comment]
Hello @shaipetel. I am sorry, but I have no idea what "SharePoint 2019" is; I've never heard about it. I don't think we can go with such kinds of steps:

> 1. Create an SPFx web part package that uses this component
> 2. Add it to a modern page on SharePoint 2019
> ...

Does your environment have access to CND? Are there any CSP restrictions/limitations? Most probably your environment, for some reason, can't load monaco sources, and in most cases, it's related to CDN. Don't you see errors in the console/network panel? If you don't want to load monaco source from CDN (or you want to load it from another CDN), please check the [loader-config](https://github.com/suren-atoyan/monaco-react#loader-config) section.

If nothing works, we can try this:

> For reproduction, I am more than happy to share login and code to a test-site.

**Comment by shaipetel** [comment]
Thanks @suren-atoyan !
In short, the web page, client and server are all connected to the internet.
There is no problem loading files from a CDN.
But - the page has a version of requireJS on it.

The component uses requireJS successfully to load the "loader.js" and the "loader.js" successfully loads the "editor.main.js"

But it seems that's where it stops.

While on a different page, the loader and editor continue to load many other files from the CDN, in this broken page nothing more is being loaded, no messages are added to the console, no errors thrown, but the loading process stops and the container is just showing "loading..." and that's it.

the require(...) call returns an editor object on other pages, but on the broken page the require(...) call returns undefined.

Seems to be some issue with the way dependencies are being loaded using require.

I can share-screen and show you the broken environment if you think we can debug this together, or I can share access with you or anyone else who is interested in trying to have a look at it?

Thanks!

**Comment by suren-atoyan** [comment]
@shaipetel most probably it's related to the original package (not react wrapper). But let's try something - could you please check [this](https://github.com/suren-atoyan/monaco-react/issues/248) discussion.

**Comment by shaipetel** [comment]
Amazing. I checked doing the same with require and didn't help, but deleting window.define does solve the issue for me as well.

**Comment by suren-atoyan** [comment]
@shaipetel glad it solved your problem 🥳
