### ISSUE TITLE
can not defineTheme

### ISSUE THREAD

**Issue by lin-mt** [suren-atoyan/monaco-react#309]
https://codesandbox.io/s/simple-usage-forked-883gj?file=/src/App.js

**Comment by lin-mt** [comment]
How to automatically format the code after the defaultValue takes effect, I tried `beforeMount` and `onMount` to call `editor.getAction('editor.action.formatDocument').run();` but they have no effect and can only be triggered by the user `editor.getAction('editor.action.formatDocument').run();` is effective

**Comment by lin-mt** [comment]
Can you help me solve two problems here, thank you very much~! @suren-atoyan

**Comment by suren-atoyan** [comment]
please, check [this](https://codesandbox.io/s/simple-usage-forked-r3rdj?file=/src/App.js)
