### ISSUE TITLE
Ability to save/export diff editor content as formatted html or png

### ISSUE THREAD

**Issue by kvarforl** [suren-atoyan/monaco-react#310]
**Is your feature request related to a problem? Please describe.**
For the project we are using the diff editor in, users will often need to create diffs between two sets of code for code reviews.
 These diffs are currently created and saved using Beyond Compare so that the diff file can be stored as documentation.
 It's frustrating to not be able to easily export the formatted diff content directly from the editor, and instead have to copy paste into a separate app.

**Describe the solution you'd like**

- An easy way to access all of the content of the diff editor, including formatting, and content beyond what's in the viewport.
-  Better yet, a method that will export the formatted diff to a file.

**Describe alternatives you've considered**
We've tried using libraries like [html2canvas](https://html2canvas.hertzen.com/) and other methods grabbing the html of the DiffEditor component, but both of these only capture what is currently in the viewport. If either side of the diff requires scrolling to see the whole content, that content won't be displayed in the capture. 
Any other ideas or help would be appreciated!

**Comment by suren-atoyan** [comment]
Hello @kvarforl 

The question/issue should be referred to the original repository ([microsoft/monaco-editor](https://github.com/microsoft/monaco-editor)) not the react-wrapper. However, [this](https://github.com/Microsoft/monaco-editor/issues/866) and [this](https://github.com/microsoft/monaco-editor/issues/1506) may be helpful.
