### ISSUE TITLE
how to get isFocused() state of the editor

### ISSUE THREAD

**Issue by aashiqahmed98** [suren-atoyan/monaco-react#311]
Thanks to @suren-atoyan  for this wonderful plugin with monaco editor, i was wondering there is any method to know about the focused status of the editor.Refer my code below, im using ref and assigning to the editor on mount, when i use 1editorRef.current.isFocused()`, it throws a error saying , no method such  , so how can i get the focused state of the editor instance like text input box we have onFocus props/attribute. Thanks in Advance
```
import { useRef } from 'react'
import Editor from '@monaco-editor/react'

const CodeEditor = (props) => {
	const {
		height,
		width,
		language = 'python',
		code = `# some comment`,
		onCodeChange,
		isReadOnly = false,
	} = props
	const editorRef = useRef(null)

	const editorOnMount = (editor,monaco) => {
		editorRef = editor;
		console.log(editorRef.current.isFocused());
		console.log('editor mounted', editorRef)
	}

	return (
		<Editor
			height={height}
			width={width}
			language={language}
			value={code}
			onChange={onCodeChange}
			options={{ fontSize: 15, cursorStyle: 'block', readOnly: isReadOnly }}
			onMount={editorOnMount}
		/>
	)
}

export default CodeEditor

```

**Comment by suren-atoyan** [comment]
Hello @aashiqahmed98 

Thank you for your feedback.

I've just created a [code snippet](https://codesandbox.io/s/monaco-focus-state-9jmyo?file=/src/App.js) for you, please check it. Check other methods [here](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.IStandaloneCodeEditor.html#onDidBlurEditorText)
