### ISSUE TITLE
editor.onKeyDown and  editor.onDidPaste callback functions do not produce updated React State values. 

### ISSUE THREAD

**Issue by prithvianilk** [suren-atoyan/monaco-react#313]
**Describe the bug**
`editor.onKeyDown` and  `editor.onDidPaste` callback functions do not produce updated React State values. 

**To Reproduce**

1. Within `onMount` function prop given to `handleEditorDidMount` define callbacks on events `onKeyDown` and `onDidPaste` as follows.
2. Try to copy a selected text on the Editor
3. Paste the text on the Editor.

```tsx
    const editorRef = useRef<any>(null);
    // react state containing clipboard text
    const [clipboardText, setClipboardText] = useState<string>('intial value');

    const handleEditorDidMount = (editor: any) => {
        editorRef.current = editor;

        editor.onKeyDown(async function (event: any) {
            const { keyCode, ctrlKey, metaKey } = event;
            if (keyCode === 33 && (metaKey || ctrlKey)) {
                const text = await navigator.clipboard.readText();
                // state change function called
                setClipboardText(text);
            }
        });

        editor.onDidPaste(({ range }: any) => {
            // does not recognise updated state
            // remains 'initial value'
            console.log(clipboardText);
            editor.executeEdits('', [{ range, text: clipboardText }]);
        });
    };

    useEffect(() => {
        // productes the updated value
        // but this is not recognised within editor callbacks `onKeyDown` and `onDidPaste`   
        console.log(clipboardText);
    }, [clipboardText]);

    return (
        <MonacoEditor
                width="100%"
                height="100%"
                language={language}
                theme="vs-light"
                value={code}
                options={{
                    fontSize,
                }}
                onMount={handleEditorDidMount}
                onChange={onChange}
        />
  )
```

**Expected behavior**
- clipboardText is expected to change within the editor event callbacks.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: chrome
 - Version 90.0.4430.212 (Official Build) (64-bit)

**Additional context**
I am trying to only allow copy-paste from text within the Editor component.
To achieve this, I am storing the text copied to the clipboard in a react state within the parent component and only pasting the contents of the state when `onDidPaste` event is called.

**Comment by mattboon** [comment]
Am also wondering how do use dynamic data/state inside the `onMount` function. 

Any help/guidance appreciated!

**Comment by suren-atoyan** [comment]
You attach your event handlers in `onMount`, which is being called once - so, they will refer to the very first value; this is expected behavior - I mean, nothing special, a basic React. There are two options to solve this:

1) use `useRef` and keep the data you want to achieve in ref
2) attach and detach your event handlers accounting to the value change you want to achieve as that value is considered to be a dependency for that action
