### ISSUE TITLE
Local version of the monaco-editor package from jsdeliver

### ISSUE THREAD

**Issue by root-io** [suren-atoyan/monaco-react#316]
I don't want to load anything outside of local scripts

Similar with #217

**Comment by suren-atoyan** [comment]
check [this](https://github.com/suren-atoyan/monaco-react#loader-config) and also, please check the [answer](https://github.com/suren-atoyan/monaco-react/issues/217#issuecomment-980800802) for [#217](https://github.com/suren-atoyan/monaco-react/issues/217)
