### ISSUE TITLE
Editor instance not showing effect of added Action, Command

### ISSUE THREAD

**Issue by rajiff** [suren-atoyan/monaco-react#317]
**Describe the bug**
addAction, addCommand not working, which is as per the examples provided 

**To Reproduce**

https://codesandbox.io/s/monaco-react-app-actions-yqlv3

**Expected behavior**
Expecting editor instance to add the action and behave as per the added action, command

**Desktop (please complete the following information):**

**Additional context**
Editor instance which is returned during mount, ie expected to behave as per the Monaco playground, such as https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-adding-an-action-to-an-editor-instance but the editor instance not showing effect

**Comment by suren-atoyan** [comment]
@rajiff it's not working because it should have been `monaco.KeyCode.KEY_S` not `monaco.KeyCode.Key_S`
