### ISSUE TITLE
cannot find namespace 'monaco' when trying to use typescript

### ISSUE THREAD

**Issue by Altair2169** [suren-atoyan/monaco-react#321]
**Describe the bug**
I have been trying to use typescript inside my code but I have not been able to define types for `monaco` and `editor` etc. I have installed `monaco-editor` for the type declarations and included `monaco.d.ts` in my `tsconfig.json` like this 
```
"include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx",
    "theme.js",
    "node_modules/monaco-editor/monaco.d.ts"
  ],
```
but when I try to define the types for e.g. `editorOptions` 
```
const editorOptions: monaco.editor.IStandaloneEditorConstructionOptions = {
    fontSize: '15px',
    minimap: {
      enabled: true,
    },
``` 
I get the error. `cannot find namespace 'monaco'` on `monaco.editor.IStandaloneEditorConstructionOptions`

**Screenshots**
If applicable, add screenshots to help to explain your problem.
[Link](https://imgur.com/a/stwrOnL)
**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] : Chrome
 

**Additional context**

**Comment by suren-atoyan** [comment]
[here](https://github.com/suren-atoyan/monaco-react/blob/master/src/types.d.ts#L4) how we use TS definitions of monaco

**Comment by rishi-habu** [comment]
Solved this issue by adding `moduleNameMapper` to the jest config. I have my jest config added to my `package.json`.
Ref,
```
"jest": {
  "moduleNameMapper": {
    "monaco-editor": "<rootDir>/node_modules/@monaco-editor/react"
  }
}
```

**Comment by RishikeshVedpathak** [comment]
Solved this issue by adding `moduleNameMapper` to the jest config. I have my jest config added to my `package.json`.
Ref,
```
"jest": {
  "moduleNameMapper": {
    "monaco-editor": "<rootDir>/node_modules/@monaco-editor/react"
  }
}
```
