### ISSUE TITLE
Why can it be used before, but suddenly it doesn't work? Monaco initialization: error is displayed

### ISSUE THREAD

**Issue by TingWaitLin** [suren-atoyan/monaco-react#323]
**Describe the bug**
![image](https://user-images.githubusercontent.com/68936723/146729950-3d09ac75-4d7e-4f75-8ae8-bdbcba7a3dc4.png)

**To Reproduce**

Or, please add a minimal code snippet to reproduce the issue, for example in [codesandbox](https://codesandbox.io/).

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help to explain your problem.

**Desktop (please complete the following information):**

**Additional context**

**Comment by bianbiandashen** [comment]
jsdeliver cdn 挂了

**Comment by suren-atoyan** [comment]
@TingWaitLin check [this](https://github.com/suren-atoyan/monaco-react/issues/324)
