### ISSUE TITLE
7.js:17 GET https://cdn.jsdelivr.net/npm/monaco-editor@0.28.1/min/vs/loader.js net::ERR_CERT_COMMON_NAME_INVALID strict-origin-when-cross-origin 

### ISSUE THREAD

**Issue by bianbiandashen** [suren-atoyan/monaco-react#324]
![image](https://user-images.githubusercontent.com/16240681/146734154-4b36ee0d-dfa5-4170-a910-dae82507bb79.png)

**Comment by suren-atoyan** [comment]
@bianbiandashen could you please try it again; I guess there was an issue with `jsdelivr`

**Comment by suren-atoyan** [comment]
@bianbiandashen I got lots of similar requests from China; check [this](https://github.com/jsdelivr/jsdelivr/issues/18354). Before fixing the `jsdelivr` issue you can configure the library to load the sources from other places, something like this:

```js
import Editor, { loader } from "@monaco-editor/react";

loader.config({
  paths: {
    vs: "https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.31.1/min/vs"
  }
});

export default function App() {
  return <Editor height="90vh" />;
}

```

**Comment by suren-atoyan** [comment]
[codesandbox](https://codesandbox.io/s/pensive-danny-ymugs?file=/src/App.js:0-238)

**Comment by hulk-sh** [comment]
import MonacoEditor, { loader } from '@monaco-editor/react';

loader.config({
paths: { vs: 'https://unpkg.com/monaco-editor@0.28.1/min/vs' },
});

Switching domain names can solve this problem temporarily

**Comment by baobao12356** [comment]
> ```js
> Editor
> ```Isn't there this loader in version 3.7?

**Comment by baobao12356** [comment]
> @bianbiandashen我收到了很多来自中国的类似要求；检查[这个](https://github.com/jsdelivr/jsdelivr/issues/18354)。在解决`jsdelivr`问题之前，您可以配置库以从其他地方加载源，如下所示：
> 
> ```js
> import  Editor ,  {  loader  }  from  "@monaco-editor/react" ;
> 
> 装载机。配置（{
>   路径：{ 
>     vs：“https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.31.1/min/vs” 
>   } 
> } ）；
> 
> export  default  function  App ( )  { 
>   return  < Editor  height = "90vh"  / > ; 
> }
> ```

How to load this js in version 3.7

**Comment by baobao12356** [comment]
> ```js
> https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.31.1/min/vs
> ```

How to load js downloaded locally
