### ISSUE TITLE
cdn resource couldn't access

### ISSUE THREAD

**Issue by gyj963** [suren-atoyan/monaco-react#325]
![6601639988589_ pic](https://user-images.githubusercontent.com/5072061/146735499-225f87b9-97d0-4cfe-900d-cd14a696e3dd.jpg)
https://cdn.jsdelivr.net/npm/monaco-editor@0.25.2/min/vs/loader.js couldn't access 
your website has the same question
![6611639988790_ pic_hd](https://user-images.githubusercontent.com/5072061/146736072-d50d2b84-224a-48b8-a813-092b57040507.jpg)
wish fixing it quickly!

**Comment by LaamGinghong** [comment]
It also issue to my project.

**Comment by suren-atoyan** [comment]
@gyj963 @LaamGinghong check [this](https://github.com/suren-atoyan/monaco-react/issues/324)
