### ISSUE TITLE
cdn https://cdn.jsdelivr.net/npm/monaco-editor@0.21.2/min/vs/loader.js 

### ISSUE THREAD

**Issue by baobao12356** [suren-atoyan/monaco-react#326]
![image](https://user-images.githubusercontent.com/22005273/146739290-667fc512-2834-47ff-8724-a06be758e901.png)

**Comment by suren-atoyan** [comment]
@baobao12356 check [this](https://github.com/suren-atoyan/monaco-react/issues/324)

**Comment by hulk-sh** [comment]
import MonacoEditor, { loader } from '@monaco-editor/react';

loader.config({
  paths: { vs: 'https://unpkg.com/monaco-editor@0.28.1/min/vs' },
});

Switching domain names can solve this problem temporarily
