### ISSUE TITLE
SyntaxError: expected expression, got '?'

### ISSUE THREAD

**Issue by KentonParton** [suren-atoyan/monaco-react#331]
**Describe the bug**
When running minimal code it remains in a "Loading" state. I am getting the following error message:
```
SyntaxError: expected expression, got '?'
```
on Firefox and Safari. It works on Chrome.

**To Reproduce**

1. Create a react app
2. Install libs
3. Code snippet
```javascript
import React from 'react';
import Editor from "@monaco-editor/react"

const CodeEditor = (props) => {
  return (
    <Editor
      height="200px"
      language="sql"
      theme='vs'
    />
  );
}

export default CodeEditor;
```
4. Inspect in Firefox or Safari and click on "Console". You will see the above error message.

**Expected behavior**
The editor to be shown without an error 

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser safari and firefox
 - Version 4.3.1

**Comment by suren-atoyan** [comment]
Hi @KentonParton 👋 

I've just created a code snippet (check [this](https://codesandbox.io/s/sweet-yonath-mese8?file=/src/App.js)) with the code you've mentioned above and checked it in:

- OS: macOS Big Sur (v11.2.1)
- Browser: Safari (v14.0.3 (16610.4.3.1.4)) and Firfox (v95.0.2 (64-bit))
- Package version: 4.3.1

But I could find any issue 😕 Could you please check it?
