### ISSUE TITLE
Type error with keycode

### ISSUE THREAD

**Issue by IamFonky** [suren-atoyan/monaco-react#337]
**Describe the bug**
I wanted to bind some key to add action in the editor and the typings are wrong.
The typings tell me to use KeyCode.KeyS but it's undefined. 
The old KeyCode.KEY_S is working but it's not what the type says

**To Reproduce**

Look at this very simple example [https://codesandbox.io/s/typeerror-keycode-react-monaco-editor-fqcvt?file=/src/App.tsx](https://codesandbox.io/s/typeerror-keycode-react-monaco-editor-fqcvt?file=/src/App.tsx)

**Expected behavior**
I want that the type matches the value

**Desktop (please complete the following information):**
Any OS, any browsers

**Comment by IamFonky** [comment]
Workaround, use monaco-editor 0.29.1 as dev dep

**Comment by suren-atoyan** [comment]
Hey 👋 @IamFonky thanks for reporting this. I'll update it in the next release
