### ISSUE TITLE
Hello, how to implement the editor to realize this TS code compilation

### ISSUE THREAD

**Issue by yhj0409** [suren-atoyan/monaco-react#339]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Implement TS code verification
**Describe alternatives you've considered**
 
**Additional context**
![Snipaste_2022-01-25_09-17-51](https://user-images.githubusercontent.com/82952237/150892667-2a5df0c9-4868-46fd-a34d-71fea6aa1412.png)

**Comment by suren-atoyan** [comment]
[DUPLICATE] @yhj0409 please check [this](https://github.com/suren-atoyan/monaco-react/issues/243)
