### ISSUE TITLE
onMount doesn't seem to work

### ISSUE THREAD

**Issue by jmakGH** [suren-atoyan/monaco-react#340]
**Describe the bug**
The `onMount` prop for the Editor component doesn't seem to work.

**To Reproduce**

1. Go to this [sandbox](https://codesandbox.io/s/monaco-instance-onmount-beforemount-forked-jwn3o) which is a quick fork of the example linked in the repo's README
2. Notice `console.log` is passed to `onMount` but nothing is logged to console

**Expected behavior**
The `onMount` prop should pass back the editor and monaco instance.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Version 97.0.4692.99

**Comment by suren-atoyan** [comment]
@jmakGH 

Just changed `onMount={console.log}` to `onMount={() => console.log('check')}` and it works. Seems `codesandbox` overwrite `console.log`, but I am not sure.
