### ISSUE TITLE
Column prop on <Editor />?

### ISSUE THREAD

**Issue by dustinlacewell** [suren-atoyan/monaco-react#347]
Is there any reason why <Editor /> does not have a column prop with which to drive the horizontal position of the cursor?

As it stands, I can't see a way to drive the editor via Redux because you need to store the cursor position, otherwise it gets reset when the component is rerendered. However, there is currently no way to fully initialize the cursor position via props.

**Comment by suren-atoyan** [comment]
After re-renderings you won't lose the cursor position. Most probably you unmount-mount the component, in which case you can use `saveViewState` and `keepCurrentModel` properties to preserve the view state (selection, scroll position, cursor position, etc). Please check the [props](https://github.com/suren-atoyan/monaco-react#props)
