### ISSUE TITLE
Callback function to "unmount" / "cleanup" function

### ISSUE THREAD

**Issue by tomer-dev** [suren-atoyan/monaco-react#349]
First of all, thank you for making this project happen! I can only imagine how many projects are using your library as their backbone, and a customized IDE entirely on the web is a just something we couldn't have imagined a few years ago. 
So kudos 🎊 🚀 🥳 

**Describe the bug**
While there is a clear callback function `onMount`, we miss a cleanup function like `onUnmount` or when closing a tab(=file) `onClose`, and rely on `useEffect` hooks. 

This is significant when already having a complex, customized `Editor` - getting lost in a complex logic with a hook-based lifecycle is rather likely, and makes the Editor more prone to errors regarding model cleanups, etc..

**To Reproduce**
Note - wouldn't happen consistently, but that's the point.

1. open an editor file
2. close an editor file
3. How can you make sure you clean the right models?
4. Open another editor file

Two possible errors that I've encountered by doing the above steps:
* "Model is disposed" - happens because of a custom hook that watches `[file.path]` in the codebase. Switching tabs will trigger cleanup and creation of the model, but the hook won't trigger when closing a file.
*  Memory leak:
```
Error: Trying to add a disposable to a DisposableStore that has already been disposed of. The added object will be leaked!
    at n.add (lifecycle.ts:224:18)
    at m._register (lifecycle.ts:255:22)
    at m._getOrCreateModelManager (editorWorkerServiceImpl.ts:449:30)
    at editorWorkerServiceImpl.ts:459:9
    at async Promise.all (index 0)
```

Monaco version - 4.3.1

**Additional context**
Hooks are the only way to approach the issues above, and they are great - but when things get complex - lifecycle callback functions are the way to go.

**Comment by tomer-dev** [comment]
Seems like this one is likely related https://github.com/suren-atoyan/monaco-react/issues/273

**Comment by tomer-dev** [comment]
Seems like this one is likely related https://github.com/suren-atoyan/monaco-react/issues/273

> when re-open the files I expect that all the files get erase or that the data of all of them is preserve.

**Comment by tomer-dev** [comment]
This one is as close as it can get to the issue above https://github.com/suren-atoyan/monaco-react/issues/305

> I also thought that simply unmounting the editor should be enough to dispose 
...

> To reproduce:
> Open file and made edits
> Close file
> Open file again

**Comment by tomer-dev** [comment]
Possibly this one too, but I'll stop here "><  https://github.com/suren-atoyan/monaco-react/issues/17

**Comment by tomer-dev** [comment]
I solved my issue, and I figured this is another thing other people may try to do - removing the editor when `file` is not defined 

```
{file && <Editor ... />}
```

**Comment by tomer-dev** [comment]
@suren-atoyan you're a star ⭐ ! thanks for the quick response!!

Well, at Rookout we use the IDE to actually create a non-breaking breakpoint(or watchpoint) in production to get more context. That is fairly complex, and we even have Rookout's own debugging language, but that's for another time..
https://www.rookout.com/

So we have a debugger, we have breakpoints and their logic, and that creates a ton of logic.  
The issue I've faced happened 95% of the time because a mistake we did related to React, rendering a very big container component (and its big subtree) conditionally. pseudo: ```{file && <EditorWrapper file={file} ... /> }```

When resolving this, things went fairly well. _But why was it there from the first place?_ 

Well, As you've mentioned above, moving between tabs will trigger a new model, but closing the last opened tab won't trigger a "cleanup" callback. We can do so by tracking the tab count, but that's not trivial. And when `file` gets `null/undefined` we want a clean slate, and in our codebase it seemed "easier" to simply condition the entire component from rendering, making the model to leak and to run code on `disposed` models. 

`onUnmount` prop will force the people to think what happens when we close/don't have an opened file, to think about `file` is undefined, and reverse their `onMount` (which is actually `didMount` in our case).
It will also potentially remove some side effects (=`useEffect`), and make programmers unregister what they've registered previously.

A `callback` is always better than side effects. (not a single word, JAVA!.. OOPs..)

>  What do you mean by "cleaning model"?

`dipose` a created model. We keep multiple models simultaneously, partly because of the breakpoints and its related logic.

> Do you still think we should have onUnmount prop?

Yeah, but not because it is a must, just because it will make programmers make less mistakes.
In any case your project rocks, for real, I'm a fan 🤘🎸

**Comment by suren-atoyan** [comment]
> A callback is always better than side effects. (not a single word, JAVA!.. OOPs..)

I'm more of a functional programming guy :stuck_out_tongue_winking_eye: 

> Yeah, but not because it is a must, just because it will make programmers make less mistakes.

I hear you. I'll add it to my notes and I'll consider it in further releases. I will let you know if there is a decision related to this; before that, let me close the issue (feel free to reopen it if you think we missed something) 🙂  And thanks for your effort :raised_hands:

**Comment by jchnxu** [comment]
My use case here:

1. I'm adding extra scroll event listeners to the monaco element. 
2. I have multiple instances in the same page.
3. The pages will disappear and reappear multiple times when being used.

That's why I need to cleanup those listeners.

Currently we have only

```
export type OnMount = (
  editor: monaco.editor.IStandaloneCodeEditor,
  monaco: Monaco,
) => void;

export type BeforeMount = (
  monaco: Monaco,
) => void;

```

My proposal
1. provide willUnmount as a callback
2. change OnMount to receive a return value as the cleanup function.

**Comment by riotrah** [comment]
It would be a nice convenience, but using the various disposable API fns in a `use-effect` and disposing them in the cleanup fn works, and appears to be a commonly endorsed pattern in this project
