### ISSUE TITLE
umijs Using the wrong

### ISSUE THREAD

**Issue by meikang123** [suren-atoyan/monaco-react#358]
### **usage scenario**
![screenshot-20220403-224313](https://user-images.githubusercontent.com/16129828/161575527-d12a6ffd-70fb-4e31-b4d0-c777d6ab6c31.png)

**### config**
![微信图片_20220403224229](https://user-images.githubusercontent.com/16129828/161575631-b94540b3-c6a3-4484-872c-540e526898c9.png)

**### error**
![微信图片_20220403224246](https://user-images.githubusercontent.com/16129828/161575694-11c52ee3-20e4-4280-a626-809378d85c1b.png)

**Comment by suren-atoyan** [comment]
@meikang123 could you please provide a repo so that we can reproduce it?

**Comment by meikang123** [comment]
> @meikang123 could you please provide a repo so that we can reproduce it?

https://github.com/meikang123/demoMonaco.git
