### ISSUE TITLE
Incompatible with the latest React version v18

### ISSUE THREAD

**Issue by cordosvictor** [suren-atoyan/monaco-react#359]
The library seems to be incompatible with the latest React version v18. I'm trying to install the library and I get the following error:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: flowbite@0.1.0
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0 || ^17.0.0" from @monaco-editor/react@4.4.1
npm ERR! node_modules/@monaco-editor/react
npm ERR!   @monaco-editor/react@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by suren-atoyan** [comment]
@cordosvictor could you please check the latest version - `v4.4.2`?

**Comment by andysmithnf** [comment]
I don't have this issue with `v4.4.1` running React 18, but I have noticed there was the `v4.4.2` release on NPM with no corresponding one here. Where can we see the changes?

**Comment by suren-atoyan** [comment]
@andysmithnf [release](https://github.com/suren-atoyan/monaco-react/releases/tag/v4.4.2) and [changelog](https://github.com/suren-atoyan/monaco-react/blob/master/CHANGELOG.md#versions)
