### ISSUE TITLE
saveViewState is not working when updating value programmatically

### ISSUE THREAD

**Issue by Janpot** [suren-atoyan/monaco-react#365]
**Describe the bug**

When using the editor as a controlled component, each time the value changes programmatically, not as a result of the editor `onChange` prop, the cursor is being reset to the end of the input. If I'm understanding correctly, `saveViewState` should prevent this behavior?

**To Reproduce**

1. Go to https://codesandbox.io/s/multi-model-editor-forked-pir178?file=/src/App.js
2. Place the cursor somewher
3. The value is updated programmatically every second
4. See the cursor jump to the end every second

**Expected behavior**

the cursor position is preserved since `saveViewState` is set. Currently I can work around the problem by updating the editor programmatically and saving/restoring the state manually:  https://codesandbox.io/s/multi-model-editor-forked-yi9m0l?file=/src/App.js

**Comment by suren-atoyan** [comment]
@Janpot in the [second](https://codesandbox.io/s/multi-model-editor-forked-yi9m0l?file=/src/App.js) code snippet you save/restore view state after each change of `input`. The library saves/restores view state (if `saveViewState` is provided) on [mount](https://github.com/suren-atoyan/monaco-react/blob/master/src/Editor/Editor.js#L128)/[unmount](https://github.com/suren-atoyan/monaco-react/blob/master/src/Editor/Editor.js#L201) of the editor and [every time when `path` is being changed](https://github.com/suren-atoyan/monaco-react/blob/master/src/Editor/Editor.js#L70) (for [multi-model-editor](https://github.com/suren-atoyan/monaco-react#multi-model-editor)).

**Comment by Janpot** [comment]
@suren-atoyan I'm not sure I understand, did you try the [first snippet](https://codesandbox.io/s/multi-model-editor-forked-pir178?file=/src/MyCodeEditor.js)? How would you update the `MyCodeEditor` component to preserve the cursor position?

**Comment by mann1996** [comment]
I am having same issue. Did you resolve it?

**Comment by Bonfims** [comment]
Hey, i having same issue and im using this work around:

```jsx
import * as React from 'react';
import MonacoEditor from '@monaco-editor/react';

function _Editor ({ data, updateData }){
    // ... editor ref
    const ref = React.useRef(null);
    // ... cursor position
    const [position, setPosition] = React.useState(null);

    React.useEffect(() => {
        ref?.current?.setPosition({
            ...position,
            column: position.column + 1 
            // ... not the best way, not work with copy paste. 
            // ... I wish we could use the method `getLineLastNonWhitespaceColumn` from API
        }); 
    }, [position])

    return (
        <MonacoEditor 
            language="json"
            value={data}
            onChange={updateData}
            onMount={(editor) => ref.current = editor}
        />
    )
}
```

And works fine, i can keept the cursor position on current data updates.

Any one know how can i access `Api methods` like described in [monaco-editor docs](https://microsoft.github.io/monaco-editor/docs.html#interfaces/editor.ITextModel.html#getLineLastNonWhitespaceColumn)
