### ISSUE TITLE
TypeError: Cannot read property 'getModeId' of null

### ISSUE THREAD

**Issue by IamFonky** [suren-atoyan/monaco-react#37]
Hello!

I often get this error from the editor when i use my own schema.

I used to dispose models before creating a new editor.
Can it be related with this?
Should I dispose models and editor or you're allready doing that in your Editor component?

I found out [a related issue](https://github.com/Microsoft/monaco-editor/issues/1254) but it seem that the problem has been corrected long ago.

![image](https://user-images.githubusercontent.com/25899984/69130417-c7278800-0ab0-11ea-97f1-30f68fdb83b6.png)

**Comment by SurenAt93** [comment]
Hello!

Can I ask you to make a reproducible snippet with the problem (f.e. in codesandbox)? It will help me to find the issue quicker.

Thank you!

**Comment by IamFonky** [comment]
I tried but it's very difficult to reproduce it in a simple example. The call stack makes no sense at all, referring to components that never use monaco-editor.
I'll will keep investigate and give you feedbacks when I understand better from where this error is coming.
Thank you for your quick answer by the way :)

**Comment by SurenAt93** [comment]
With pleasure. Let me know if something will be revealed.

**Comment by hemavidal** [comment]
I've got a cross-origin error:
```
FROM ErrorBoundary:  Error: A cross-origin error was thrown. React doesn't have access to the actual error object in development.
```
```
TypeError: Cannot read property 'getModeId' of null
    at cdn.jsdelivr.net/npm/monaco-editor@0.18.1/min/vs/language/css/cssMode.js:7
```

**Comment by hemavidal** [comment]
I think this will be a security breach if you load the content from **cdn.jsdelivr.net**

https://github.com/SurenAt93/monaco-react/search?q=cdn.jsdelivr.net&unscoped_q=cdn.jsdelivr.net

**Comment by SurenAt93** [comment]
Hello @hemavidal,

hmmm, cross-origin? can I ask you to make a reproducible snippet with the problem (f.e. in codesandbox)? It will help me to find the issue quicker.

Thank you!

**Comment by hemavidal** [comment]
My bad! I've made some changes and is working fine.
Thanks to build this project.... seems to be easier to configure than react-monaco-editor

**Comment by IamFonky** [comment]
@hemavidal

**Comment by suren-atoyan** [comment]
> Hello!
> 
> I often get this error from the editor when i use my own schema.
> 
> I used to dispose models before creating a new editor.
> Can it be related with this?
> Should I dispose models and editor or you're allready doing that in your Editor component?
> 
> I found out [a related issue](https://github.com/Microsoft/monaco-editor/issues/1254) but it seem that the problem has been corrected long ago.
> 
> ![image](https://user-images.githubusercontent.com/25899984/69130417-c7278800-0ab0-11ea-97f1-30f68fdb83b6.png)

You don't need to dispose them, I am already doing it in a component.

**Comment by IamFonky** [comment]
Hey thank you for your answer I missed it!
Great job :+1:
