### ISSUE TITLE
Editor loads the first time, but shows blank screen after the second load

### ISSUE THREAD

**Issue by everdrone** [suren-atoyan/monaco-react#371]
**Describe the bug**
When using the editor in react-router-dom 6 from electron, the first load is successful but changing route and going back to the editor it shows only the empty container div.

**To Reproduce**

1. Visit https://codesandbox.io/s/monaco-webpack-react-7wqo3q
2. Navigate to Editor (editor loads normally)
3. Navigate to Home
4. Go back to Editor (error happens here)

I'm not able to reproduce inside codesandbox because the `loader` fails for some reason (uncomment lines in `Component.tsx`)

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help to explain your problem.

**Desktop (please complete the following information):**
 - OS: macOS 12.3.1
 - Browser Electron
 - Version 18.2.0

**Additional context**
I'm using `electron-forge`, `monaco-editor-webpack-plugin` and `typescript`.

**Comment by jo0ger** [comment]
I have same problem;

**Comment by suren-atoyan** [comment]
@everdrone @jo0ger could you please check the latest version?

**Comment by everdrone** [comment]
I'm getting:
```
Editor.js?c25a:53 Monaco initialization: error: Error: ENOENT: no such file or directory, open 'https:/cdn.jsdelivr.net/npm/monaco-editor@0.33.0/min/vs/editor/editor.main.js'
eval @ Editor.js?c25a:53
Promise.catch (async)
eval @ Editor.js?c25a:53
invokePassiveEffectCreate @ react-dom.development.js?f731:23487
callCallback @ react-dom.development.js?f731:3945
invokeGuardedCallbackDev @ react-dom.development.js?f731:3994
invokeGuardedCallback @ react-dom.development.js?f731:4056
flushPassiveEffectsImpl @ react-dom.development.js?f731:23574
unstable_runWithPriority @ scheduler.development.js?c398:468
runWithPriority$1 @ react-dom.development.js?f731:11276
flushPassiveEffects @ react-dom.development.js?f731:23447
eval @ react-dom.development.js?f731:23324
workLoop @ scheduler.development.js?c398:417
flushWork @ scheduler.development.js?c398:390
performWorkUntilDeadline @ scheduler.development.js?c398:157
```

Could be electron's CSP? Currently it's set to `default-src * 'unsafe-eval' 'unsafe-inline'`

**Comment by everdrone** [comment]
My bad, wasn't calling the loader properly 😁

Seems to be working smoothly now! Thank you so much for the fast reply!
