### ISSUE TITLE
Cursor position is not restored

### ISSUE THREAD

**Issue by vasilev-alex** [suren-atoyan/monaco-react#372]
**Describe the bug**

The cursor position is not restored when you switch files.

**To Reproduce**

1. You can open the [demo](https://codesandbox.io/s/multi-model-editor-kugi6?file=/src/App.js) which I found in your Readme file
2. Put a cursor in any position
3. Open another file by clicking the button
4. Go back and see the cursor is lost

Or, please add a minimal code snippet to reproduce the issue, for example in [codesandbox](https://codesandbox.io/).

**Expected behavior**
The cursor doesn't change the position and visible

**Screenshots**
If applicable, add screenshots to help to explain your problem.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser chrome
 - Version 4.4.4

**Additional context**
The cursor position is not preserved event when `saveViewState` is passed as prop

**Comment by suren-atoyan** [comment]
When you click a button editor loses the focus. You should manually focus the editor after file change. Check [this](https://codesandbox.io/s/multi-model-editor-kugi6?file=/src/App.js).
