### ISSUE TITLE
GET https://cdn.jsdelivr.net/npm/monaco-editor@0.25.0/min/vs/loader.js net::ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by kzcPo** [suren-atoyan/monaco-react#377]
```
index.js:70          GET https://cdn.jsdelivr.net/npm/monaco-editor@0.25.0/min/vs/loader.js net::ERR_CONNECTION_TIMED_OUT
```

![image](https://user-images.githubusercontent.com/16077203/170495421-57b6f6b3-4c63-4119-a9f2-93334f55ad26.png)

**Comment by CYLpursuit** [comment]
I crashed into this proplem, too. His official example has the same problem, wait and see.

**Comment by kzcPo** [comment]
> I crashed into this proplem, too. His official example has the same problem, wait and see.
I finally found the solution through the official [documents](https://github.com/suren-atoyan/monaco-react#use-monaco-editor-as-an-npm-package)，use monaco-editor as an npm package
```
import * as monaco from "monaco-editor";
import { loader } from "@monaco-editor/react";

loader.config({ monaco });

// ...
```

**Comment by suren-atoyan** [comment]
@CYLpursuit @kzcPo where are you located? I guess you have issues with `https://cdn.jsdelivr.net` from your country. Anyway, you can [configure](https://github.com/suren-atoyan/monaco-react#loader-config) the loader to import it from other resources. For example:

```js
import { loader } from "@monaco-editor/react";

loader.config({ paths: { vs: "https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.33.0/min/vs/" } });
```

**Comment by XueMeijing** [comment]
> 

thank u a lot , this url seems faster than jsdlivr ,  but just a little. It still costs 44 seconds without a VPN proxy.
![image](https://user-images.githubusercontent.com/35559153/188844655-6592f74c-92f7-46e9-b834-09286c8339c7.png)

As a Chinese im realy sad about the Great Fire Wall, angry about the China state. People have no freedom

**Comment by kzcPo** [comment]
你好，我已经收到邮件！

**Comment by cwtuan** [comment]
> ```js
> 
> loader.config({ paths: { vs: "https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.33.0/min/vs/" } });
> ```

After change to this cdn domain, there's a error:
![image](https://user-images.githubusercontent.com/3455798/210392041-7f5b1888-2ce7-4c19-8c64-b370af71653c.png)

**Comment by suren-atoyan** [comment]
> ```js
> https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.33.0/min/vs/
> ```

Seems you have a typo. It should be `https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.33.0/min/vs/language/json/jsonWorker.js` not `https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.33.0/min/v/vs/language/json/jsonWorker.js`; there is an additional `v` before `vs` in your example

**Comment by BoLan6180** [comment]
> > ```js
> > loader.config({ paths: { vs: "https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.33.0/min/vs/" } });
> > ```
> 
> After change to this cdn domain, there's a error: ![image](https://user-images.githubusercontent.com/3455798/210392041-7f5b1888-2ce7-4c19-8c64-b370af71653c.png)

Removing the last slash from `https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.33.0/min/vs/` and using `https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.33.0/min/vs` instead.
