### ISSUE TITLE
Command Palette Customization

### ISSUE THREAD

**Issue by StanimalTheMan** [suren-atoyan/monaco-react#379]
**Is your feature request related to a problem? Please describe.**
Command palette upon pressing f1 is small.  Users might not even be able to tell that they can scroll.

**Describe the solution you'd like**
Easy way to display more rows, customization

**Describe alternatives you've considered**
Tried looking into the css

**Additional context**

**Comment by suren-atoyan** [comment]
similar issues should be referred to the base package [microsoft/monaco-editor](https://github.com/microsoft/monaco-editor/issues) (not React wrapper)
