### ISSUE TITLE
Issues to set Model Markers

### ISSUE THREAD

**Issue by paillave** [suren-atoyan/monaco-react#38]
how to access `setModelMarkers`?
The only way I found to access it was to add the reference to the package `monaco-editor` and to call it the following way:

```typescript
import * as monacoEditor from "monaco-editor/esm/vs/editor/editor.api";
/// blabla
monacoEditor.editor.setModelMarkers(myEditor.getModel(), "ScriptEditor", []);
```
the pb is that from the moment I make an actual use of monacoEditor.editor in the code, the editor doesn't behave correctly anymore: ctrl+arrow doesn't work, syntaxic coloration doesn't work, autocomplete doesn't work...

I believe that the import overrides some calls that are done in your version your are exposing, and ruins the behavior. I assume this because even if I make the following I still have the pb:
```typescript
if(false){
    // this will never be called, but still, the compiler feels compelled to integrate 
    // the code in the final bundle, and that causes the issue as well
    monacoEditor.editor.setModelMarkers(myEditor.getModel(), "ScriptEditor", []);
}
```

here the working/failling example: https://codesandbox.io/s/funny-sara-kbws9?fontsize=14&hidenavigation=1&theme=dark

FYI, I would need to access some types that are necessary, like `IStandaloneCodeEditor`, or `MarkerSeverity` but it is as well impossible to access it. I think you should expose the full api of monaco, or at least a wrapper for most common features.

**Comment by paillave** [comment]
Actually I see that somehow, you expose some apis... But I don't see anywhere in the documention how/when to make the call to `monaco.init()`

**Comment by SurenAt93** [comment]
Hello @paillave.

To access `setModelMarkers` you need to access the monaco instance.

- to see how you can access to monaco instance read [here](https://github.com/SurenAt93/monaco-react#monaco-instance)
to say short:

```js
import { monaco } from '@monaco-editor/react';

monaco
  .init()
  .then(monacoInstance => console.log(monacoInstance.editor.setModelMarkers);
```
- [similar issue](https://github.com/SurenAt93/monaco-react/issues/31)
- about types I agree, I need to expose all possible types; I'll try to do it in next version

I think it helps. Thank you!

**Comment by paillave** [comment]
Thanks, @SurenAt93 I figured it out, but I still wanted to know about types. At my side I copied the content of the .d.ts of monaco and tweaked it to make it a normal .ts file with interfaces.
Everything seems to work, but... the label of the message is not shown. I suppose there might a pb with a worker.
FYI it works very well on the monaco playground using this script:
```typescript
function createDependencyProposals() {
    return [
        {
            label: 'class',
            kind: monaco.languages.CompletionItemKind.Snippet,
            documentation: "Class with constructor.",
            insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
            insertText: "public class ${1:MyClass}\n{\n\tprivate int ${2:myProp};\n\tpublic ${1}(int ${2})\n\t{\n\t\tthis.${2} = ${2};\n\t}\n}"
        },
    ];
}


monaco.languages.registerCompletionItemProvider('csharp', {
    provideCompletionItems: function (model, position) {
        return {
            suggestions: createDependencyProposals(),
        };
    }
});

var editor = monaco.editor.create(document.getElementById("container"), {
    value:
        `namespace MyNamespace
{
}`,
    language: "csharp"
});



setTimeout(function () {
    monaco.editor.setModelMarkers(editor.getModel(), 'test', [{
        startLineNumber: 8,
        startColumn: 18,
        endLineNumber: 8,
        endColumn: 24,
        message: "a message",
        severity: monaco.MarkerSeverity.Error,

    }])
}, 1000);
```

**Comment by a33nazarenko** [comment]
@SurenAt93 can I use setModelMarkers in your ControlledEditorComponent, like on change event ? 
because when i use monaco instance, I have  init another editor on the page.

**Comment by SurenAt93** [comment]
Hello @paillave, I run your script in monaco playground and get this kind of result.  
<img width="1680" alt="Screen Shot 2019-12-24 at 19 58 44" src="https://user-images.githubusercontent.com/13118722/71419239-de492f00-2687-11ea-95fb-3d93eb4d9813.png">

**Comment by SurenAt93** [comment]
After I run it with @monaco-editor/react, the result is
<img width="1680" alt="Screen Shot 2019-12-24 at 20 00 26" src="https://user-images.githubusercontent.com/13118722/71419318-45ff7a00-2688-11ea-879f-db7f7acf743d.png">

Check it [here](https://codesandbox.io/s/distracted-goodall-se5sf?fontsize=14&hidenavigation=1&theme=dark)

**Comment by SurenAt93** [comment]
so, from point of view of messages, it looks the same; isn't it?

**Comment by alessonsouza** [comment]
Is anybody here know how to use "setModelMarkers" now, in the version 4.4.4 ??

**Comment by suren-atoyan** [comment]
@alessonsouza you should be able to use it as before. Check [this](https://codesandbox.io/s/gracious-murdock-u1m0yn?file=/src/App.js)

**Comment by Jared-Dahlke** [comment]
this is not working. surprise there is not a first class way to set markers

**Comment by Ekrekr** [comment]
I'm on 4.7.0, and this works for me. Example:

```ts
import { Editor, Monaco } from "@monaco-editor/react";
import * as monaco from "monaco-editor";
import { useRef } from "react";

export function MyComponent() {
  const editorRef = useRef<monaco.editor.IStandaloneCodeEditor | null>(null);
  const monacoRef = useRef<Monaco | null>(null);

  const handleEditorDidMount = (
    mountedEditor: monaco.editor.IStandaloneCodeEditor,
    monaco: Monaco
  ) => {
    editorRef.current = mountedEditor;
    monacoRef.current = monaco;
    monacoRef.current.editor.setModelMarkers(
      editorRef.current?.getModel()!,
      "my-language",
      {
        severity: monaco.MarkerSeverity.Error,
        message: "someMessage",
        startLineNumber: 0,
        startColumn: 0,
        endLineNumber: 10,
        endColumn: 10,
      }
    );
  };

  return (
    <Editor
      language={"my-language"}
      onMount={handleEditorDidMount}
    />
  );
}
```

I think the confusion above comes from using a `monaco` from the `import * as monaco from "monaco-editor";` instead of using the monaco **instance** available from the mount methods. Having the monaco ref solves this by making it easily accessible in the component for re-use later.
