### ISSUE TITLE
Loading monaco from node_modules throws an `Unexpected usage` error

### ISSUE THREAD

**Issue by hpohlmeyer** [suren-atoyan/monaco-react#380]
**Describe the bug**

When trying to load monaco from node_modules in vite [as descibed in the readme](https://github.com/suren-atoyan/monaco-react#use-monaco-editor-as-an-npm-package), an `Uncaught Error: Unexpected usage` error is logged to the console and intellisense does not work.

**To Reproduce**

1. Go to the [StackBlitz reproduction](https://stackblitz.com/edit/vitejs-vite-okyfsk?file=src/App.tsx)
2. Click on "Open in new window" in the top right
3. Open the devtools and see the error being logged

**Expected behavior**
No error should occur and the editor should load from node_modules

**Screenshots**
<img width="1559" alt="image" src="https://user-images.githubusercontent.com/6564077/172581356-b00845ed-f2a7-4dd1-b4cc-c72f0962e6c1.png">

**Desktop (please complete the following information):**

**Additional context**
The error also occurs if I do not implement `getWorker` and just use `loader.config`, e.g.
```ts
import Editor, { loader } from "@monaco-editor/react";
import * as monaco from "monaco-editor";

loader.config({ monaco })
```

**Comment by suren-atoyan** [comment]
@hpohlmeyer I've just checked and it works well in a new window. Maybe it was an issue related to StackBlitz.

Feel free to re-open this issue if it still exists.

**Comment by hpohlmeyer** [comment]
Hey @suren-atoyan thanks for looking at it. I have tried it in Chrome and Firefox. Chrome works fine, but in Firefox I still the the error.

<img width="861" alt="image" src="https://user-images.githubusercontent.com/6564077/180738364-97a907af-7b91-41a3-a90b-fd4d02435615.png">

Firefox 102.0.1
Mac OS 12.4

**Comment by hpohlmeyer** [comment]
I have looked into the problem again. The reason for the error in Firefox is the missing support for "module workers".

Vite seems to compile that away in production, but relies on native browser support for that feature in dev mode.

> note during dev this relies on browser native support and currently only works in Chrome, but for the production build it is compiled away.
> — https://vitejs.dev/guide/features.html#web-workers

__Vite links__
- https://github.com/vitejs/vite/issues/8621
- https://github.com/vitejs/vite/issues/4586

__Firefox links__
- https://bugzilla.mozilla.org/show_bug.cgi?id=1247687
- https://caniuse.com/mdn-api_worker_worker_ecmascript_modules

What’s confusing me about the `monaco-editor` error message is, that it seems to try to fall back to loading the code in the main thread, which does support es modules and should be able to load the worker code just fine.
