### ISSUE TITLE
How to use Web Worker in custom language

### ISSUE THREAD

**Issue by langhaoabcd** [suren-atoyan/monaco-react#381]
qution:
When I use a custom language,self.MonacoEnvironment getworker does not recognize the language label

![image](https://user-images.githubusercontent.com/39892654/172774519-13480e68-51a6-4e80-b3a2-cc04b52972a4.png)

What should I do?

demo
https://stackblitz.com/edit/vitejs-vite-eb2xqq?file=src/App.tsx

**Comment by josealvarez97** [comment]
Your example was just so amazing and useful! A life saver!
