### ISSUE TITLE
cannot find module 'monaco-editor' testing with testing library

### ISSUE THREAD

**Issue by eduardopcaj** [suren-atoyan/monaco-react#383]
**Describe the bug**
Im using this fantastic library for weeks, but last week i decided to add it to my application bundle instead use cdn resources. The problem is when i have run my testing script, I saw that a lot of tests are failing by the same reason: 

"Cannot find module 'monaco-editor' from   'componentPath....'"

I have tried some solucions, like add "monaco-editor" to moduleNameMapper jest.config, but without success. I also have tried to add monaco-editor-webpack-plugin to my webpack.config, but without changes in the testing error

What is diconcerting me is that in dev and production bundle all works fine, the error only happens in testing environment.

Can you expose a global solution for that problem?

**Expected behavior**
I can import 'monaco-editor' library without problems in testing environments

**Desktop (please complete the following information):**
 - OS: macOS Monterrey
 - Browser chrome
 - Version 28

**Additional context**

**Comment by suren-atoyan** [comment]
hmm, @eduardopcaj we've never faced this issue. please share your test file and also the file where you use this library

**Comment by eduardopcaj** [comment]
> hmm, @eduardopcaj we've never faced this issue. please share your test file and also the file where you use this library

Hi @suren-atoyan I have solved this problem placing the  code snippet on my main.tsx, in the root of the application. But now I have another problem. 
I have this code on the main.tsx: 
````
import { loader } from '@monaco-editor/react';
import * as monaco from 'monaco-editor';

loader.config({ monaco });
````

But now the editor.worker is not running every time that the value of the code-editor changes, only runs the first time that the editor is rendered


![image](https://user-images.githubusercontent.com/88657622/174848085-f76dfca0-51b4-460d-913e-dca78e338a93.png)

When monaco-editor resources comes from cdn every time that value changes, this workerMain is called 

![image](https://user-images.githubusercontent.com/88657622/174848792-2e23d076-24e7-4fcd-b2f5-59cefaf8ab13.png)

**Comment by rishi-habu** [comment]
Solved this issue by adding `moduleNameMapper` to the jest config. I have my jest config added to my `package.json`.
Ref,
```
"jest": {
  "moduleNameMapper": {
    "monaco-editor": "<rootDir>/node_modules/@monaco-editor/react"
  }
}
```

**Comment by RishikeshVedpathak** [comment]
Solved this issue by adding `moduleNameMapper` to the jest config. I have my jest config added to my `package.json`.
Ref,
```
"jest": {
  "moduleNameMapper": {
    "monaco-editor": "<rootDir>/node_modules/@monaco-editor/react"
  }
}
```
