### ISSUE TITLE
Incorrect calculation of line width when using custom fonts

### ISSUE THREAD

**Issue by oriooctopus** [suren-atoyan/monaco-react#384]
https://codesandbox.io/s/monaco-editor-react-forked-nmk30v?file=/src/index.js

**Expected behavior**
Both examples should support text going to the end of the line

**Comment by suren-atoyan** [comment]
@oriooctopus this type of issue should be addressed to the [original library](https://github.com/microsoft/monaco-editor)

**Comment by goliney** [comment]
You need to call [`monaco.editor.remeasureFonts()`](https://microsoft.github.io/monaco-editor/docs.html#functions/editor.remeasureFonts.html) after the font is loaded and applied.
