### ISSUE TITLE
Conflict with Spotify SDK 

### ISSUE THREAD

**Issue by miroshSa** [suren-atoyan/monaco-react#386]
**Describe the bug**
When trying to load the Spotify SDK script after monaco Editor component is rendered it invokes an error `TypeError: r.__extends is not a function`
If you try to load Spotify SDK script on the page before rendering monaco Editor component everything is working on

**To Reproduce**

1. Go to any page with Editor component 
2. Invoke in console:
` const script = document.createElement('script');

      script.id = 'spotify-player';
      script.type = 'text/javascript';
      script.async = false;
      script.defer = true;
      script.src = 'https://sdk.scdn.co/spotify-player.js';
document.head.appendChild(script);`

**Expected behavior**
the Spotify script loads correctly

**Screenshots**
If applicable, add screenshots to help to explain your problem.

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: Chrome
 - Version 102.0.5005.115 (Official Build) (arm64)

**Comment by suren-atoyan** [comment]
@miroshSa I believe the issue is AMD's `define` function conflict - between monaco's custom AMD implementation and Spotify's one. Could you please check [this](https://github.com/suren-atoyan/monaco-react/issues/248#issuecomment-846581961) discussion?

**Comment by miroshSa** [comment]
@suren-atoyan provided solution is works. thanks
