### ISSUE TITLE
Cann't display different theme or language with multiple editor in the same time

### ISSUE THREAD

**Issue by 14glwu** [suren-atoyan/monaco-react#389]
**Describe the bug**
I want to display multiple editor  with different theme or language in the same time
But the style among theme will affect each other. 

**To Reproduce**
demo: https://codesandbox.io/s/multi-model-editor-forked-jo05ud?file=/src/App.js

**Expected behavior**
can show different theme or language in mulitple editor  in the same time

**Screenshots**
![image](https://user-images.githubusercontent.com/26249572/181678931-70b2b85d-521d-46f1-a1be-844c8415b7af.png)

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [chrome]
 - Version [4.0.4]

**Comment by suren-atoyan** [comment]
having different themes in the editors that are being rendered at the same time isn't supported. check [this](https://github.com/microsoft/monaco-editor/issues/338#issuecomment-274837186)

**Comment by Rahul5546-X** [comment]
@suren-atoyan , I'm using two different editors(react components), but I'm still not able to render them with different themes.

// First component
`<MonacoEditorComp
	height="40vh"
	theme="vs-dark"
	language="tsx"
/>`

// Second component
`<MonacoEditorComp
	height="40vh"
	theme="light"
	language="typescript"
/>`

Inside my MonacoEditorComp, if language is tsx(first case I create a custom theme and set it using defineTheme and setTheme). The same custom theme is being applied to the Second Component.

I have a helper function which decide theme based on the language. If I log it then in first case it logs 'customTheme' and in second case it logs 'light'. But in browser the theme is still same for both the editors.

**Comment by suren-atoyan** [comment]
> [@suren-atoyan](https://github.com/suren-atoyan) , I'm using two different editors(react components), but I'm still not able to render them with different themes.
> 
> // First component `<MonacoEditorComp height="40vh" theme="vs-dark" language="tsx" />`
> 
> // Second component `<MonacoEditorComp height="40vh" theme="light" language="typescript" />`
> 
> Inside my MonacoEditorComp, if language is tsx(first case I create a custom theme and set it using defineTheme and setTheme). The same custom theme is being applied to the Second Component.
> 
> I have a helper function which decide theme based on the language. If I log it then in first case it logs 'customTheme' and in second case it logs 'light'. But in browser the theme is still same for both the editors.

@Rahul5546-X it's a limitation on monaco-editor, check [this](https://github.com/microsoft/monaco-editor/issues/338#issuecomment-274837186)
