### ISSUE TITLE
Error: Hydration failed because the initial UI does not match what was rendered on the server.  See more info here: https://nextjs.org/docs/messages/react-hydration-error

### ISSUE THREAD

**Issue by iUnstable0** [suren-atoyan/monaco-react#393]
**Describe the bug**
Next.JS Shows this error
```
Error: Hydration failed because the initial UI does not match what was rendered on the server.

See more info here: https://nextjs.org/docs/messages/react-hydration-error
```

This is my code

```js
if (typeof window !== "undefined") {
    loader.init().then(async (monaco) => {
        //set theme and stuff
    })
}
```

![Screenshot 2022-08-03 at 10 51 35 PM](https://user-images.githubusercontent.com/46888825/182652949-3fb63be4-543b-4075-b0d7-b90db3fe7b20.png)

 - OS: Ubuntu Server 20.04.4 LTS
 - Browser: Safari
 - Version: Latest safari version (MacOS Ventura Public Beta 2)

**Comment by suren-atoyan** [comment]
you should use something like [this](https://github.com/vercel/next.js/discussions/35773#discussioncomment-2485078) instead of `if (typeof window !== "undefined") {`. Read more [here](https://nextjs.org/docs/messages/react-hydration-error)
