### ISSUE TITLE
How to avoid duplicate actions with monaco's registerCodeActionProvider method?

### ISSUE THREAD

**Issue by omniphx** [suren-atoyan/monaco-react#394]
I'm trying to use monaco's `registerCodeActionProvider` to provide "Quick Fix" actions on line markers. The register function works fine but everytime the component is unmounted/re-mounted a duplicate action is registered/created.

I'm trying to register this action with the `onMount` prop. Is there a better way to register this type of thing?

**To reproduce:**
1. Open: https://codesandbox.io/s/registercodeactions-evbxt6?file=/src/App.js
2. Click "Lightbulb" and see "Quick fix" as an option
3. Click "Hide"
4. Click "Show"
5. Click "Lightbulb" again and will now see two "Quick fix" options

**Comment by suren-atoyan** [comment]
hi @omniphx 👋 

`registerCodeActionProvider` returns a disposable object.

<img width="881" alt="Screen Shot 2022-08-10 at 09 43 26" src="https://user-images.githubusercontent.com/13118722/183824510-4e97912d-8f7f-4bfa-ac2e-05857c07f519.png">

Check it [here](https://microsoft.github.io/monaco-editor/api/modules/monaco.languages.html#registerCodeActionProvider).

So, you can keep that disposable object and dispose it on unmount for example.

Check [this](https://codesandbox.io/s/registercodeactions-forked-diu7b2?file=/src/App.js).

**Comment by omniphx** [comment]
Awesome, that worked like a charm! Thanks
