### ISSUE TITLE
How do I serve Monaco editor's loader.js and its dependencies on localhost in my react build

### ISSUE THREAD

**Issue by raseshsingh** [suren-atoyan/monaco-react#401]
**Describe the bug**
I am using Monaco [Monaco Editor](https://www.npmjs.com/package/@monaco-editor/react). After building and serving code on localhost, The Loader Script is loading from CDN.

![Screenshot](https://i.ibb.co/hmF5z8c/image.png)

How can I include the files in the build?

**To Reproduce**

Steps to reproduce:
1. Serve the build on localhost
2. Chrome's network tab
3. Loader.js is loading from CDN.

**Expected behavior**
Every resource should be served locally. If i don't have the internet connection and i serve the build locally then i wont be able to use the app.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Any
 - Version ^4.3.1

**Comment by suren-atoyan** [comment]
please check [loader-config](https://github.com/suren-atoyan/monaco-react#loader-config)

**Comment by raseshsingh** [comment]
Thanks
