### ISSUE TITLE
can't make the package to use monaco-editor@0.34.0

### ISSUE THREAD

**Issue by mbui0327** [suren-atoyan/monaco-react#403]
I am running `monaco-react` with `nextjs`. Everything seems to be running fine except for the fact that `monaco-react` is using `monaco-editor` v. 0.33.0 while I would like it to use 0.34.0 instead. I have installed v 0.34.0 locally but this is not being used. 
I can confirm that the package is loaded from a CDN see the attached pic:
<img width="251" alt="Screen Shot 2022-09-04 at 6 41 11 PM" src="https://user-images.githubusercontent.com/34329345/188344222-4a386e10-cffc-45ab-b6ea-e111b4220eeb.png">

**Comment by mbui0327** [comment]
Turn out it has to do with the version in this file `@monaco-editor/loader/lib/es/config/index.js`. Is there any change we can update this to `0.34.0`?

**Comment by suren-atoyan** [comment]
@mbui0327 use [config](https://github.com/suren-atoyan/monaco-react#loader-config)

```js

import { loader } from '@monaco-editor/react';

loader.config({ paths: { vs: 'https://cdn.jsdelivr.net/npm/monaco-editor@0.34.0/min/vs' } });

```
