### ISSUE TITLE
Support monaco-language client compatibility

### ISSUE THREAD

**Issue by wudstrand** [suren-atoyan/monaco-react#405]
I am trying to integrate the [monaco-language client](https://github.com/TypeFox/monaco-languageclient) library with this editor so I can connect an [lsp server for python](https://github.com/python-lsp/python-lsp-server). The ESM versions for this library is behind the language-client's making them [incompatible](https://github.com/TypeFox/monaco-languageclient/issues/412#issuecomment-1225365888). 

Is there a work around for this? If not can the ESM version of this library be upgraded so it can work with other external libraries (i.e. the [monaco-language client](https://github.com/TypeFox/monaco-languageclient))?

**Comment by kaisalmen** [comment]
Hi @wudstrand you are referring to `@monaco-editor/react` when you say "this editor", right?

**Comment by suren-atoyan** [comment]
@wudstrand could you please try [this](https://github.com/suren-atoyan/monaco-react#use-monaco-editor-as-an-npm-package)?

**Comment by wudstrand** [comment]
We tried it and it worked. Thank you.

**Comment by suren-atoyan** [comment]
hey @wudstrand could you please share your experience in your other [PR](https://github.com/suren-atoyan/monaco-react/issues/400)? It would help lots of people. This is a pretty popular topic now. I would appreciate it if you could find some time to put together a reproducible example. Thank you!

**Comment by chaitanya71998** [comment]
hey @wudstrand can you share what steps you have followed and made language servers work. 
if possible can you share a code sandbox

**Comment by boan-anbo** [comment]
I think @wudstrand already shared it [here](https://github.com/wudstrand/lsp-ingration-react-monaco-editor)
