### ISSUE TITLE
Preventing onChange Event on programmatic value change

### ISSUE THREAD

**Issue by v27855** [suren-atoyan/monaco-react#411]
According to [the fixing](https://github.com/suren-atoyan/monaco-react/issues/91), I believe that is a bug and it showed again 

Version:
@monaco-editor/react: "^4.4.6",

Reproduce:
[code fork](https://codesandbox.io/s/monaco-editor-react---controlled-editor-2-forked-ev823r?file=/src/index.js)

Expected behavior:
onChange Event only triggered when user update the text in the editor
instead of being triggered by a programmatic change

**Comment by LaamGinghong** [comment]
I had the same problem too.

**Comment by n8agrin** [comment]
We ran into this as well. Seems to be something in the 4.4.6 release. 4.4.5 works for us.

**Comment by blackerer** [comment]
Versions before 4.0.0 have been repaired, but later versions have reappeared

**Comment by blackerer** [comment]
@suren-atoyan

**Comment by blackerer** [comment]
Versions before 4.0.0 have been fixed, but later versions have reappeared @suren-atoyan

**Comment by Nishchit14** [comment]
My application is breaking due to this. any help? @suren-atoyan

**Comment by willdady** [comment]
When can we expect the next version? I just got stung by this (again) because I _accidentally_ upgraded to the latest version.

**Comment by suren-atoyan** [comment]
I'll try to organize it this week

**Comment by Nishchit14** [comment]
That wold be a great help, thank you @suren-atoyan

**Comment by willdady** [comment]
Any update on this @suren-atoyan?

**Comment by suren-atoyan** [comment]
@willdady @Nishchit14 @blackerer @n8agrin @LaamGinghong @v27855 Hi everyone 👋 Sorry for being late on this one and thank you for your patience. The issue is fixed, you can try the latest version (v4.5.0) 🥳 🎉

**Comment by suren-atoyan** [comment]
let me know how it works

**Comment by Nishchit14** [comment]
Thank you @suren-atoyan for fixing it. I'll upgrade it soon and share my feedback.

**Comment by kasliwalshreyas** [comment]
@suren-atoyan 

I am encountering an issue while developing a collaborative code editor feature. Here's the problem: when person A makes a change, I use sockets to trigger an event that sends this change to person B. The change is applied using `monaco.editor.getModels()[0].applyEdits(e.changes)`, where e represents the aforementioned event.

My concern is whether this action should be classified as a programmatic change or not. Currently, the event triggered by the change ends up causing the same change to be sent back to person A, resulting in an infinite loop scenario.
