### ISSUE TITLE
callback inside onMount function is caching?

### ISSUE THREAD

**Issue by Angryman18** [suren-atoyan/monaco-react#412]
**Describe the bug**

**To Reproduce**

Or, please add a minimal code snippet to reproduce the issue, for example in [codesandbox](https://codesandbox.io/).

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help to explain your problem.

**Desktop (please complete the following information):**

**Additional context**
`writtenCode` changes whenever user edits on editor. but hitting ctrl + enter i want to run the (`executeCode` makes that api call) but i see everytime code changes and hitting ctrl + enter this callback function is taking the old code like what code was when the editor got mount. why is this? how to fix this issue. hitting ctrl + enter i want latest code run everytime

handleEditorMount the called on onMount

![Screenshot from 2022-10-08 09-37-06](https://user-images.githubusercontent.com/63530626/194687477-239d4dca-333d-4e21-9233-f530bf252580.png)

**Comment by suren-atoyan** [comment]
@Angryman18 you can find an answer to this [here](https://github.com/suren-atoyan/monaco-react/issues/328#issuecomment-1079967898) and [here](https://github.com/suren-atoyan/monaco-react/issues/277)
