### ISSUE TITLE
[@monaco-editor/react] formatDocument is not working

### ISSUE THREAD

**Issue by chandrashekhar-patil** [suren-atoyan/monaco-react#414]
I am trying to format the json text present in the Editor using editorDidMount method, but its not working when readOnly option is set as true. 

I am using @monaco-editor/react": "^3.2.1" 

PFA the code snippet. Any work around or suggestions will be helpful

```
  const editorDidMount = (_valueGetter: any, editor: any) => {
    if (editor) {
      setTimeout(function() {
        editor.getAction('editor.action.formatDocument').run();
      }, 300);
    }
  };
  
   <Editor
            language={props.language}
            value={props.data.payload || ''}
            height={'300px'}
            options={{
              readOnly: true,
              autoIndent: 'full',
              automaticLayout: true,
              minimap: {
                enabled: false,
              },
              wordWrap: 'on',
              formatOnPaste: true,
              formatOnType: true,
            }}
            editorDidMount={editorDidMount}
          />
```

**Comment by suren-atoyan** [comment]
it works [here](https://codesandbox.io/s/simple-usage-forked-8ldv98?file=/src/App.js)

**Comment by suren-atoyan** [comment]
@chandrashekhar-patil could you please create a reproducible snippet?

**Comment by chandrashekhar-patil** [comment]
Hi @suren-atoyan, Thanks for taking your time to review the issue. 
[here](https://codesandbox.io/s/monaco-editor-wmrsw1) is the reproducible snippet.  
The code snippet that you have created allows user to edit the json, To prevent that I have placed readOnly:true inside options prop., but the auto formatting is not working when I do that

**Comment by rainy789** [comment]
The following workaround works.
```
  const handleEditorMount = (editor) => {
    setTimeout(function () {
      editor
        .getAction('editor.action.formatDocument')
        .run()
        .then(() => editor.updateOptions({ readOnly: true }));
    }, 500);
  };
```

**Comment by chandrashekhar-patil** [comment]
Hi @rainy789, Thanks for the code snippet. It works!

**Comment by chandrashekhar-patil** [comment]
Closing the issue as @rainy789 answer solves the formatting issue of monacto-editor for readOnly option
