### ISSUE TITLE
Host all js and css files locally

### ISSUE THREAD

**Issue by SamTV12345** [suren-atoyan/monaco-react#419]
Because of the GDPR it is mandatory to inform the user if any other sources than the webserver are used to load files. The project unfortunately uses https://cdn.jsdelivr.net for delivering the files. Is there a solution to host all files locally?

**Comment by SamTV12345** [comment]
```javascript
import * as monaco from "monaco-editor";
import { loader } from "@monaco-editor/react";

loader.config({ monaco });
```
in main.tsx/index.tsx
Fixed it. But it's still weird that by default everything is loaded from cdn. The inverse would be more logically. By default everything is hosted locally and if someone decides to use a cdn this behaviour can be enabled.

**Comment by suren-atoyan** [comment]
@SamTV12345 we do use CDN by default to avoid having a need for an additional `webpack` plugin (which is a pain when you use CRA)

**Comment by yuicer** [comment]
> @SamTV12345 we do use CDN by default to avoid having a need for an additional `webpack` plugin (which is a pain when you use CRA)

so did there one way to use local es import within CRA ?

default CDN import will cause the global CDN script bad effect, it will can not be parsed as modules

**Comment by SamTV12345** [comment]
You can find a working version [here](https://github.com/SamTV12345/stackedit-react/blob/main/src/main.tsx). By the way consider moving to vite as it contains less boilerpackages and has a faster startup time.

**Comment by cwtuan** [comment]
if I want to deploy a website in a private cloud, is there any way to host all resource locally?

**Comment by cwtuan** [comment]
> ```js
> 
> loader.config({ monaco });
> ```

This doesn't work in next.js. Error:

```bash
index.js:702 Uncaught ReferenceError: navigator is not defined
    at eval (webpack-internal:///./node_modules/monaco-editor/esm/vs/base/browser/browser.js:122:19)
```

**Comment by SamTV12345** [comment]
What bundler are you using? Seems like the navigator api is not exposed.

**Comment by SamTV12345** [comment]
Please check out the [official docs](https://nextjs.org/docs/migrating/from-create-react-app#safely-accessing-web-apis) on how to access these apis with NextJS.

**Comment by cwtuan** [comment]
Currently, I copy all of monaco-editor files into my repo's `/static` directory. Then config like this:
```js
loader.config({ paths: { vs: "/static/vs" } });
```
It works in next.js.

**Comment by cwtuan** [comment]
@BrunoQuaresma Copy one by one from CDN manually

**Comment by suren-atoyan** [comment]
@cwtuan @BrunoQuaresma you shouldn't copy it manually from CDN, you can do something like this:

```bash
cp -R ./node_modules/monaco-editor/min/vs ./static
```

**Comment by cwtuan** [comment]
@suren-atoyan 
Yes, you're right. I have updated [solution](https://github.com/suren-atoyan/monaco-react/issues/419#issuecomment-1478846313) above.
