### ISSUE TITLE
Theming multiple editor instances: possible bug

### ISSUE THREAD

**Issue by cdolek** [suren-atoyan/monaco-react#429]
Hi,

I would like to be able to use separate themes for multiple editor instances on the same page, but for some reason, there is a collision. I am providing an example below, where the left editor should have a red background, and the one on the right should have a blue background as set by their custom themes (inherited from vs-dark.)

Is there anything I'm missing here?

https://codesandbox.io/s/monaco-editor-react-theming-c15dq8?file=/src/App.js

![Screen Shot 2022-12-09 at 1 13 54 PM](https://user-images.githubusercontent.com/174331/206766446-6d6c2592-7309-4a18-87e9-26849e55658b.png)

**Comment by suren-atoyan** [comment]
hi @cdolek 

it's not supported by `monaco-editor`. check [this](https://github.com/suren-atoyan/monaco-react/issues/389#issuecomment-1200067123) please

**Comment by cdolek** [comment]
Thanks, I wish it was supported!
