### ISSUE TITLE
Docs say "JSON" but the expected prop is "json"

### ISSUE THREAD

**Issue by ejfrancis** [suren-atoyan/monaco-react#432]
**Describe the bug**
The README says that a supported language is "JSON" but when passing the `defaultLanguage` prop it must be "json" for validation to work. This leads me to think that the README is incorrect.

**Comment by arop3nny** [comment]
I second this. Hit an issue where we were passing the prop as displayed in the README into the component but wondered why it never picked up the language. Turns out casing has to be lowercase.

**Comment by suren-atoyan** [comment]
<img width="1006" alt="Screen Shot 2022-12-23 at 10 43 50" src="https://user-images.githubusercontent.com/13118722/209286040-cfaf4a36-3d94-49a4-8151-c371f7f8e6b1.png">

If you are talking about this section then it says which languages are supported. A number of language names are listed here. The key word is "language name". So, a language name is `JavaScript` not `javascript`, it's `HTML` not `html`. These are the language names, not property names. You can find these lists in monaco-editor [website](https://microsoft.github.io/monaco-editor/) as well.

But if you think that's confusing, I can add a note that language prop should be lowercase.
