### ISSUE TITLE
unable to connect to java language server

### ISSUE THREAD

**Issue by chaitanya71998** [suren-atoyan/monaco-react#441]
Greetings,
Thanks for the awesome package. I was trying to connect to a java language server. I was using [eclipse/eclipse.jdt.ls](https://github.com/eclipse/eclipse.jdt.ls) and created server.
What are the steps to connect to a language server to editor.

**Comment by suren-atoyan** [comment]
hey @chaitanya71998 👋 Thanks for the feedback!

Please check [this](https://github.com/TypeFox/monaco-languageclient#monaco-editorreact).

**Comment by chaitanya71998** [comment]
@suren-atoyan 
The example worked. But, I found the files are creating over sever side, do you have any idea on how to show auto suggestions and implement the language server for this type of use case

**Comment by fanyuwei4** [comment]
> @suren-atoyan The example worked. But, I found the files are creating over sever side, do you have any idea on how to show auto suggestions and implement the language server for this type of use case ![Screenshot from 2023-01-06 21-25-50](https://user-images.githubusercontent.com/46353549/211049162-1da58cc5-b5f8-48c6-9b01-898714de4b2c.png)

can you give me your example code ? I really need this,thank you very much

**Comment by suren-atoyan** [comment]
@fanyuwei4 I don't have an example code. You should be able to do it with [monaco-languageclient](https://github.com/TypeFox/monaco-languageclient) - if you face any problems with language-server feel free to open an issue on their repo
