### ISSUE TITLE
Monaco.Editor is not the Monaco Editor

### ISSUE THREAD

**Issue by michaeleliot** [suren-atoyan/monaco-react#443]
**Describe the bug**
monaco.editor is not the editor of monaco

**To Reproduce**
```
export function MonacoEditor() {
    const monaco: Monaco = useMonaco();

    useEffect(() => {
        if (monaco) {
            console.log("Monaco Editor ", monaco.editor)
        }
    }, [monaco]);

    function handleEditorDidMount(editor, monaco) {
        console.log("Editor", editor)
    }
  return (
    <Editor
      height="90vh"
      theme="dark"
      language="markdown"
      value={"### Hello world"}
      onMount={handleEditorDidMount}
    />
  );

```

1. Run above example
2. Note the difference between monaco editor and editor

**Expected behavior**
Monaco.editor is the same as the editor of monaco.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox
 - Version: @monaco-editor/react: 4.4.7

**Additional context**

**Comment by suren-atoyan** [comment]
1. `editor` that you see in the `onMount` is the editor instance; the very instance you've just rendered. The type is [IStandaloneCodeEditor](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.IStandaloneCodeEditor.html). It's what `monaco.editor.create(...)` returns. It's the `editor` object in line 5 in [this](https://microsoft.github.io/monaco-editor/playground.html#creating-the-editor-editor-basic-options) example.

2. `monaco.editor` is the monaco editor namespace. [Here](https://microsoft.github.io/monaco-editor/api/modules/monaco.editor.html) it is.

=========

From a naming point of view, this library reflects the original `monaco-editor`'s naming. So, if you still find it confusing or incorrect, I would kindly ask you to open an issue in the original package.
