### ISSUE TITLE
Arrow folds not loading properly

### ISSUE THREAD

**Issue by ElinorW** [suren-atoyan/monaco-react#449]
**Describe the bug**
Adding `loader.config({ monaco });` to my code changes how the arrow fold look on the editor 

**Expected behavior**
The arrow folds should appear like this  
![image](https://user-images.githubusercontent.com/18407044/216560119-e178fff0-da05-4f4e-8960-67f6a7d19714.png)

**Screenshots**
Here's an example of how it appears once I add the `loader.config({monaco});` line
![image](https://user-images.githubusercontent.com/18407044/216559828-95a40391-bf63-4c62-92f8-9c12f1040f58.png)

**Additional context**
I am trying to move from using the CDN and instead just import it from node modules.
I am using:
```
"@monaco-editor/react": "4.4.6",
"monaco-editor": "0.34.1",
"monaco-editor-webpack-plugin": "7.0.1",
```

**Comment by Summer12130** [comment]
Hello, have you solved this problem? I am encountering the same issue and I think it may be due to the codicon font file not being properly imported, but I currently have no idea how to solve this problem.

**Comment by Summer12130** [comment]
Just now, I  copied the CSS/ TFF file of Monaco-Editor and placed it in the project to import it. The icons can be displayed normally now.
