### ISSUE TITLE
Extend monaco-editor peerDependency range to include current `monaco-editor@next`

### ISSUE THREAD

**Issue by thom4parisot** [suren-atoyan/monaco-react#450]
**Is your feature request related to a problem? Please describe.**

I am trying to install `monaco-editor` npm package to test a version that potentially includes a bugfix, not available through the CDN at the day I'm writing this issue:

```
npm install monaco-editor@next
```

The command adds `"monaco-editor": "^0.35.0-dev.20230202"` in package.json BUT, `npm clean-install` fails:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @monaco-editor/react@4.4.6
npm ERR! Found: monaco-editor@0.35.0-dev.20230202
npm ERR! node_modules/monaco-editor
npm ERR!   monaco-editor@"^0.35.0-dev.20230202" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer monaco-editor@">= 0.25.0 < 1" from @monaco-editor/react@4.4.6
npm ERR! node_modules/@monaco-editor/react
npm ERR!   @monaco-editor/react@"^4.4.1" from the root project
```

The [semver simulator](https://semver.npmjs.com/) indeed surfaces the `peerDependency` range does not include any `-dev.xxx` suffixed/unstable version

**Describe the solution you'd like**

Beta versions cannot be as nicely expressed as stable versions, as the range can only applies to a minor version in our case.

What do you think of having this instead?

```diff
- "monaco-editor": ">= 0.25.0 < 1",
+ "monaco-editor": ">= 0.25.0 >= 0.35.0-dev.0 < 1 ",
```

**Describe alternatives you've considered**

Another alternative I consider is adding extra flags to my project npm command (`--legacy-peer-deps` or `--force`) until `monaco-editor@0.35.0` is published, thus picked up by the current `peerDependency` setup of `@monaco-editor/react`.

**Comment by suren-atoyan** [comment]
in the latest version `4.5.0-beta.0` (soon I'll release `v4.5.0`) it uses `monaco-editor@0.36.1`
