### ISSUE TITLE
renderMarginRevertIcon does not render on DiffEditor

### ISSUE THREAD

**Issue by yehoshuasandler** [suren-atoyan/monaco-react#451]
**Describe the bug**

Setting `renderMarginRevertIcon` as `true` on the `<DiffEditor>` component does not render the revert icon in the margins as can be seen [in the Monaco playground](https://microsoft.github.io/monaco-editor/playground.html?source=v0.35.0#example-creating-the-diffeditor-multi-line-example).

By the docs these are taken as part of the `options` props on the `DiffEditor`

From the `editor.api.d.ts`:
``` javascript
        /**
         * Enable the rendering of the glyph margin.
         * Defaults to true in vscode and to false in monaco-editor.
         */
        glyphMargin?: boolean;

        /**
         * Shows icons in the glyph margin to revert changes.
         * Default to true.
         */
        renderMarginRevertIcon?: boolean;
```

I am unsure if `glyphMargin` is needed, so I tested with and without.

Even tested `editor.updateOptions({ thoseOptions })` inside my `onMount` handler to no success.

**To Reproduce**

Code to reproduce the behavior:

``` javascript


const someInitialOriginalValue = 'Here is a line \n and here is another'
const someInitialModifiedValue = 'Here is a line'

  const [editorValue, setEditorValue] = useState(someInitialOriginalValue)
  const [modifiedEditorValue, setModifiedEditorValue] = useState('')

  const handleEditorDidMount: DiffOnMount = async (editor, _) => {

    const modifiedEditor = editor.getModifiedEditor()
    const originalEditor = editor.getOriginalEditor()

    editor.updateOptions({ glyphMargin: true, renderMarginRevertIcon: true })

    setModifiedEditorValue(someInitialModifiedValue)

    // not needed, I do several other things in this event but thought the context of how I set the editor value might be important
    modifiedEditor.onDidChangeModelContent(() => {
      const modifiedMarkdown = modifiedEditor.getValue()
      setModifiedEditorValue(modifiedMarkdown)
    })
  }

    <DiffEditor
      original={editorValue} // state value
      modified={modifiedEditorValue} // state value
      language='markdown'
      height='600px'
      onMount={handleEditorDidMount}
      options={{
        renderMarginRevertIcon: true,
        glyphMargin: true,
        enableSplitViewResizing: false,
      }}
    />

```

**Expected behavior**

**Screenshots**

No revert glyph showing with this package:
<img width="718" alt="Screenshot 2023-02-14 at 8 06 20 PM" src="https://user-images.githubusercontent.com/14902813/218908939-8f95805b-1013-439d-8b97-ec3a89d6b90c.png">

Revert glyph showing on Monaco Editor playground:
<img width="682" alt="Screenshot 2023-02-14 at 8 07 14 PM" src="https://user-images.githubusercontent.com/14902813/218909059-95a86332-d2c1-4c85-8b0a-79974255abed.png">

**Desktop (please complete the following information):**
 - MacOS 13.1
 - Building onto of Wails so using Safari
 - Version 16.2 (18614.3.7.1.5)

**Comment by suren-atoyan** [comment]
@yehoshuasandler could you please check the `monaco-editor` version that you use and the one is being used in playground?

**Comment by yehoshuasandler** [comment]
@suren-atoyan 

This is what I find in `@monaco-editor/loader` and `@monaco-editor/react` package.json

```
    "monaco-editor": ">= 0.25.0 < 1",
```

If you need the package version:

```
  "name": "@monaco-editor/react",
  "version": "4.4.6",

  // --------

  "name": "@monaco-editor/loader",
  "version": "1.3.2",
```

The playground allows the choice of release version, and from what I can see, this feature was introduced version `0.34.0`

Let me know if this is not the exact info you are needing

**Comment by suren-atoyan** [comment]
`monaco-loader` v1.3.2 uses `0.34.0` version, check [this](https://github.com/suren-atoyan/monaco-loader/blob/master/src/config/index.js#L3)

if you don't have `loader.config(...)` somewhere in your code you should be using `0.34.0` version; you can check if in your devtools network tab - search `loader` and check the version.

**Comment by suren-atoyan** [comment]
playground by default uses `0.36.0`, be sure that the feature you are looking for exists in `0.34.0`

**Comment by yehoshuasandler** [comment]
In case you didn't see one of my comments above:

> The playground allows the choice of release version, and from what I can see, this feature was introduced version 0.34.0

The feature appears to exist in `0.34.0`, that is if I put faith that their playground works correctly.

I am not using `loader.config(...)` in my code but when I check the `loader.js` on my network tab, I see that it claims `0.33.0`. I pulled from npm only a few weeks ago and verified that I am working on version `^4.4.6` of `@monaco-editor/react`. 

<img width="553" alt="Screenshot 2023-02-18 at 10 04 53 AM" src="https://user-images.githubusercontent.com/14902813/219875939-191e9585-d785-4d31-b420-a9902adc626f.png">

**Comment by suren-atoyan** [comment]
I see, could you please try this?

```js
import { loader } from '@monaco-editor/react';

loader.config({
  paths: {
    vs: 'https://cdn.jsdelivr.net/npm/monaco-editor@0.34.0/min/vs',
  },
});
```

**Comment by suren-atoyan** [comment]
and check `loader.js` again, after `loader.config` change

**Comment by yehoshuasandler** [comment]
yup, can confirm that the loader config did the job!

Thankyou!
