### ISSUE TITLE
List of all options

### ISSUE THREAD

**Issue by justin-betty** [suren-atoyan/monaco-react#452]
Is there a list of all options that I'm able to use?

Seems this link isn't working.
https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.IStandaloneEditorConstructionOptions.html

Thnx!

**Comment by suren-atoyan** [comment]
check [this](https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IStandaloneEditorConstructionOptions.html) - README will be updated soon
