### ISSUE TITLE
🐛 `theme`

### ISSUE THREAD

**Issue by shenlong616** [suren-atoyan/monaco-react#453]
Hi

I use `<Editor options={{theme: "vs-dark"}} />` component and pass `{theme: "vs-dark"}` value into `options` property is not working 🥲

[screen-capture.webm](https://user-images.githubusercontent.com/15698245/221503587-73efd5d0-47c0-4f8e-9bb0-b7bdd6d47097.webm)

**Comment by suren-atoyan** [comment]
there is no `theme` in options, it's an Editor property, so instead of:

```js
<Editor
  options={{ theme: '...' }}
/>
```

do:

```js
<Editor
  theme="..."
/>
```
