### ISSUE TITLE
bug-ish: remove usage of `defaultProps`

### ISSUE THREAD

**Issue by juliusmarminge** [suren-atoyan/monaco-react#454]
**Describe the bug**

The editor component currently uses defaultProps which is deprecated and will be removed from react and already outputs some nasty warnings in the console:

**Screenshots**

<img width="1127" alt="CleanShot 2023-02-27 at 09 41 53@2x" src="https://user-images.githubusercontent.com/51714798/221515154-d9075731-1b9b-47b0-a027-5b88d7d8d521.png">

**Additional context**

Should be fairly straight forward to just use an `=` instead:

```ts
function Editor({
  foo,
}) { ... }
Editor.defaultProps = {
  foo: "whatever"
}

// => 

function Editor({
  foo = "whatever"
}) { ... }
```

Might as well get rid of the PropType dependency as well and use TypeScript.

I could make a PR for this if you want

**Comment by suren-atoyan** [comment]
having this converted to TS is a kind of dream; would love to check your PR 💚

**Comment by juliusmarminge** [comment]
> having this converted to TS is a kind of dream; would love to check your PR 💚 

Done :)

**Comment by suren-atoyan** [comment]
@juliusmarminge This is amazing, I really appreciate your work. I'll spend some time checking this; will keep you up to date.

**Comment by juliusmarminge** [comment]
> @juliusmarminge This is amazing, I really appreciate your work. I'll spend some time checking this; will keep you up to date.

Cool - FYI, I used a lot of optional chainging and even non-null assertions in some places where I didn't feel like changing the runtime behavior by putting in a bunch of new conditionals. Might be something to look over in the future
