### ISSUE TITLE
update `monaco-editor` to v0.34.0 or higher

### ISSUE THREAD

**Issue by tom2drum** [suren-atoyan/monaco-react#461]
The new API method `createDecorationsCollection` was introduces in [v0.34.0](https://github.com/microsoft/monaco-editor/blob/v0.34.1/CHANGELOG.md#0340) of `monaco-editor` which allows to create a collection of decorations in the editor.

I really like to use the new feature in my project, that is built with `@monaco-editor/react`, in order to highlight matching results of user's search.

Could we up `monaco-editor` version in `@monaco-editor/react` please?

**Comment by suren-atoyan** [comment]
new version is coming soon, there are some open PR that we are still working on; I'll keep you up to dated

**Comment by suren-atoyan** [comment]
@tom2drum could you please check `v4.5.0-beta.0` version?

**Comment by tom2drum** [comment]
@suren-atoyan I've checked it, everything works fine with `createDecorationsCollection` as far as I can see. Thanks!

**Comment by suren-atoyan** [comment]
`v4.5.0` has been released 🙂
