### ISSUE TITLE
onChange Event executed incorrectly

### ISSUE THREAD

**Issue by LaamGinghong** [suren-atoyan/monaco-react#472]
https://stackblitz.com/edit/react-ts-zzruqe?file=App.tsx

When the value get another platform's line break, it will trigger onChange event automatic incorrectly.

**Comment by suren-atoyan** [comment]
@LaamGinghong sorry, but I am not sure I understand

**Comment by LaamGinghong** [comment]
@suren-atoyan In the App.tsx file in the online example I gave, the value of the editor is manually updated when the trigger button is clicked. But at this time, the editor executes the onChange event by mistake, because the newline character of the value of the editor has changed.
![image](https://user-images.githubusercontent.com/33472924/230761693-717661b2-c12e-41b9-becc-a9ba098a18d1.png)
My computer is a mac.

**Comment by suren-atoyan** [comment]
@LaamGinghong I see, try the latest version `v4.5.0`

**Comment by LaamGinghong** [comment]
@suren-atoyan It works and thank you so much.
