### ISSUE TITLE
ERROR in ../node_modules/_@monaco-editor_react@4.5.0@@monaco-editor/react/dist/index.mjs 1:1806 Module parse failed: Unexpected token (1:1806)

### ISSUE THREAD

**Issue by zuoqi705** [suren-atoyan/monaco-react#475]
**Describe the bug**
Module parsed failed in webpack4 when exclude `node_modules` in babel, since it contains optional chaining operator.

**To Reproduce**

Or, please add a minimal code snippet to reproduce the issue, for example in [codesandbox](https://codesandbox.io/).

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help to explain your problem.
![image](https://user-images.githubusercontent.com/30346283/230768121-8f78aa17-af5e-44f0-9712-c94aa188f5f9.png)
![image](https://user-images.githubusercontent.com/30346283/230768135-28e2b6cd-0524-4634-be47-0e4845154ea3.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by suren-atoyan** [comment]
@zuoqi705 the compile [target](https://github.com/suren-atoyan/monaco-react/blob/master/tsup.config.ts#L10) is `esnext`. If your target is different then do not exclude it from your compile/transpile process.

**Comment by zuoqi705** [comment]
> @zuoqi705 the compile [target](https://github.com/suren-atoyan/monaco-react/blob/master/tsup.config.ts#L10) is `esnext`. If your target is different then do not exclude it from your compile/transpile process.

but in the `4.4.x` version it won't，I think it should be transpiled to es5 in .mjs file

**Comment by viko16** [comment]
I understand the benefits of using `mjs`. 
But, it would be helpful if this change could be postponed until the next major version release, so that users who cannot upgrade their webpack versions can continue to use the library.
