### ISSUE TITLE
Incorrect model updated when keeping models in DiffEditor

### ISSUE THREAD

**Issue by StefanDBTLabs** [suren-atoyan/monaco-react#478]
**Describe the bug**
When using `Editor` with `keepCurrentModel` and switch between 2 files you correctly end up with 2 models. [Here is a sandbox with 2 buttons to switch between files and a console log that logs out all the models with path and value.](https://codesandbox.io/s/onvalidate-forked-ue3ho3?file=/src/App.js:920-936)

This does not work correctly with the `DiffEditor`. With `keepCurrentOriginalModel` and `keepCurrentModifiedModel` set to true and switching between 2 files with `original` and `modified` values and with unique paths should result in 4 models. instead only 2 models are created and wrong models are updated with the new values. [Here is a sandbox that lets you switch between 2 files and console logs the model paths and values](https://codesandbox.io/s/simple-usage-forked-2fek7i?file=/src/App.js:304-315). I would expect this to console log 4 models with 4 unique URIs and 4 unique values but only 2 models are created and incorrect values are set with URIs as the content switches.

**To Reproduce**

- Sandbox bug demo https://codesandbox.io/s/simple-usage-forked-2fek7i?file=/src/App.js:304-315
- Open the console 
- Switch between the 2 files with the provided buttons
- See the URIs and Values printed to the console
- Notice that the URIs do not change but the values do, those values are from other URIs
- Notice only 2 models are created when there should be 4.

**Expected behavior**
When the DiffEditor is used with `keepCurrentOriginalModel` and `keepCurrentModifiedModel` and 4 unique paths are passed in for `originalModelPath` and `modifiedModelPath` I expect monaco to have 4 models in memory with correct values mapped to the correct paths.

**Screenshots**
Loom video of the bug https://www.loom.com/share/e595966e055447ffb19dfb8b99290770

**Additional context**
I would be happy to help write a fix for this but after debugging the code I can't tell where things are going wrong. Would love any help you can provide to submit a PR.

**Comment by suren-atoyan** [comment]
fixed ✅

**Comment by StefanDBTLabs** [comment]
I think we either need to re-open this issue or I can file it again. I've updated the codesandbox to the most recent version and switching between files in the diffEditor still causes wrong contents to appear by following the same steps as above. [https://codesandbox.io/s/simple-usage-forked-2fek7i?file=/src/App.js:304-315](https://codesandbox.io/s/simple-usage-forked-2fek7i?file=/src/App.js:304-315)
