### ISSUE TITLE
Readonly 

### ISSUE THREAD

**Issue by alipas** [suren-atoyan/monaco-react#490]
**Problem**
Sometimes you want to be able to view code that is complicated and long enough to warrant being placed in an editor.

**Describe the solution you'd like**
A simple configuration where the content is only available in readonly mode - disallowing adding or removing information but allowing copying and navigating in the editor.

**Comment by suren-atoyan** [comment]
@alipas try this:

```js
<Editor
  options={{
    readOnly: true,
  }}
  ...
/>
```

**Comment by utkubiz** [comment]
@suren-atoyan Can we remove or edit the tooltip for readonly editor ?

<img width="315" alt="image" src="https://github.com/suren-atoyan/monaco-react/assets/3123846/e133c291-ebb8-4645-bc36-b131cfdf67ab">
