### ISSUE TITLE
Height property not working for percentages

### ISSUE THREAD

**Issue by BoxedFruits** [suren-atoyan/monaco-react#491]
**Describe the bug**
It seems like the height property only works with vh and not percentages
**To Reproduce**

Use a percentage for height. 
Can also delete the prop and it will produce the same behavior as it tries to default to 100%

https://codesandbox.io/s/get-value-forked-uojw5j?file=/src/App.js

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help to explain your problem.
![image](https://github.com/suren-atoyan/monaco-react/assets/34636700/de596d00-8c6b-4c26-8efa-eb6b3ab8e4d2)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
 - Version 114.0.1823.37 (Official build) (64-bit

**Additional context**

**Comment by suren-atoyan** [comment]
@BoxedFruits in your example `height` is 20%. So, the question is 20% of what? Most probably its parent doesn't have any height.

**Comment by BoxedFruits** [comment]
oops i forgot how html and css work
