### ISSUE TITLE
How to external monaco-editor when using webpack

### ISSUE THREAD

**Issue by LaamGinghong** [suren-atoyan/monaco-react#498]
**Is your feature request related to a problem? Please describe.**
If I use CDN to load monaco-editor, it means I don't want to build the chunk in webpack flow.

**Describe the solution you'd like**
Added a fully manual control function.

**Comment by suren-atoyan** [comment]
@LaamGinghong I am having a bit of trouble understanding the issue you're currently facing. Could you please provide more detail or clarify your question?

**Comment by lehaiquantb** [comment]
I guess OP wants to use loader file in local environment instead of using CDN
