### ISSUE TITLE
defineTheme and setTheme not available?

### ISSUE THREAD

**Issue by avisprince** [suren-atoyan/monaco-react#50]
Are `defineTheme` and `setTheme` implemented? I see that they are available in the API docs and in the [playground](https://microsoft.github.io/monaco-editor/playground.html#customizing-the-appearence-exposed-colors) but I cannot access those functions with the editor instance provided in EditorDidMount.

**Comment by suren-atoyan** [comment]
Hello @avisprince 

It's implemented. In the playground, they use "monaco.editor.setTheme". You can access it by using the instance of monaco, not editor. "monaco.editor", which you see in the playground is not called "editor instance". The editor instance is what returns by `monaco.editor.create`. By `monaco.editor.setTheme` you will set the theme for all editors. Hence, check [it](https://codesandbox.io/s/monaco-editorreact---monaco-instance-5pbmx?fontsize=14&hidenavigation=1&theme=dark) to see how you can access the instance of monaco or read more [here](https://github.com/suren-atoyan/monaco-react#monaco-instance).

Thank you!

**Comment by avisprince** [comment]
That makes sense. Thanks so much for the clarification and for your work on the project! Cheers :)
