### ISSUE TITLE
I can't see the suggestions text when typing using monaco

### ISSUE THREAD

**Issue by folego** [suren-atoyan/monaco-react#505]
I added some suggestions to my Monaco instance using a new custom language.
I am able to start typing and see the suggestions being displayed but I without the text.

```_monacoInstance.languages.registerCompletionItemProvider("solidity", {
                provideCompletionItems: (model, position) => {
                    const word = model.getWordUntilPosition(position);
                    const range = {
                        startLineNumber: position.lineNumber,
                        endLineNumber: position.lineNumber,
                        startColumn: word.startColumn,
                        endColumn: word.endColumn,
                    };
                    var suggestions = [
                        {
                            label: "simpleText",
                            kind: monaco.languages.CompletionItemKind.Text,
                            insertText: "simpleText",
                            range: range,
                        },
                        {
                            label: "testing",
                            kind: monaco.languages.CompletionItemKind.Keyword,
                            insertText: "testing(${1:condition})",
                            insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                            range: range,
                        },
                        {
                            label: "ifelse",
                            kind: monaco.languages.CompletionItemKind.Snippet,
                            insertText: ["if (${1:condition}) {", "\t$0", "} else {", "\t", "}"].join("\n"),
                            insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                            documentation: "If-Else Statement",
                            range: range,
                        },
                    ];
                    return { suggestions: suggestions };
                },
            });
```

Expected behavior: popup with labels declared in suggestions

Screenshots
<img width="453" alt="image" src="https://github.com/suren-atoyan/monaco-react/assets/20648959/e4eedb3a-ba0d-4d67-bbc4-aa3e96c197fe">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge/Chrome
 - Version Latest

**Additional context**
Tried to add quickSuggestions and wordBasedSuggestions but doesn't work.

```
<Editor defaultLanguage="mylang" theme="mylangTheme" scrollBeyondLastLine={false} value={code} onChange={handleEditorChange}
// trying to fix the popup issue
quickSuggestions={true}
wordBasedSuggestions={true}
// quickSuggestions={ other: true, strings: true }
/>
```

**Comment by chenEdgar** [comment]
hei, I maked a demo in [codesabox](https://codesandbox.io/s/monaco-editor-react---get-value-forked-2mrlws?file=/src/index.js). maybe it will help you

**Comment by chenEdgar** [comment]
> I added some suggestions to my Monaco instance using a new custom language. I am able to start typing and see the suggestions being displayed but I without the text.
> 
> ```
>                 provideCompletionItems: (model, position) => {
>                     const word = model.getWordUntilPosition(position);
>                     const range = {
>                         startLineNumber: position.lineNumber,
>                         endLineNumber: position.lineNumber,
>                         startColumn: word.startColumn,
>                         endColumn: word.endColumn,
>                     };
>                     var suggestions = [
>                         {
>                             label: "simpleText",
>                             kind: monaco.languages.CompletionItemKind.Text,
>                             insertText: "simpleText",
>                             range: range,
>                         },
>                         {
>                             label: "testing",
>                             kind: monaco.languages.CompletionItemKind.Keyword,
>                             insertText: "testing(${1:condition})",
>                             insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
>                             range: range,
>                         },
>                         {
>                             label: "ifelse",
>                             kind: monaco.languages.CompletionItemKind.Snippet,
>                             insertText: ["if (${1:condition}) {", "\t$0", "} else {", "\t", "}"].join("\n"),
>                             insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
>                             documentation: "If-Else Statement",
>                             range: range,
>                         },
>                     ];
>                     return { suggestions: suggestions };
>                 },
>             });
> ```
> 
> Expected behavior: popup with labels declared in suggestions
> 
> Screenshots <img alt="image" width="453" src="https://user-images.githubusercontent.com/20648959/253158223-e4eedb3a-ba0d-4d67-bbc4-aa3e96c197fe.png">
> 
> **Desktop (please complete the following information):**
> 
> * OS: Windows
> * Browser Edge/Chrome
> * Version Latest
> 
> **Additional context** Tried to add quickSuggestions and wordBasedSuggestions but doesn't work.
> 
> ```
> <Editor defaultLanguage="mylang" theme="mylangTheme" scrollBeyondLastLine={false} value={code} onChange={handleEditorChange}
> // trying to fix the popup issue
> quickSuggestions={true}
> wordBasedSuggestions={true}
> // quickSuggestions={ other: true, strings: true }
> />
> ```

hei, I maked a demo in [codesabox](https://codesandbox.io/s/monaco-editor-react---get-value-forked-2mrlws?file=/src/index.js). maybe it will help you

**Comment by chenEdgar** [comment]
@folego hei, I maked a demo in [codesabox](https://codesandbox.io/s/monaco-editor-react---get-value-forked-2mrlws?file=/src/index.js). maybe it will help you

**Comment by folego** [comment]
I got it, a class called main in my app.css was messing with the popup. I can't believe this🤦‍♂️. Thanks for all the support.
