### ISSUE TITLE
Workers without CDN

### ISSUE THREAD

**Issue by Alejandroid17** [suren-atoyan/monaco-react#506]
**Is your feature request related to a problem?**
I am creating an application that cannot have external access, and monaco-editor library makes requests to external resources to load the workers. Is it possible to have those workers locally?

**Describe the solution you'd like**
Store external resources locally.

**Additional context**
![image](https://github.com/suren-atoyan/monaco-react/assets/17381133/cff09273-087c-4f81-a4bd-bc9e3fb2979a)

Thanks!!

**Comment by suren-atoyan** [comment]
@Alejandroid17 could you please check [this](https://github.com/suren-atoyan/monaco-react#use-monaco-editor-as-an-npm-package)?

**Comment by Alejandroid17** [comment]
> @Alejandroid17 could you please check [this](https://github.com/suren-atoyan/monaco-react#use-monaco-editor-as-an-npm-package)?

In my first solution, the path was modified, and worked
```
import Editor, { loader } from '@monaco-editor/react';
loader.config({
    paths: {
        vs: '/site_media/vendor/vs'
    }
});
```
but I was looking for a better solution.

Thanks for everything, it works without problems!
