### ISSUE TITLE
Place Holder for Editor

### ISSUE THREAD

**Issue by Shreyas-sonu** [suren-atoyan/monaco-react#507]
is it possible to add PlaceHolder for Editor, if so Please Reply for this message, waiting for your response thank you

**Comment by suren-atoyan** [comment]
there is no placeholder functionality on `monaco` - it should be implemented custom

**Comment by Shreyas-sonu** [comment]
thank you for the quick response, I have found a way out for this issue, just check for Feature Request #509 ...❣

**Comment by lifegit** [comment]
hi, @Shreyas-sonu , is it convenient to share?

**Comment by lifegit** [comment]
https://dev.to/ademking/how-to-add-a-placeholder-to-monaco-editor-35p7
this help you.

**Comment by Shreyas-sonu** [comment]
@lifegit thanks for sharing
