### ISSUE TITLE
Avoiding Copy Paste

### ISSUE THREAD

**Issue by Shreyas-sonu** [suren-atoyan/monaco-react#508]
is there Anyway i can avoid copy paste in Editor Component. I had attached the onPaste in event handlers in onMount Callback Function and Tried to avoid paste event through ref and done some trial as well but this isn't working

**Comment by Shreyas-sonu** [comment]
is there any Updates on this Feature ??

**Comment by Shreyas-sonu** [comment]
bro

**Comment by suren-atoyan** [comment]
@Shreyas-sonu [this](https://github.com/microsoft/monaco-editor/issues/2848#issuecomment-1000164089) works. Use `copy` instead of `pase`, something like this:

```js
import React from 'react';

import Editor from '../../dist';

function App() {
  return (
    <Editor
      height="100vh"
      defaultLanguage="javascript"
      defaultValue="// some comment"
      onMount={(editor) => {
        editor.getContainerDomNode().addEventListener(
          'copy',
          (event) => {
            console.log('copy captured in monaco editor contianer');
            event.preventDefault();
            event.stopPropagation();
          },
          true,
        );
      }}
    />
  );
}

export default App;

```
