### ISSUE TITLE
Initialization Error: Trying to load URL from local file system

### ISSUE THREAD

**Issue by crystaltine** [suren-atoyan/monaco-react#514]
I'm using Monaco (`@monaco-editor/react`) for a code editor in a React-Electron Typescript app. When I simply `import Editor from '@monaco-editor/react';` and then add an `Editor` component to React, I'm getting the error

```
ENOENT: no such file or directory, open 
D:\<My project directory>\https:\cdn.jsdelivr.net\npm\monaco-editor@0.36.1\min\vs\editor\editor.main.js'
```

which I'm assuming means it's trying to load the URL but it is somehow getting appended to the absolute path of my local directory. I checked the URL and it does in fact lead to a Javascript file. Does anyone know how to get rid of the local path at the beginning?

(`<My project directory>` refers to the folder containing `node_modules`, `package.json`, `src`, etc.) 

All I have done is npm installed `@monaco-editor/react` and `monaco-editor`. Here's a snippet of my component:

```typescript
import React from 'react';
import Editor, { loader } from '@monaco-editor/react';

export interface CodeBodyProps {...}

const CodeBody = (...) {
    return (
      <Editor
        height="100%"
        defaultLanguage="javascript"
        defaultValue='// test comment'
      />
    );
}

export default CodeBody;
```

The exact wording of the error:
```
Monaco initialization: error: Error: ENOENT: no such file or directory, open 'D:\<My project directory>\https:\cdn.jsdelivr.net\npm\monaco-editor@0.36.1\min\vs\editor\editor.main.js'
```
I'm not given anything about the location of the error besides
```
0.36.1\min\vs\editor\editor.main.js':undefined:undefined
```
and looking at that file it seems like it's already bundled, plus I searched for the URL in there and couldn't find anything.

More information:
OS - Windows 11
Not using a browser, but an Electron app

**Comment by suren-atoyan** [comment]
check [this](https://github.com/suren-atoyan/monaco-react#for-electron-users) and [this](https://github.com/suren-atoyan/monaco-react#use-monaco-editor-as-an-npm-package)

**Comment by crystaltine** [comment]
Thanks so much! The Editor is now rendering properly and without any errors. Just one quick thing though, I don't seem to be getting autocomplete/suggestions inside the editor. Other things like highlighting and loading contents are working fine. Is there anything I need to do to make that work?

**Comment by crystaltine** [comment]
Edit - Not exactly sure what happened but after tweaking a little bit everything works now :)

**Comment by Yamazaki93** [comment]
In case someone needs the steps, we are also using an Electron-React-Typescript based project with webpack and had trouble getting this to work. (Electron 30.0.1, typescript 4.5.4, react 18.3.1)

How we make it work was:

1. `npm i @monaco-editor/react monaco-editor monaco-editor-webpack-plugin`
2. Configure webpack (`webpack.renderer.config.ts`) with [this](https://www.npmjs.com/package/monaco-editor-webpack-plugin#using)
3. In the files using the editor, do
```Typescript
import * as monaco from 'monaco-editor';
import { Editor, loader } from '@monaco-editor/react';

loader.config({ monaco });
```
4. Then use `<Editor/>` as noted in the doc.
