### ISSUE TITLE
Minimap flickers when editor is resized

### ISSUE THREAD

**Issue by ledelinski-loadero** [suren-atoyan/monaco-react#525]
**Describe the Bug**
When resizing the `@monaco-editor/react` editor that uses version "4.5.2" of "@monaco-editor/react", the minimap flickers intermittently.

**To Reproduce**
1. Initialize a `@monaco-editor/react` editor using the specified versions.
2. Resize the editor (e.g., by resizing the browser window).
3. Observe the minimap behavior.

**Expected behavior**
The minimap should move smoothly without any flickering when the editor is resized.

Environment:
@monaco-editor/loader: 1.3.3
@monaco-editor/react: 4.5.2

**Additional context**
I've also tested different versions of @monaco-editor/react and the flickering issue persists across all major browsers. This issue impacts the user experience.

**Comment by suren-atoyan** [comment]
@ledelinski-loadero as you can see [here](https://github.com/suren-atoyan/monaco-react/blob/master/src/Editor/Editor.tsx#L161C11-L161C26) `automaticLayout` is turned on. If I am not mistaken `automaticLayout` is implemented in a way that it just updates the layout every 100 milliseconds. You can turn it off and do it manually on your container resize. Call `editor.layout()` to adjust the layout.
