### ISSUE TITLE
Different Monaco editor components sharing same schema

### ISSUE THREAD

**Issue by ishan-diablo** [suren-atoyan/monaco-react#537]
**Describe the bug**

I have 2 separate components with [Monaco editor react](https://www.npmjs.com/package/@monaco-editor/react) of value `JSON`. One of the editor has a schema validation defined, **problem is another instance also validating with same schema. That instance should not have any validation/schema.**

I have created a demo on [stackblitz here](https://stackblitz.com/edit/stackblitz-starters-ftdvat?description=React%20%20%20TypeScript%20starter%20project&file=package.json,src%2FEditorField.tsx,src%2FApp.tsx,src%2Fstyle.css,src%2FSchemaField.tsx&title=React%20Starter)

```ts
// code showing schema validation
  useEffect(() => {
    if (schema) {
      const editorSchema = createEditorSchema(schema);
      monaco?.languages?.json?.jsonDefaults?.setDiagnosticsOptions({
        validate: true,
        schemas: [editorSchema],
      });
    }
  }, [schema]);
```

**To Reproduce**
1. Check editor 1 and hover to see the schema error
2. Check editor 2 which has the schema of editor 1. Problem is editor 2 is validating with its own value.

**Expected behavior**
Editor 2 which is schema field should not be validated with a schema. It should only show value. Only editor 1 should be validated

**Demo Link**
[Sample demo](https://stackblitz.com/edit/stackblitz-starters-ftdvat?description=React%20%20%20TypeScript%20starter%20project&file=package.json,src%2FEditorField.tsx,src%2FApp.tsx,src%2Fstyle.css,src%2FSchemaField.tsx&title=React%20Starter)

**Screenshots**
The editor 2 should not have any validations on schema, find SS below
![Screenshot 2023-09-19 at 13 33 21](https://github.com/suren-atoyan/monaco-react/assets/114394941/33911a58-3b6d-4158-b7f3-a3fa78a6daa4)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - mac
 - Browser [e.g. chrome, safari] - any

**Additional context**
I have a feature requirement where I render 2 editor instances. Instances one has value of JSON, instance 2 has JSON schema for first instance.

**Comment by suren-atoyan** [comment]
@ishan-diablo that is because by doing this:

```js
monaco?.languages?.json?.jsonDefaults?.setDiagnosticsOptions({
    validate: true,
    schemas: [editorSchema],
  });
```

you apply schema rules on all JSON editors.

To fix this, do the following:

1) add path to the editor you want to apply rules:

in file `EditorField.tsx` in the `<Editor />` component add `path="test.json"`

2) adjust `uri` and `fileMatch` in the schema to refer to the model you want. In `createEditorSchema` `schemaBase` should look like this:

```js
  const schemaBase = {
    uri: '/test.json',
    fileMatch: ['test.json'],
    schema: { ...parsedSchema },
  };
```

**Comment by ishan-diablo** [comment]
Hi @suren-atoyan 
Thanks for the update. Yes providing unique `path` works 🚀 

I have another small trouble. 

Initialising `schema` in useEffect is not working as expected. For e.g. the below code doesn't work

```ts
    useEffect(() => {
        if (schema) {
            const editorSchema = createEditorSchema(schema);
            monaco?.languages?.json?.jsonDefaults?.setDiagnosticsOptions({
                validate: true,
                schemas: [editorSchema],
            });
        }
    }, [schema]);

```

But this works
```ts
const handleMount = (editor, monaco) => {
       const editorSchema = createEditorSchema(schema);
       monaco?.languages?.json?.jsonDefaults?.setDiagnosticsOptions({
            validate: true,
            schemas: [editorSchema],
       });
} 

```

I don't want to use 2nd code since my schema is coming from async api.

**Comment by suren-atoyan** [comment]
@ishan-diablo I guess that's expected. You render the editor with current json rules, and after that you update the rules, most probably it won't affect on already rendered editor. You either should manually force that model to re-run again (or reconsider its rules) or you can render the Editor component whenever you have the schema.
