### ISSUE TITLE
custom cdn url

### ISSUE THREAD

**Issue by flowerofmycountry** [suren-atoyan/monaco-react#542]
cdn.jsdelivr.net is too slow. i want to pass cdn url like  this 'https://cdn.bootcdn.net/ajax/libs/{name}/{version}/{path}'

**Comment by suren-atoyan** [comment]
you can do this:

```js
import { loader } from '@monaco-editor/react';

loader.config({ paths: { vs: '...' } });
```

check how it's done [here](https://github.com/suren-atoyan/monaco-loader/blob/master/src/config/index.js)
