### ISSUE TITLE
multiple editor components with the same path, Editor value will be changed to the same value

### ISSUE THREAD

**Issue by fewismuch** [suren-atoyan/monaco-react#552]
**Describe the bug**
If I use multiple editor components with the same path, The value of the editor will change the same, as will the input

**To Reproduce**
[This is an example](https://codesandbox.io/s/multi-editor-s3pxwg?file=/src/App.js)

**Expected behavior**
I need to use multiple editors on a page, and different editors may have the same path and different content, how do I make sure they are isolated, for example by adding a key or namespace?

**Comment by suren-atoyan** [comment]
> for example by adding a key or namespace?

Yes, the behavior you've experienced is expected. Use/implement a namespace to isolate them. So, let's say the path is `something/index.js` make it `project1/something/index.js` for one editor and `project2/something/index.js` for another.
