### ISSUE TITLE
How to have intellisense for a language  ? (in Nextjs)

### ISSUE THREAD

**Issue by dev265545** [suren-atoyan/monaco-react#560]

**Comment by suren-atoyan** [comment]
You have IntelliSense for the following languages out of the box:

- TypeScript
- JavaScript
- CSS
- LESS
- SCSS
- JSON
- HTML

For all other supported languages, you have only syntax highlighting, so you have to implement IntelliSense by yourself by using an appropriate [LSP](https://microsoft.github.io/language-server-protocol/) or doing it manually by using a [completion provider](https://microsoft.github.io/monaco-editor/playground.html?source=v0.44.0#example-extending-language-services-completion-provider-example)

**Comment by ansh** [comment]
How do I integrate Shiki highlighter? @suren-atoyan
