### ISSUE TITLE
monaco-react is not compatible with React 18's React 17 Mode

### ISSUE THREAD

**Issue by Zsynuting** [suren-atoyan/monaco-react#563]
**Describe the bug**
If rendering monaco-react with React 18 but using legacy `render` API instead of the `createRoot` API, when typing fast in monaco-editor, cursor will automatically just to the end of text model

**To Reproduce**

I have this repo to reproduce this issue 

https://github.com/Zsynuting/test-monaco-diff-react

**Expected behavior**
Just want to understand why it happens the behavior with React 18's React 17 mode. No specific expected behavior

**Screenshots**
I have screenshot and video of the behavior in my repo 

https://github.com/Zsynuting/test-monaco-diff-react

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version:  "@monaco-editor/react": "^4.6.0",

**Additional context**
No

**Comment by suren-atoyan** [comment]
hi @Zsynuting 

> Just want to understand why it happens the behavior with React 18's React 17 mode

I don't know. The way you load different versions of React [here](https://github.com/Zsynuting/test-monaco-diff-react/blob/main/src/index.tsx#L22) raises many questions. Anyway, I am not sure I understand the issue - if you only want to understand why it behaves in an unexpected way while you are using React 18 with React 17 render method (still I am not sure I understand why you are doing this in a first place) - I don't know the answer to this.

**Comment by Zsynuting** [comment]
thanks for the reply.

> (still I am not sure I understand why you are doing this in a first place)

It's not on purpose. just because I was rendering an open source Low Code App using its UMD resources in our micro-frontend project. Previously the version of React in the micro-frontend project is React 17, the Low Code was working fine. But after the micro-frontend project updated React to 18, the monaco-editor inside the Low Code App behave the way I described.

I just want to understand the root cause. So, it's more of an inquiry instead of an issue of monaco-react. 

Maybe I should inquiry it from React team. :)
