### ISSUE TITLE
monaco loader unable auto prompt in 0.45.0.

### ISSUE THREAD

**Issue by lifegit** [suren-atoyan/monaco-react#565]
**Describe the bug**
monaco unable auto prompt.

**To Reproduce**
[codesandbox code snippet](https://codesandbox.io/p/sandbox/simple-usage-forked-cdnhxy?file=%2Fsrc%2Findex.js%3A7%2C17) perfect work.

**Expected behavior**
monaco loader in version 0.25.2 working normally. write 'import x' auto  prompt 'from'.
bug in version 0.45.0 (latest version) it can't work well.

**Screenshots**
<img width="1031" alt="image" src="https://github.com/suren-atoyan/monaco-react/assets/33006878/a37a1dac-e3a8-49fa-86b2-f198bf2d26ff">
<img width="1024" alt="image" src="https://github.com/suren-atoyan/monaco-react/assets/33006878/1610c77d-049b-4d0c-bdaf-c2dd583f41b1">

**Desktop (please complete the following information):**
 - OS: MacOs 13.2.1 (22D68)
 - Browser Chrome
 - Version 119.0.6045.199

**Comment by suren-atoyan** [comment]
You can use [loader](https://github.com/suren-atoyan/monaco-react?tab=readme-ov-file#loader-config) to load whatever version of `monaco-editor` you want. You can do something like this:

```js
loader.config({ paths: { vs: 'https://cdn.jsdelivr.net/npm/monaco-editor@0.25.2/min/vs' } });
```

Also, you should open this issue on the original repository, this is the `React` wrapper.
