### ISSUE TITLE
Snippet suggession or the error finding is not working properly

### ISSUE THREAD

**Issue by SujithThirumalaisamy** [suren-atoyan/monaco-react#567]
**Describe the bug**
When switching for one lang to another. Using state the proper prompt for the suggession is not working

**To Reproduce**

1. Set a default lang
2. Type and test some snippet suggesstion
3. Change the language with state
4. Snippet is not working

**Expected behavior**
Expected to properly switch the editor to the language and give propper snippets

**Comment by suren-atoyan** [comment]
please check out [multi-model-editor](https://github.com/suren-atoyan/monaco-react?tab=readme-ov-file#multi-model-editor)
