### ISSUE TITLE
https://cdn.jsdelivr.net/npm/monaco-editor@0.43.0/min/vs/loader.js 加载失败 怎么处理

### ISSUE THREAD

**Issue by zj91zj** [suren-atoyan/monaco-react#571]
https://cdn.jsdelivr.net/npm/monaco-editor@0.43.0/min/vs/loader.js 加载失败 怎么处理

**Comment by suren-atoyan** [comment]
@zj91zj sorry, but I don't understand Chinese.

If you want to use a different CDN, use [loader-config](https://github.com/suren-atoyan/monaco-react?tab=readme-ov-file#loader-config)

**Comment by zj91zj** [comment]
> @zj91zj sorry, but I don't understand Chinese.
> 
> If you want to use a different CDN, use [loader-config](https://github.com/suren-atoyan/monaco-react?tab=readme-ov-file#loader-config)


import Editor from '@monaco-editor/react';
import { loader } from '@monaco-editor/react';
loader.config({ paths: { vs: './scripts/monaco-editor' } });
![微信图片_20240124123626](https://github.com/suren-atoyan/monaco-react/assets/41497368/8242fa13-665a-4793-b04c-ac2e230b0ba7)

I use a local file, success to load editor, but  Code snippets and error tip not effective.

**Comment by zj91zj** [comment]
thanks

**Comment by zedfight** [comment]
use [loader-config](https://github.com/suren-atoyan/monaco-react?tab=readme-ov-file#loader-config)

```
import * as monaco from 'monaco-editor/esm/vs/editor/editor.api.js';
import Editor, {loader} from '@monaco-editor/react';

loader.config({ monaco });
```

use [monaco-editor-webpack-plugin](https://github.com/microsoft/monaco-editor/tree/main/webpack-plugin)
```
const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin');

module.exports = {
	entry: './index.js',
	module: {
		rules: [
			...
		]
	},
	plugins: [new MonacoWebpackPlugin()]
};
```

**Comment by qhh001** [comment]
I did it the same way you did. However, I'm still getting an error saying the loading has failed. Do I still need to add my own CDN configuration in the loader? Should I place the requested loader.js on our own CDN? @zedfight  @suren-atoyan
