### ISSUE TITLE
I need rounded Scrollbars

### ISSUE THREAD

**Issue by Wissperwind** [suren-atoyan/monaco-react#584]
Hi

I included the monaco editor in my website. But the website use modern style rounded scrollbars. Like this:

```
*::-webkit-scrollbar {
    width: 16px;
}

*::-webkit-scrollbar-track {
    border-radius: 8px;
}

*::-webkit-scrollbar-thumb {
    height: 56px;
    border-radius: 8px;
    border: 4px solid transparent;
    background-clip: content-box;
    background-color: #888;
}

*::-webkit-scrollbar-thumb:hover {
    background-color: #555;
}
```

It does no look good if the whole website has rounded scrollbars, but the editor has thick square ones. Can you please provide an option for rounded scrollbars?

![Unbenannt](https://github.com/suren-atoyan/monaco-react/assets/20759873/4aa7e50e-0352-4fbe-a2bc-9056e6e4a13e)

**Comment by suren-atoyan** [comment]
this issue should be addressed to [microsoft/monaco-editor](https://github.com/microsoft/monaco-editor)

**Comment by Wissperwind** [comment]
Okay, I opened the same Issue there:
https://github.com/microsoft/monaco-editor/issues/4374
