### ISSUE TITLE
style of quickSuggestions

### ISSUE THREAD

**Issue by jessycalcalcal** [suren-atoyan/monaco-react#588]
**Describe the bug**
when i choose  the option quickSuggestions, the style of Suggestions is error
**To Reproduce**

**Expected behavior**
such as
<img width="698" alt="image" src="https://github.com/suren-atoyan/monaco-react/assets/119379794/a69c49eb-16e0-4fe3-80fb-4c69513f48da">

**Screenshots**
<img width="748" alt="image" src="https://github.com/suren-atoyan/monaco-react/assets/119379794/254c9703-9c2b-4f96-975b-d6a8fc7e4edb">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome
 - Version: 121

**Comment by suren-atoyan** [comment]
this issue should be referred to [microsoft/monaco-editor](https://github.com/microsoft/monaco-editor)
