### ISSUE TITLE
"setTheme" gets called every time  a new instance of Editor is initialised

### ISSUE THREAD

**Issue by saikatmitra91** [suren-atoyan/monaco-react#593]
**Describe the bug**
My app contains multiple instances of Editor some of which load dynamically. 
Every time a new editor is initialised the theme gets set again causing a flash in all the other initialised editor instances as well. 

**To Reproduce**

1. Go to https://www.empirical.run/gpt-3-5-turbo-vs-gpt-4
2. Click on one of the "Schema" buttons
3. Look at the cells closely. The currently drawn cells flash while the schema drawer opens.

**Comment by suren-atoyan** [comment]
This issue should be addressed to [microsoft/monaco-editor](https://github.com/microsoft/monaco-editor/issues/338).

[There is already one](https://github.com/microsoft/monaco-editor/issues/338)
