### ISSUE TITLE
How can i add Prettier to insert semicolons automatically in JS

### ISSUE THREAD

**Issue by Suniron** [suren-atoyan/monaco-react#60]
Hello,

How can i add Prettier to insert semicolons when formatting js code ?

I can't find this..

Thank's a lot.

**Comment by suren-atoyan** [comment]
Hello @Suniron.

It's out of the responsibilities of this library. I mean, you are able to get the value of editor whenever you want, and also you are able to set a new value, again, whenever you want. So, between these steps, you can modify the value you got with any tools; if you are interested in running Prettier in a browser, maybe [it can help](https://prettier.io/docs/en/browser.html) (it was found from this [discussion](https://github.com/prettier/prettier/issues/3296)).

Hope it'll help :)

**Comment by suren-atoyan** [comment]
Hello @Suniron, please let me know if your problem is solved, that we can close the issue. Thank you!

**Comment by Suniron** [comment]
Hi, 

Yes, it's solved by using another lib.

Thanks

**Comment by steveruizok** [comment]
It should look something like this:

```js
import * as React from "react"
import prettier from "prettier/standalone"
import parserTypeScript from "prettier/parser-typescript"
import { ControlledEditor } from "@monaco-editor/react"

function Example() {

  const [state, setState] = React.useState("")

  return (
    <ControlledEditor
      value={state}
      onChange((_, code) => {
        return prettier.format(code, {
            semi: false,
            parser: "typescript",
            plugins: [parserTypeScript],
          })
        })
    />
  )
}
```

Note that this will format on every keystroke. My actual solution involved a save action, so that it would only format on save.

**Comment by suren-atoyan** [comment]
Hello @steveruizok. That looks really great. I think I should create a snippet for that, and also include it into README.
Thank you!
