### ISSUE TITLE
Editor cannot be used with Next.js

### ISSUE THREAD

**Issue by LBBO** [suren-atoyan/monaco-react#609]
**Describe the bug**
In a clean Next.js project, when I `npm install @monaco-editor/react` and simply try to display an editor somewhere (which should be possible, [as per the docs](https://github.com/suren-atoyan/monaco-react?tab=readme-ov-file#for-nextjs-users)), I get an error

```
Error: useState only works in Client Components. Add the "use client" directive at the top of the file to use it.
```

**To Reproduce**
See [this CodeSandbox](https://codesandbox.io/p/devbox/monaco-nextjs-ld3s6j?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clv8nczbk00073b6jzxpi4ib2%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clv8nczbk00023b6jaada4iws%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clv8nczbk00043b6jjtlyl7np%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clv8nczbk00063b6jwg0oy1ma%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clv8nczbk00023b6jaada4iws%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clv8nczbk00013b6jos4ahemd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clv8nczbk00023b6jaada4iws%2522%252C%2522activeTabId%2522%253A%2522clv8nczbk00013b6jos4ahemd%2522%257D%252C%2522clv8nczbk00063b6jwg0oy1ma%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clv8nczbk00053b6jbxqs1h18%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clv8nczbk00063b6jwg0oy1ma%2522%252C%2522activeTabId%2522%253A%2522clv8nczbk00053b6jbxqs1h18%2522%257D%252C%2522clv8nczbk00043b6jjtlyl7np%2522%253A%257B%2522id%2522%253A%2522clv8nczbk00043b6jjtlyl7np%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clv8nczbk00033b6joibsqkjo%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clv8nczbk00033b6joibsqkjo%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

1. Create fresh Next.js app (I used the CodeSandbo "Next.js (App Router)" template)
2. Install `@monaco-editor/react`
3. Display an `<Editor />` somewhere
4. See above error
5. Optionally try to wrap the import in a `dynamic(..., { ssr: false })`, same result

**Expected behavior**
There should be no error, as per the docs linked above.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Arc
 - Version 4.6.0

**Additional context**
I briefly checked the source code and found a 'use client' at the top of the corresponding TSX files. However, that 'use client' seems to get lost in the build process because it isn't present in the final index.mjs.

**Comment by suren-atoyan** [comment]
you need to use `"use client"` at the top of the file where you use the editor

<img width="1161" alt="Screenshot 2024-04-23 at 16 08 58" src="https://github.com/suren-atoyan/monaco-react/assets/13118722/7500539a-4f63-4096-99d6-db6b8e545324">
