### ISSUE TITLE
Not loading on IE11

### ISSUE THREAD

**Issue by IndProgo** [suren-atoyan/monaco-react#61]
**Describe the bug**
Loading Editor in IE11 throws `Object doesn't support this action` error, as Editor is loaded using ` document.dispatchEvent(new Event('monaco_init'));` in [utils/monaco.js](https://github.com/suren-atoyan/monaco-react/blob/9f4a92a4756e0125d0a6864e9e84d9ebd4dfc2db/src/utils/monaco.js#L46).
It would be better to use `new CustomEvent('monaco_init')`, so we can use 'custom-event-polyfill' for it.
Thanks

**Expected behavior**
Editor loading and running on IE11

**Desktop (please complete the following information):**
IE11

**Comment by suren-atoyan** [comment]
Hello @IndProgo. I see, thank you for opening this issue. I'll test it on IE11 today. Keep you up to date here.

**Comment by IndProgo** [comment]
Sorry, as I posted, I  found that there is also 'events-polyfill', and 
`import 'events-polyfill/src/constructors/Event';` 
helps with current new Event() for IE11

**Comment by suren-atoyan** [comment]
Good, I'll examine and try all possible ways, and let you know which one I am going to choose and why (and how).

And thank you for your support!

**Comment by suren-atoyan** [comment]
@IndProgo ahh, I got you wrong at first, sorry. So, I guess we can close it.
