### ISSUE TITLE
[Bug] editor minimap option failed 

### ISSUE THREAD

**Issue by zzusunjs** [suren-atoyan/monaco-react#617]
**Describe the bug**
2024-2-28. I find that the editor has a strange behavior,  the editor minimap height is becoming without any modify of my code.

![image](https://github.com/suren-atoyan/monaco-react/assets/22544339/6aea1047-28a4-4e23-b066-01340f1a54f5)

**To Reproduce**

1.  I use "@monaco-editor/react": "^4.5.1", and vite 
or you can check out at my site https://leeetcode.netlify.app/#/question/11

**Desktop (please complete the following information):**
 - OS: [macos]
 - Browser [chrome]

**Comment by suren-atoyan** [comment]
<img width="1723" alt="Screenshot 2024-04-29 at 10 07 37" src="https://github.com/suren-atoyan/monaco-react/assets/13118722/26eeaadf-edeb-4eab-9b6a-355ffcb0c60c">

I could fix it by removing the `height` from `div.editor-box`; still I am not sure what was the issue

**Comment by zzusunjs** [comment]
Thank you so much for taking the time to address my issue. I truly appreciate your prompt response and the solution you provided. I find out that make `div.editor-box` height from `100%` to `99%` fix the problem too. Still not sure what was happing behind that.
