### ISSUE TITLE
Custom fonts not working

### ISSUE THREAD

**Issue by casualdevvv** [suren-atoyan/monaco-react#620]
**Bug Description:**
I am encountering issues when attempting to integrate a custom font face. The font displays incorrectly, and the text within the editor has irregular spacing, which look like whitespace characters but is the text inside the editor. 

**Steps to Reproduce:**
1. Add the custom font face into the CSS.
2. Assign the fontFamily to the options props, for example: `fontFamily: 'Editor'`.

**Expected Behavior:**
Expecting the editor font to change to the selected custom font.

**Screenshots:**
![Screenshot 1](https://github.com/suren-atoyan/monaco-react/assets/54014018/ae3a38d7-4016-4cd3-acca-f3ddf695a1f4)
![Screenshot 2](https://github.com/suren-atoyan/monaco-react/assets/54014018/6774f3f6-64b4-4cbe-80d2-afea14d250bb)
![Screenshot 3](https://github.com/suren-atoyan/monaco-react/assets/54014018/34f6ce25-3a72-4668-8fe5-5f4fbd4bbfbf)
![Screenshot 4](https://github.com/suren-atoyan/monaco-react/assets/54014018/781790eb-2199-4036-9091-17dadaa7e6f2)

**Desktop Details:**
- OS: Windows
- Browser: Chrome
- Version: 126

**Editor Snippet**
```js 
<Editor height="calc(100vh - 8rem)" defaultLanguage="lua" defaultValue='print("Hello, World!")' theme='hw-novo' options={{ fontSize: 18, minimap: { enabled: false }, smoothScrolling: true, cursorBlinking: "smooth", renderLineHighlight: 'all', fontFamily: 'Editor'}}/>

**Comment by suren-atoyan** [comment]
@casualdevvv could you please try [this](https://github.com/microsoft/monaco-editor/issues/123#issuecomment-243052918)?

**Comment by casualdevvv** [comment]
@suren-atoyan That did fix the spacing issue
![image](https://github.com/suren-atoyan/monaco-react/assets/54014018/6ee3b414-de49-4f6e-a40c-843fe68ca02e)
But it still isn't able to use the font, it gets replaced by some weird default font
Here is what the font is supposed to look like
![image](https://github.com/suren-atoyan/monaco-react/assets/54014018/c8d04467-93a8-48ad-99cc-826c46576597)

**Comment by suren-atoyan** [comment]
Can you try that font somewhere else in your application? let's see if it's related to `monaco` or not.

**Comment by Gallardo7761** [comment]
Hey! I'm encountering the same problem with custom fonts. I've already tried using it in another place in the site and it loads correctly. Also my custom font (Fira Code) seems to load only when the editor requests it. What's wrong then? 
(I know I have to send snippet for reproducing the error, but it's a basic editor component with the fontFamily set to 'Fira Code' in options)
