### ISSUE TITLE
Can't access lib/cjs files

### ISSUE THREAD

**Issue by Ketler13** [suren-atoyan/monaco-react#621]
**Describe the bug**
First of all, thank you for the very useful package.

In the application I use these lines of code to import stuff I need for custom editor:
```
import MonacoContainer from '@monaco-editor/react/lib/cjs/MonacoContainer';
import useMount from '@monaco-editor/react/lib/cjs/hooks/useMount';
import useUpdate from '@monaco-editor/react/lib/cjs/hooks/useUpdate';
import usePrevious from '@monaco-editor/react/lib/cjs/hooks/usePrevious';
import {
  noop,
  getOrCreateModel,
  isUndefined,
} from '@monaco-editor/react/lib/cjs/utils';
```
That works fine at least in 4.3.1. I can see cjs folder exists in node_modules.
But with the latest 4.6.0 version structure is different and looks like main.js does not export those items.
Maybe this is something with my package manager (pnpm) because I can see those hooks and MonacoContainer still exist in the source code.

**To Reproduce**

Install 4.6.0 version of the package

**Expected behavior**
I expect to still be able to import those elements.

**Screenshots**
Before (4.3.1):
<img width="265" alt="Screenshot 2024-05-15 at 09 40 36" src="https://github.com/suren-atoyan/monaco-react/assets/24254801/92677ad3-65d3-4bde-af59-ed649a946749">

After (4.6.0):
<img width="265" alt="Screenshot 2024-05-15 at 09 41 13" src="https://github.com/suren-atoyan/monaco-react/assets/24254801/32681fce-fbb9-4328-a851-0712a412eaee">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Node: 20
 - pnpm: 9.1.1

**Additional context**
I use pnpm and nx monorepo, not sure if that matters though.

**Comment by suren-atoyan** [comment]
That is correct, we no more support cjs, umd, etc, only js/mjs.

**Comment by Ketler13** [comment]
Sorry, but is it possible to still access MonacoContainer, useMount, useUpdate, usePrevious, getOrCreateModel?

**Comment by suren-atoyan** [comment]
Ah, I see what you are saying. Unfortunately, with the current build these utilities/hooks are not available.

- for `useMount`, `useUpdate` and `usePreviouse` you can use [react-use](https://github.com/streamich/react-use) or write your own implementations (they are pretty small), check [this](https://github.com/suren-atoyan/monaco-react/tree/master/src/hooks) to get some inspiration
- for `noop` you can use `lodash/noop`, or write your own implementation. For this and for other utilities check [this](https://github.com/suren-atoyan/monaco-react/blob/master/src/utils/index.ts)
