### ISSUE TITLE
Hotkey command work in last editor on page only

### ISSUE THREAD

**Issue by ErBlack** [suren-atoyan/monaco-react#626]
**Describe the bug**
We use a form with three monaco editors in one page. They have a different name props

```jsx
// name is 'option', 'question', 'answer'
// handleMount used to add command
                <Editor
                    path={name}
                    defaultPath={name}
                    onMount={handleMount}
                    options={codeEditorOptions}
                    {...props}
                />
```

list of options

```js
{
    unicodeHighlight: { ambiguousCharacters: false },
    automaticLayout: true,
    scrollBeyondLastLine: false,
    showFoldingControls: 'never',
    wordWrap: 'on',
    minimap: {
        enabled: false,
    },
    overviewRulerBorder: false,
    overviewRulerLanes: 0,
    hideCursorInOverviewRuler: true,
    padding: {
        top: codeEditorPadding,
        bottom: codeEditorPadding,
    },
    lineNumbersMinChars: 3,
    renderLineHighlightOnlyWhenFocus: true,
    scrollbar: {
        alwaysConsumeMouseWheel: false,
    },
}
```

Add command code
```tsx
export interface MarkdownEditorBoldCommandProps  {
    editor: monaco.editor.IStandaloneCodeEditor | null;
}

const formatter = (text?: string) => `**${text}**`;
const keyBindings = KeyMod.CtrlCmd | KeyCode.KeyB;
const command = (editor: monaco.editor.IStandaloneCodeEditor | null) => executeCommand(editor, formatter);

export const MarkdownEditorBoldCommand: FC<MarkdownEditorBoldCommandProps> = ({ editor }) => {
    useEffect(() => {
        if (editor) {
            editor.addCommand(keyBindings, () => {
                command(editor);
            });
        }
    }, [editor]);

    return (
        <button
            onClick={() => command(editor)}
        >B</button>
    );
};
```

**To Reproduce**

1. Render three editors on page
2. Select text in first one
3. Press Ctrl/Command + B
4. **** will be inserted in last editor on page

[Code sandbox](https://codesandbox.io/p/sandbox/wispy-tree-839sk3?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clx4k82dr00063b6hy19nshbw%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clx4k82dr00023b6h24sqj00i%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clx4k82dr00033b6hwaojtcb4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clx4k82dr00053b6htkaj3ae0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clx4k82dr00023b6h24sqj00i%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx4k82dr00013b6huxqqgvt5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clx4kaeg1004c3b6h25r2glgb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A1%252C%2522startColumn%2522%253A23%252C%2522endLineNumber%2522%253A1%252C%2522endColumn%2522%253A23%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clx4k82dr00023b6h24sqj00i%2522%252C%2522activeTabId%2522%253A%2522clx4kaeg1004c3b6h25r2glgb%2522%257D%252C%2522clx4k82dr00053b6htkaj3ae0%2522%253A%257B%2522id%2522%253A%2522clx4k82dr00053b6htkaj3ae0%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx4k82dr00043b6h12apyq5j%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clx4k82dr00043b6h12apyq5j%2522%257D%252C%2522clx4k82dr00033b6hwaojtcb4%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clx4k82dr00033b6hwaojtcb4%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Expected behavior**
Command will be executed in focused editor

**Comment by suren-atoyan** [comment]
Your `CodeEditor` component should look like this:

```js
export function CodeEditor({ name }) {
  const handleMount = useCallback((editor) => {
    editor.addAction({
      keybindings: [2080],
      run: command,
      label: "test",
      id: name,
    });
  }, []);

  return <Editor className="Editor" path={name} onMount={handleMount} />;
}
```

**Comment by qhh001** [comment]
@suren-atoyan  how to remove the already addAction . How to rename an already displayed context menu or redefine an existing context menu。
How to delete an action that has already been defined using addAction. I need to define different context menus based on different languages.
