### ISSUE TITLE
Link to Blog Post about Electron?

### ISSUE THREAD

**Issue by jameskerr** [suren-atoyan/monaco-react#627]
Thanks for your working creating this! I am using it inside an electron app and I wrote a blog post about how I did it. If you care to include it in your docs in the electron section, then have at it! 

https://www.jameskerr.blog/posts/offline-monaco-editor-in-electron/

**Comment by suren-atoyan** [comment]
hey @jameskerr 👋 That's awesome!

Let me add it to the docs real quick

**Comment by suren-atoyan** [comment]
✅ Done!
