### ISSUE TITLE
Use monaco-editor-core for peerDependencies

### ISSUE THREAD

**Issue by TeraMind244** [suren-atoyan/monaco-react#63]
**Is your feature request related to a problem? Please describe.**
I don't need the support of `monaco-editor` on pre-defined languages such as javascript or XML, etc. I find out the core library that supports critical functions of `monaco-editor` called `monaco-editor-core`. However, `@monaco-editor/react` use the `peerDependencies` from `monaco-editor`. I think this is redundant and increase the library size unnecessarily.

**Describe the solution you'd like**
Remove peerDependencies for `monaco-editor` and use `monaco-editor-core` instead.

**Comment by suren-atoyan** [comment]
Hello @TeraMind244, I assume you've misunderstood something. The `monaco-editor` is used only for types. Library size does not depend on `peerDependencies` or `devDependencies`.  You need to have monaco-editor installed if you use typescript (for example) and you want to use types.

So, your point will work only if `monaco-editor-core` can help us implement types as we do it with `monaco-editor`. But again as it's not included to bundle, I don't see the point yet.

**Comment by TeraMind244** [comment]
Hi @suren-atoyan, thanks for your response.

Let's say I want to use your library for my project. I wonder if I need to install `monaco-editor` in my project? Instead, I just want to install `monaco-editor-core`.

I'm not an expert, so please correct me if I'm misunderstanding here.

**Comment by suren-atoyan** [comment]
@TeraMind244, you don't need to install monaco-editor as long as you don't want to use types. I use this library in 6 projects, and I don't have monaco-editor installed in any of them. So, again, if you don't use things like typescript or flow and you don't use types, you don't need to install either monaco-editor or  monaco-editor-core; you don't need any of them.

**Comment by TeraMind244** [comment]
Unfortunately, it was the case. I using TypeScript for my project. Any recommendation?

**Comment by TeraMind244** [comment]
Because you only use the type in `monaco-editor`, it could be a huge reduction in the library size if you can switch to `monaco-editor-core`. Please check [this](https://github.com/Microsoft/monaco-editor/blob/master/CONTRIBUTING.md#a-brief-explanation-on-the-source-code-structure). `monaco-editor` in basic includes `monaco-editor-core` and 5 other libraries (which we don't need).
This will benefit devs who don't need the supported language definitions from `monaco-editor`.
I can create a pull request if you want.

**Comment by suren-atoyan** [comment]
@TeraMind244 look, the library size never will change, it doesn't depend on the "monaco-editor". The source of monaco-editor comes from CDN in the default configuration, not from node_modules. Again it's just for types. It's just for the development process. After compilation types will not be included in your bundle. We can change it, but not for reducing the library size, it will be the same. When you install some package to use the types it can't be included in your final bundle. Your final bundle is going to be run in the browser, and there are no types in that environment.

If you use typescript and also want to use types, install `monaco-editor` and that's all, if you don't want to use types don't install it.

**Comment by TeraMind244** [comment]
Thanks for your response @suren-atoyan.

I understand your point. But the library size I'm talking about here is under my project's perspective. Also, I don't use the files from `monaco-editor`'s CDN. I created a script to copy their files to my static directory to serve them on-premise. Now, imagine I have to install `monaco-editor` in order to use your  library. Its `min` folder size is 9MB. Whereas, the `min` folder size of `monaco-editor-core` is 3MB.

I understand this change brings no benefit to your library. But it would benefit other projects that use your library. Please consider this.
