### ISSUE TITLE
[Bug] - Unable to refresh type definitions when using the same interface name

### ISSUE THREAD

**Issue by doregg** [suren-atoyan/monaco-react#630]
**Describe the bug**
I cannot refresh my type definitions when using setExtraLibs / dispose on addExtraLibs - when using the same interface name and same file path.
My interface is dynamically loaded and can be refreshed because of user interaction. I can't refresh the type definition because of this bug.

**To Reproduce**

1. Setup monaco editor with type definition, filePath: `ts:filename/typings.d.ts`
2. Change type definition without changing the interface name with the same filePath `ts:filename/typings.d.ts`
3. Get a type error (because interface is not getting refreshed)
See code in the playground

**Expected behavior**
[monaco playground - there it works](https://microsoft.github.io/monaco-editor/playground.html?source=v0.43.0#XQAAAAItBAAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw5Zx0HH_KnD-tsx_JEjspAd-fBsopUVtJDpZicQGyDEjFPoZU-KMlBx4h2JTZJgtNx0tLOMYgGBGlmW-mYyDrYAGqxI0ee0z4uCJdG3bGI91dQjHUeLbh7xP70DksLO4TPkJ4On86YorlRRaD3nfaaGH-i9h8T-XamMjY48QO3YJqE5q6OgipImDDmVdoc_87wrPflBI6aAQAcJgpdJu2zAs6js5hsKXp-yRUAc3AdrvMEhEElS6pKneqbTA3KxRpdK1dKdEtdLt0eYZIMsCy1duOWiHXoROv4-zkfG_m0YrPo043A5N0J93SOLsx4OAQCyTRASxxBEApVpbIwYAvh7tSNhlNMzw1wMDGHcd_P39p1XS1kjYo8HQKMxIIyDvLk2KgVD9TlY_LXTY9c3tYOcxGCLIf2IUmZ4LTbpFLKxfUDtp1q4gkbSjxHIAXdte6pp9xtSs0Z_2STKTUobT9D49krvvGbgGrujuOddTMc2bSLunuR9zSfSHQRGLFZAEvsDO7rAuYD8pDMxVdeGAEyIMM-7o1HAwJwKe8ZSu85ocJcnKFxEeqsv-_8vwgTjznMcFOyDF7cGX1O-aZPGValNfMMG1gyZ0InEJs3BKoBksyCUxyHQEcdRPE20fBC7Z0HqYUC_JnvHtNgA7OQhhk_wH25089i1C6nq4RO10-ne4vd_kdBhZ1-QR3KbVL0_2Xxu4)

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome
 - Version latest monaco version

**Comment by suren-atoyan** [comment]
I tried to reproduce it and I don't see any issue. Please check [this codesandbox](https://codesandbox.io/p/sandbox/reverent-ptolemy-z3zzh8?file=%2Fsrc%2FApp.js%3A32%2C14&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxrrx27v00062e69iycy8r7x%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxrrx27v00022e69aerntgiv%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxrrx27v00032e69ikihw5fg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxrrx27v00052e69mqiz6okl%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxrrx27v00022e69aerntgiv%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxrrx27v00012e69jzzie6bo%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxrs8iu300022e69fsdhipv5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A32%252C%2522startColumn%2522%253A14%252C%2522endLineNumber%2522%253A32%252C%2522endColumn%2522%253A14%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxrrx27v00022e69aerntgiv%2522%252C%2522activeTabId%2522%253A%2522clxrs8iu300022e69fsdhipv5%2522%257D%252C%2522clxrrx27v00052e69mqiz6okl%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxrrx27v00042e69jzs675cb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxrrx27v00052e69mqiz6okl%2522%252C%2522activeTabId%2522%253A%2522clxrrx27v00042e69jzs675cb%2522%257D%252C%2522clxrrx27v00032e69ikihw5fg%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clxrrx27v00032e69ikihw5fg%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by doregg** [comment]
@suren-atoyan thanks for trying to reproduce
My use case is much more complex than that (language javascript with a lot of typescript configurations). I tried to implement my use case in the code sandbox but I couldn't make it work like in my local. Let's close it for now and if I'll have more time to invest on it I'll re-open. Thanks
