### ISSUE TITLE
Ability to specify html id on monaco editor

### ISSUE THREAD

**Issue by kodonnell-heila** [suren-atoyan/monaco-react#638]
**Is your feature request related to a problem? Please describe.**
I am using the Monaco editor within a form and trying to write tests using [testing-library](https://testing-library.com/). Ideally you select elements by role, but I cannot specify a role for the editor. Instead I tried to select my `DiffEditor` with an id, but you cannot specify that attribute in the options either. 

**Describe the solution you'd like**
I'd like to be able to do this:
```
<label htmlFor="my-editor">My editor</label>
<DiffEditor options={{ htmlId="my-editor" }}/>
```

**Describe alternatives you've considered**
I can use `ariaLabel` by itself, but because this isn't linked to a form label, it's not visible to a user. Ideally, every form input has a label attached to it with "for".

It would also be cool if the editor could be assigned a role of "textbox" as specified here https://www.w3.org/TR/html-aria/#docconformance. The w3 docs explicitly do not want people manually assigning "textbox" roles though.

**Comment by kodonnell-heila** [comment]
I have noticed you apply the aria-label to the `textarea` element in the diff editor, but testing library seems to think it's inaccessible.

Diff editor settings
```
<DiffEditor
  options={{
            ariaLabel: `File editor for network_manager.conf`
  }}/>
```

Line failure
```
    const fileEditor = screen.getByRole('textbox', { name: 'File editor for network_manager.conf' });
```

`TestingLibraryElementError: Unable to find an accessible element with the role "textbox" and name "File editor for network_manager.conf"`

**Comment by suren-atoyan** [comment]
I guess you are facing a different issue here: I assume testing library fails to render the Editor. We have a similar issue, could you please check [this](https://github.com/suren-atoyan/monaco-react/issues/88)?

**Comment by kodonnell-heila** [comment]
Ah #88 does seem to include what I am running into. Closing this in favor of the existing one. Thanks!
