### ISSUE TITLE
Default json value not formatted on mounted

### ISSUE THREAD

**Issue by jpainam** [suren-atoyan/monaco-react#649]
Hi. I'm unable to format the default `json` value on mouted.

Here is my code 

```tsx
"use client";

import { useRef } from "react";
import { Editor } from "@monaco-editor/react";

export const MyEditor = ({
  onChange,
  defaultValue,
}: {
  onChange?: (value: string | null | undefined) => void;
  defaultValue?: string;
}) => {
  return (
      <Editor
        height={"200px"}
        defaultValue={defaultValue}
        language="json"
        defaultLanguage="json"
        onChange={(v) => onChange?.(v)}
        options={{
          minimap: { enabled: false },
          lineNumbers: "on",
          scrollbar: {
            vertical: "hidden",
            horizontal: "hidden",
          },
        }}
      />
  );
};
```

And here is the result
![image](https://github.com/user-attachments/assets/19bb1acc-495f-4de5-bce1-7894a848cd65)

Is it possible to format the default `json` value?

Thanks.

**Comment by chenyingkeai** [comment]
maybe you can refer to this issue，its useful for me

**Comment by chenyingkeai** [comment]
maybe you can refer to this issue, its helpful to me
https://github.com/suren-atoyan/monaco-react/issues/11

**Comment by suren-atoyan** [comment]
> maybe you can refer to this issue, its helpful to me #11

I am glad you found it helpful. I am closing this now, feel free to reopen if you face other issues related to this
