### ISSUE TITLE
Bundle size control/reduction

### ISSUE THREAD

**Issue by riotrah** [suren-atoyan/monaco-react#65]
**Is your feature request related to a problem? Please describe.**
This adds about 15mb to my total bundle size. and it would be nice to have some control over this. Perhaps Monaco itself is by necessity so large, but I'm not sure yet.

**Describe the solution you'd like**
I'm not sure what the best way to reduce this is, or if it even matters, so forgive my ignorance! However, I'd like to know if there is a way to lazy-load the component, reduce the total bundle size somehow, or do something to affect the page load and help my application pass a LightHouse edit

**Describe alternatives you've considered**
I could try to eject and try using Monaco by itself with all the webpack config - however that would defeat whatever purpose I had in using this library in the first place. If the way this library is implemented will never let me do reduce my bundle size/perf, then I'm willing to accept that as a caveat of the simpler installation.

**Additional context**
N/A

**Comment by suren-atoyan** [comment]
Hello @riotrah, the size of this library is about 60 kb, you can check it [here](https://www.npmjs.com/package/@monaco-editor/react). 60kb with README, Changelog and other staff, it will be reduced to 10 - 20 kb as a source code after compilation.

If you use default configuration of this library, it means, the main source code of monaco will come from CDN, of course with lazy loading.

You bundle can't be 15mb, you can load 15mb to your browser, but it's not you BUNDLE SIZE. If you use CRA, type yarn builds, and please show me the result. Here, is the example of empty CRA with some things and with this library; there are 4 bundles, the biggest one is 43+ kb.
<img width="569" alt="Screen Shot 2020-03-24 at 00 22 40" src="https://user-images.githubusercontent.com/13118722/77359984-f8b5a600-6d65-11ea-9c42-b4ecf546a61c.png">
