### ISSUE TITLE
How do i add a custom theme ? 

### ISSUE THREAD

**Issue by mohsinxx365** [suren-atoyan/monaco-react#66]

**Comment by suren-atoyan** [comment]
You need to use `.defineTheme` method. Read about it [here](https://microsoft.github.io/monaco-editor/api/modules/monaco.editor.html#definetheme). As an example see [this code](https://github.com/suren-atoyan/monaco-react/blob/277c249ffef6a6a4bb5ea12e2a20fa78abdbddea/demo/src/store/effects/index.js).

**Comment by mohsinxx365** [comment]
I had another doubt . How to add custom autocompletion

**Comment by suren-atoyan** [comment]
@mohsinxx365 this library is a react wrapper for `monaco-editor`. To understand how to create custom autocompletion examine `monaco-editor` itself. Search `.registerCompletionItemProvider`.
