### ISSUE TITLE
How to set a json specification in MonacoEditor

### ISSUE THREAD

**Issue by pvilaca** [suren-atoyan/monaco-react#69]
**Is your feature request related to a problem? Please describe.**
I am trying to define a single json specification so that Monaco Editor could autocomplete and validate the typed json. I can not understand how can I do it.

**Describe the solution you'd like**
Something like this:
https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-json-defaults

**Describe alternatives you've considered**
Using your demo code I re-write the Editor component like this:

```javascript
import React from 'react';

import MonacoEditor from '@monaco-editor/react';
import Settings from './Settings';

import { useStore } from 'store';
import examples from 'config/examples';
import config from 'config';

import useStyles from './useStyles';
import { monaco } from '@monaco-editor/react';

const Editor = _ => {
  const classes = useStyles();
  const { state: { editor: { selectedLanguageId, options }, monacoTheme } } = useStore();
  var modelUri;

  monaco
  .init()
  .then(monaco => {

    // where I put this modelUri ??
    modelUri = monaco.Uri.parse("a://b/foo.json"); // a made up unique URI for our model

    monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
      validate: true,
      schemas: [{
          uri: "http://myserver/foo-schema.json", // id of the first schema
          fileMatch: [modelUri.toString()], // associate with our model
          schema: {
              type: "object",
              properties: {
                  p1: {
                      enum: ["v1", "v2"]
                  },
                  p2: {
                      $ref: "http://myserver/bar-schema.json" // reference the second schema
                  }
              }
          }
      }, {
          uri: "http://myserver/bar-schema.json", // id of the first schema
          schema: {
              type: "object",
              properties: {
                  q1: {
                      enum: ["x1", "x2"]
                  }
              }
          }
      }]
  });
  })
  .catch(error => console.error('An error occurred during initialization of Monaco: ', error));
  
return <div className={classes.root}>
    <MonacoEditor
      theme={monacoTheme}
      height=""
      value={examples[selectedLanguageId] || ''}
      language={config.supportedLanguages.find(({ id }) => id === selectedLanguageId).name}
      options={options}
    />
    <Settings />
  </div>;
}

export default Editor;
```

This worked but I didn't get the expected result.
I would like only the "http: //myserver/foo-schema.json" scheme to be active for autocomplete and validation.

Instead of that the editor suggest me the "$schema" field when I am trying to type a json with four suggestions:
* "http://json-schema.org/draft-04/schema"
* "http://json-schema.org/draft-07/schema"
* "http://myserver/bar-schema.json"
* "http://myserver/foo-schema.json"

If I choose the "http://myserver/foo-schema.json" the editor stars to suggest the correct things. 

There are a way to force only one json schema on MonacoEditor?

**Comment by suren-atoyan** [comment]
Hello @pvilaca. I examined your example. My question is - do you see the same behavior in the [Monaco Playground](https://microsoft.github.io/monaco-editor/playground.html)? If you didn't try the example you've mentioned above, please implement the same one in the playground to understand whether the problem is from the wrapper (this library) or from the original library (monaco-editor).

**Comment by hrgui** [comment]
@pvilaca I had the same problem as you, but after seeing an example in react-monaco-editor, I was able to make it work here too.

See https://github.com/react-monaco-editor/react-monaco-editor#do-something-before-editor-mounted

https://codesandbox.io/s/monaco-editor-json-validation-example-gue0q?file=/src/App.js

The idea is to set `fileMatch to `*`

**Comment by suren-atoyan** [comment]
Thank you @hrgui. @pvilaca could you please check it and let us know if everything is okay?

**Comment by pvilaca** [comment]
Thank you @suren-atoyan and @hrgui for your help..

I forgot to setModel in the editor.

I added:
```js
           ...
            var modelUri = monaco.Uri.parse("a://b/foo.json"); 
            const model = monaco.editor.createModel(
              "// write code",
              "json",
              modelUri,
            )
            editor.setModel(null)
            editor.setModel(model)
           
            monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
            ...
```

and then work fine!
