### ISSUE TITLE
getModelMarker() doesn't include newly introduced Markers

### ISSUE THREAD

**Issue by jpeterson** [suren-atoyan/monaco-react#70]
**Describe the bug**
Using `getModelMarkers()` when handling the `onChange` event of `ControlledEditor` does not include any ModelMarkers that were introduced by the change being handled. 

It does, however, include any ModelMarkers that existed before the current change.

```jsx
  const handleEditorChanged = (ev, value) => {
    const errors = monacoRef.current.editor.getModelMarkers();
    console.log(errors);
    // returns [] when first ModelMarker is introduced
  };
```

**To Reproduce**
https://codesandbox.io/s/nifty-ardinghelli-7w84o

**Expected behavior**
When called inside the ControlledEditor's `onChange` handler, `getModelMarkers()` should include any ModelMarkers that were introduced by the change being handled.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Additional context**
I would also think this is possible without using the `monaco` instance, since I already have a ref for the `editor` itself (see codesandbox)... Please let me know if I'm just going about this all wrong 🙂

**Comment by jpeterson** [comment]
Follow up note: I see the same behavior when using this approach:

```jsx
  const handleEditorDidMount = (_valueGetter, editor) => {
    monaco.init().then(monaco => {
      monacoRef.current = monaco;
    });

    editorRef.current = editor;

    editorRef.current.onDidChangeModelContent(ev => {
      const errors = monacoRef.current.editor.getModelMarkers();
      console.log(errors);
      // returns [] when first ModelMarker is introduced
    });
  };
```

**Comment by suren-atoyan** [comment]
Hello @jpeterson, I've checked your snippet, and yes, there is strange behavior. Now the question is - does it come from the original module or from the wrapper (this library). So, could you please check your example in the [monaco playground](https://microsoft.github.io/monaco-editor/playground.html)?

**Comment by jpeterson** [comment]
@suren-atoyan thanks for the quick response. Turns out I'm seeing the same behavior in monaco-editor itself... which makes me think I'm probably approaching this problem the wrong way.

Same issue using monaco-editor: https://codesandbox.io/s/aged-haze-e2fgd

**Comment by jpeterson** [comment]
Logged a new issue: https://github.com/microsoft/monaco-editor/issues/1906

**Comment by suren-atoyan** [comment]
That was definitely a good decision to refer the issue to `microsoft/monaco-editor`. Let's leave it open for a while. Keep us up to date here, please. 👍

**Comment by SakaSaiTrinath** [comment]
`monacoRef.current.editor.getModelMarkers()` function returns the current markers but not the updated markers. So, you can't use this function to track errors.

Instead [this](https://github.com/microsoft/monaco-editor/issues/30#issuecomment-316418679) works well.

**Comment by suren-atoyan** [comment]
I examined the case; I reckon it won't be "fixed". I mean we call `onacoRef.current.editor.getModelMarkers()` right after content is changed, but `monaco` to understand are there any problems "need" time. The example @SakaSaiTrinath mentioned, works. I create a [snippet](https://codesandbox.io/s/onvalidate-lu557?file=/src/index.js) based on that. There is also [another](https://github.com/microsoft/monaco-editor/issues/2138#issuecomment-694689888) method. Currently, I am planning a new major version release, and probably one of them I'll use to provide something like `onValidate`, but for now you can use one of the versions mentioned above.

**Comment by aamir1995** [comment]
@suren-atoyan the original issue still remains, you still get outdated markers when trying `const errors = monacoRef.current.editor.getModelMarkers();`.
