### ISSUE TITLE
peer dependency version range update

### ISSUE THREAD

**Issue by michaelsbradleyjr** [suren-atoyan/monaco-react#71]
Is there a possibility the peerDep specifier for [monaco-editor](https://github.com/suren-atoyan/monaco-react/blob/master/package.json#L33) can be bumped in the next version?

I am using a newer version of the editor with this package and it works fine, but because e.g. `0.20.0` doesn't satisfy the range `^0.19.0` there is always a complaint from yarn during a fresh install.

**Comment by hrgui** [comment]
From my understanding, this package loads monaco from the CDN from here:

https://github.com/suren-atoyan/monaco-react/blob/master/src/config/index.js#L1-L5

I wonder if we could just remove the peer dep because it doesn't use monaco-editor directly as a dep?

**Comment by michaelsbradleyjr** [comment]
It can be loaded from the local filesystem as well.

See: https://github.com/embarklabs/embark/blob/master/packages/cockpit/ui/src/components/TextEditor.js#L10-L17.

See also: 

* https://github.com/embarklabs/embark/blob/master/packages/cockpit/ui/package.json#L77
* https://github.com/embarklabs/embark/blob/master/packages/cockpit/ui/package.json#L33-L34
* https://github.com/embarklabs/embark/blob/master/packages/cockpit/ui/scripts/copy-monaco-to-public.js

So, I think having this package spec it as a peerDep does make sense; it's possible there was a misunderstanding by this package's author re: the semantics of caret ranges (`^`) with respect to versions that start with `0.` — definitely something that tripped me up in the past:

* `^1.0.0` — any version that's `<=2.0.0` can satisfy that range (leaving aside prerelease semantics).
* `^0.1.0` — any version that's `<=0.2.0` can satisfy that range (again leaving aside prerelease semantics).

The fact that the `^` operator behaves differently when the MAJOR version-part is `0` can be surprising, and is maybe a bit weird, but it is what it is.

**Comment by suren-atoyan** [comment]
Hello @michaelsbradleyjr @hrgui 

`monaco-editor` was written as a `peerDependency` because of types. There are type definitions and to be able to use it you need to have a `monaco-editor` installed.

@michaelsbradleyjr There wasn't a misunderstanding about versions, I just kept the same logic of versioning in the `config file` and `package.json`; the idea was to have the same versions of `monaco` come from `CDN` and one for types.

Anyway, I have already updated both of them, now it's 0.20.0.
