### ISSUE TITLE
Cannot hide suggestions tooltip

### ISSUE THREAD

**Issue by adhanji8** [suren-atoyan/monaco-react#72]
**Describe the bug**
When I try to add a setting to hide tooltip suggestions, the suggestions are still displayed. 

**To Reproduce**

Try typing console.log( 
<img width="480" alt="Screen Shot 2020-04-20 at 5 20 20 PM" src="https://user-images.githubusercontent.com/55081439/79812110-c11e2780-832c-11ea-8cfd-ceda665af31a.png">

**Expected behavior**
Tooltip window should be hidden

I have tried adding to my opts:
`let opts = {
  editor: {
      parameterHints: { 
          enabled: false
      },
      suggestOnTriggerCharacters: false,
      quickSuggestions: false,
      wordBasedSuggestions: false
  }
};`

**Comment by suren-atoyan** [comment]
Hello @adhanji8. Did you check it in [Monaco Playground](https://microsoft.github.io/monaco-editor/playground.html)? I mean to say, does it depend on this library (which is a wrapper of monaco for react) or on the original library?
