### ISSUE TITLE
diffEditor is not support

### ISSUE THREAD

**Issue by llfylwg** [suren-atoyan/monaco-react#73]
**Describe the bug**
diffEditor is not support

**To Reproduce**

Can you provide a diffeditor demo?

**Comment by suren-atoyan** [comment]
Hello @llfylwg.
1) [Demo](https://monaco-react.surenatoyan.com/) - Scroll down to see diff editor demo
2) [The source code of the demo](https://github.com/suren-atoyan/monaco-react/blob/master/demo/src/sections/DiffEditor/DiffEditor.js)
3) [Props of Diff Editor](https://github.com/suren-atoyan/monaco-react#diffeditor)

**Comment by suren-atoyan** [comment]
@llfylwg let me know if it helps.

**Comment by llfylwg** [comment]
i init the demo, it's blank. when i change the window, the demo will render, this is a bug?  you can try。  
  another, how handle value includes \n\t?

**Comment by suren-atoyan** [comment]
@llfylwg I check it. There is a problem, but it's related to the latest monaco version.

Check this [snippet](https://codesandbox.io/s/monaco-editorreact--diff-s9p2h?file=/src/index.js), please. Now we are running `0.20.0` version of monaco by default. So, you can change it and downgrade to older versions, before they fix it.

**Comment by llfylwg** [comment]
use this?  
````
monaco.config({
  paths: {
    // vs: "https://cdn.jsdelivr.net/npm/monaco-editor@0.20.0/min/vs" // this one is default
    vs: "https://cdn.jsdelivr.net/npm/monaco-editor@0.19.3/min/vs" // switch to this one - DO REFRESH AFTER CHANGE
  }
});
````
this is successfully,thx

**Comment by suren-atoyan** [comment]
@llfylwg, glad to hear that.
