### ISSUE TITLE
about onValidate

### ISSUE THREAD

**Issue by sringly** [suren-atoyan/monaco-react#74]
**Is your feature request related to a problem? Please describe.**
react-ace package has a function called onValidate, now i want to replace react-ace with @monaco-editor/react , but i can not find onValidate, how can i do?

**Comment by suren-atoyan** [comment]
Hello @sringly, sorry for the late answer

I am planning a new major version release, probably we will have something like `onValidate`. For now, you can do something like [this](https://codesandbox.io/s/onvalidate-lu557?file=/src/index.js) - to get live validation.

**Comment by suren-atoyan** [comment]
Hey @sringly 👋 

The new version of the `monaco-react` has been released. And there is a property `onValidate` 🙂 [Read more](https://github.com/suren-atoyan/monaco-react#onvalidate)

Thank you for your support!

**Comment by sujinleeme** [comment]
@suren-atoyan Hello, is there any way to get to know code has no errors? I have to store all errors with `onValidate`. But If the code doesn't have any errors,  `onValidate` is not called.

**Comment by suren-atoyan** [comment]
@sunderls hello. Hmm, I see, you are right. Now I call `onValidate` only if the length of model markers isn't 0; I should call it anyway. Okay, I'll fix it tomorrow; will let you know here.

**Comment by suren-atoyan** [comment]
@sunderls done, please check the new version `v4.0.7`

**Comment by AykutSarac** [comment]
> @sunderls hello. Hmm, I see, you are right. Now I call `onValidate` only if the length of model markers isn't 0; I should call it anyway. Okay, I'll fix it tomorrow; will let you know here.

I don't think onValidate is being called when there is no marker currently.
