### ISSUE TITLE
"Uncaught Error: Could not find source file" when using setCompilerOptions on monaco instance

### ISSUE THREAD

**Issue by nickjanssen** [suren-atoyan/monaco-react#75]
Hello! Thank you for making this library, it's so much better than other monaco editors out there.

**Describe the bug**
It appears that doing anything with the monaco instance results in `Uncaught Error: Could not find source file` errors.

**To Reproduce**

Add the following to your code:
```
monaco.init().then(monaco => {
  monaco.languages.typescript.javascriptDefaults.setCompilerOptions({
    noLib: true
  });
});
```
Also be sure to use `language="javascript"`

Here's a minimally reproducable example:
https://codesandbox.io/s/patient-sky-uykvg?file=/src/App.js

Note that these errors don't show in the Codesandbox console for some reason, you have to actually open your Chrome console to see them.

**Comment by suren-atoyan** [comment]
Hello @nickjanssen. Thank you for feedback.

I've found [this issue](https://github.com/microsoft/monaco-editor/issues/1842). I assume it's related to the original library.

**Comment by jannisch** [comment]
I also experienced this issue but was able to fix it by including the default options. Try this:
``` javascript
let options = monaco.languages.typescript.javascriptDefaults.getCompilerOptions()
options.noLib = true
monaco.languages.typescript.javascriptDefaults.setCompilerOptions(options)
```

**Comment by suren-atoyan** [comment]
Hello @nickjanssen, sorry for the late answer

It was related to the `monaco-editor` version. Check new versions it's fixed.

**Comment by VitalickS** [comment]
> I also experienced this issue but was able to fix it by including the default options. Try this:
> 
> ```js
> let options = monaco.languages.typescript.javascriptDefaults.getCompilerOptions()
> options.noLib = true // example change
> monaco.languages.typescript.javascriptDefaults.setCompilerOptions(options)
> ```

its because you need set `allowNonTsExtensions` to true
