### ISSUE TITLE
Undo does not fire onChange callback with controlled editor

### ISSUE THREAD

**Issue by MichaelKowal** [suren-atoyan/monaco-react#76]
Using a controlled editor, the onChange callback is not called when an undo is done.  The causes any changes that are undone to continue to be applied until a new change is made.

[Here](https://codesandbox.io/s/monaco-editorreact-bug-h24pe) is a codesandbox link that you can test this in.

**Expected behavior**
When you undo the onChange should fire with the new (old) value.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox
 - Version: 76.0

**Additional context**
Confirmed in Firefox and Chrome.  Reproduced in codesandbox.

**Comment by suren-atoyan** [comment]
Hello @MichaelKowal. Thank you for opening this issue. It's actually a duplication of [this one](https://github.com/suren-atoyan/monaco-react/issues/51).
