### ISSUE TITLE
How to setup intelliSense and go to definition for multiple files

### ISSUE THREAD

**Issue by avisprince** [suren-atoyan/monaco-react#79]
Hi,

I am trying to figure out how to get intelliSense and go to definition working. I have tried following the instructions found [here](https://stackoverflow.com/questions/57146485/monaco-editor-intellisense-from-multiple-files) but no matter what I do, it does not seems to work. I am able to create and set models just fine and have run setEagerModelSync(true) but intellisense still isn't working properly.

Any help would be greatly appreciated!

**Comment by suren-atoyan** [comment]
Hello @avisprince. Could you please make a reproducible code snippet, please?

**Comment by avisprince** [comment]
Here you go. I should be able to jump to Globals.scss but I can't...

```import React from "react";
import MonacoEditor, { monaco } from "@monaco-editor/react";

let monacoInstance = null;

class BasicEditor extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      initialized: false,
      editorIsReady: false,
    };
  }

  async componentDidMount() {
    monacoInstance = await monaco.init();
    monacoInstance.editor.createModel(globalCss, "css");
    monacoInstance.editor.createModel(indexCSS, "css");

    monacoInstance.languages.typescript.javascriptDefaults.setEagerModelSync(true);

    this.setState({ initialized: true });
  }

  render() {
    if (!this.state.initialized) {
      return null;
    }

    return <MonacoEditor height='90vh' theme='dark' value={indexCSS} language='scss' />;
  }
}

export default BasicEditor;

const indexCSS = `@import './Globals.scss';

body {
  background-color: $blackColor;
}`;

const globalCss = `$blackColor: black;`;
```

**Comment by suren-atoyan** [comment]
Could you please check the same example in the [playground](https://microsoft.github.io/monaco-editor/playground.html) of the monaco, to understand if the problem comes from the original library or from the wrapper.

**Comment by avisprince** [comment]
So, with more playing around I was able to get intellisense and go to definition working. However, in order to get go to definition working, I need to overwrite the default codeEditorService when calling create editor. (It's the third parameter). I checked your code and it doesn't look like you support this?

**Comment by avisprince** [comment]
You can find an example in this tutorial in the go to definition section: https://blog.expo.io/building-a-code-editor-with-monaco-f84b3a06deaf

**Comment by suren-atoyan** [comment]
No, unfortunately, we don't support it yet. We'll add it in the next version.

**Comment by aviprince-hdai** [comment]
Amazing. Thank you!

**Comment by suren-atoyan** [comment]
@nealchandra could you please check the new version `3.3.1`

**Comment by nealchandra** [comment]
@suren-atoyan Looks to be working for me! Thanks for merging and putting up a new release so quickly

**Comment by suren-atoyan** [comment]
@aviprince-hdai @avisprince guys could you please check it also; if it's okay, we can close the issue. And let's thank @nealchandra for opening the PR. 🎉

**Comment by avisprince** [comment]
Thanks for the quick turnaround! I cannot test this right away as I have some things on my plate, but I'm happy to close this issue and open a new one if I can't figure it out. I looked at the changes and they look like they should be fine. Thanks @nealchandra 

Also, sorry about the confusion of 2 different users responding. I accidentally responded with my work GitHub account.
