### ISSUE TITLE
State is not reactive in onDidChangeModelContent

### ISSUE THREAD

**Issue by ALITHEALI** [suren-atoyan/monaco-react#81]
**Describe the bug**

Hello, First of all, thank you for this great project. I am trying to save some items into the database when the editor content changes and I'd like to save the language (which is stored in useState) alongside  the content so naturally I went for `onDidChangeModelContent` but unfortunately the language(in React's useState) is not reactive in`onDidChangeModelContent` method.
Here's the code: (I've also added the codesandbox link below).
```jsx
import React, { useRef, useState, useEffect } from "react";
import ReactDOM from "react-dom";

import Editor from "@monaco-editor/react";

function App() {
  const editorRef = useRef();
  const [lang, setlang] = useState("javascript");

  useEffect(() => {
    // Language outside CB is reactive
    console.log("langOutsideCB", lang);
  }, [lang]);

  const handleEditorDidMount = (_, editor) => {
    editorRef.current = editor;
    listenEditorChagnes();
  };

  const listenEditorChagnes = () => {
    editorRef.current.onDidChangeModelContent(ev => {
      // Language inside CB Doesn't change here ⬇️
      console.log("languageInsideCB", lang);
    });
  };

  return (
    <>
      <button onClick={() => setlang("python")}>Change Language</button>
      <Editor
        height="90vh"
        editorDidMount={handleEditorDidMount}
        language={lang}
      />
    </>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);

```
**To Reproduce**

1. Go to 'https://codesandbox.io/s/monaco-editorreact---editor-instance-rzg3l?file=/src/index.js'
2. Switch the language at the top
3. check the console and compare the `languageInsideCB` with `langOutsideCB` and see that it is different

Minimal code sample in [codesandbox](https://codesandbox.io/s/monaco-editorreact---editor-instance-rzg3l?file=/src/index.js).

**Expected behavior**

The state should be reactive inside the callback `onDidChangeModelContent`

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 83.0.4103.61 (Official Build) (64-bit)

**Additional context**

This might be because of dependencies of the` editorDidMount` for reactivity.

**Comment by suren-atoyan** [comment]
Hello @ALITHEALI. Thank you for your support.

It's because you are trying to detect language change by `onDidChangeModelContent ` method, which is supposed to be used to detect model content change. So, for your case, you should use `onDidChangeModelLanguage` method. Check [this](https://codesandbox.io/s/monaco-editorreact---issue81-m7gkl?fontsize=14&hidenavigation=1&theme=dark), please.

**Comment by ALITHEALI** [comment]
Thank you so much! That did the job! Many thanks.
