### ISSUE TITLE
need position absolute for MonacoContainer

### ISSUE THREAD

**Issue by jquintozamora** [suren-atoyan/monaco-react#86]
Hello, I'd need to configure monaco container as position:absolute. 

Could we have styles prop available for the container? 

https://github.com/suren-atoyan/monaco-react/blob/eb186ab61aa6c063f3c619f9ad0f93a40a915f96/src/MonacoContainer/styles.js#L4

Thanks!

**Comment by suren-atoyan** [comment]
Hello @jquintozamora, okay, I'll add it to the next version and keep you up to date here.

**Comment by suren-atoyan** [comment]
Hello @jquintozamora.
I've just published the new version - v3.4.0 🎉 
Now we have two new props - `className` and `wrapperClassName`.
In your particular case, you need `wrapperClassName`. Pass a class name to that prop, and write your custom styles for the wrapper element.

Note that in the case of `position`, as it is one of default wrapper styles, you should use `!important`. That's all.
Please check the new version, and let me know if everything works fine.

**Comment by jquintozamora** [comment]
Hello @suren-atoyan , 

Thanks for that. 

Re: !important , I think is best not to fill my codebase with !important clauses. I'll put your component into another wrapper instead if you don't have plans to give flexibility for position attribute.

**Comment by suren-atoyan** [comment]
Hello @jquintozamora. No, there are no plans, for now, it can be redesigned in the future, but now.
