### ISSUE TITLE
How to add a customer lanaguage to monaco-react

### ISSUE THREAD

**Issue by dougajmcdonald** [suren-atoyan/monaco-react#92]
I would like to create a language definition to represent a custom the https://microsoft.github.io/monaco-editor/monarch.html language monaco doesn't support.

I'd like to be confident that I would be able to import this language definition into monaco-react before putting the effort in to create it but couldn't see anything in the monaco-react API. 

Is there any way to access these properties from the monaco-react package: https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-custom-languages

Any info, warmly received

**Comment by suren-atoyan** [comment]
Hello @dougajmcdonald.

Sure, it's possible. For that, you need to access the instance of monaco. [Here](https://github.com/suren-atoyan/monaco-react#monaco-instance) is the README part of that. Also, you can check [this](https://codesandbox.io/s/monaco-editorreact---monaco-instance-5pbmx?fontsize=14&hidenavigation=1&theme=dark) snippet.

Let me know if it works.

**Comment by dougajmcdonald** [comment]
Excellent I'll give that a whirl, thanks for the reply

**Comment by Jacqueline-ms** [comment]
@dougajmcdonald any luck? I understand how to access the instance of monaco, but I don't know how to incorporate the new syntax I created with [monarch](https://microsoft.github.io/monaco-editor/monarch.html) to my react project. I greatly appreciate any input!

**Comment by suren-atoyan** [comment]
> @dougajmcdonald any luck? I understand how to access the instance of monaco (mentioned above), but I don't know how to incorporate the new syntax I created with [monarch](https://microsoft.github.io/monaco-editor/monarch.html) to my react project. @suren-atoyan I greatly appreciate any input!
> 
> I tried following [this documentation](https://github.com/Microsoft/monaco-languages#dev-adding-a-new-language) however I don't think it's applicable to the react version.

Hello @Jacqueline-ms 

Could you please check [this](https://codesandbox.io/s/monaco-editorreactcustom-language-5yqj6?file=/src/index.js) code snippet? Let me know if it helps.

**Comment by Jacqueline-ms** [comment]
This helps tremendously. Thank you so much, @suren-atoyan.
