### ISSUE TITLE
FormatOnType not trigerred when typing

### ISSUE THREAD

**Issue by MRzNone** [suren-atoyan/monaco-react#95]
**Describe the bug**
I registered a on type formatter, but the formatter is not called when typing.

**To Reproduce**
https://codesandbox.io/s/not-working-editor-marker-ouiwi?file=/src/index.tsx

**Expected behavior**
console should log when we type in the text editor.

**Desktop (please complete the following information):**
 - Browser: chrome

**Additional context**
I think activating formatOnType and providing a formatter are sufficient for the workflow.

**Comment by suren-atoyan** [comment]
Hello @MRzNone,

You missed `autoFormatTriggerCharacters `, please check it [here](https://github.com/Microsoft/monaco-editor/blob/master/monaco.d.ts#L5752).

I fixed your example, you can check it [here](https://codesandbox.io/s/it-is-working-1gzyl)
