### ISSUE TITLE
DiffEditor do not init in full width & height

### ISSUE THREAD

**Issue by mmechacek** [suren-atoyan/monaco-react#97]
Hello,

I just found the issue with component DiffEditor.
After mount component is not visible until I resize the window.

Any idea how to hotfix it?
I can not find any Types and description for typescript .. just using the (_: any, editor: any) parameters for handleEditorMount function.

Thanks for any advice.
BR,
Michal

**Comment by mmechacek** [comment]
It supposed to be issue with loading theme.
With theme "light" is it works well but not with "light" or default.

Used 
```
import { Box } from "@material-ui/core";
import React from "react";
import { DiffEditor, ControlledEditor } from "@monaco-editor/react";

const options: any = {
  automaticLayout: true,
  colorDecorators: true,
};

const value = `function bla() {
    console.log("bla");
  }
  bla();
`;

export default function TestComponent() {
  const editorRef = React.useRef(null);
  const [ready, setReady] = React.useState<boolean>(false);

  const handleEditorMount = (_: any, editor: any) => {
    editorRef.current = editor;
    setReady(true);
  };

  React.useEffect(() => {
    if (ready) {
      console.log(editorRef);
    }
  }, [ready, editorRef]);

  return (
    <Box width="100%" height={500}>
      <DiffEditor
        original={value}
        modified={value}
        editorDidMount={handleEditorMount}
        language="javascript"
        options={options}
        theme="light"
      />
    </Box>
  );
}

```

**Comment by suren-atoyan** [comment]
Hello @mmechacek.

There is a problem with Monaco version 0.20.0, which is used by default here. It will be solved in the next version of Monaco. One option is to use version 0.19.x. Please check [this](https://github.com/suren-atoyan/monaco-react/issues/73) out.

**Comment by mmechacek** [comment]
Ah, it works 👍 with version 0.19.x. Thank you for hotfix idea.
