### ISSUE TITLE
Integrating with Typescipt

### ISSUE THREAD

**Issue by adarshaacharya** [suren-atoyan/monaco-react#99]
Should we install monaco-editor package separatley for using with React Typescript?

**Comment by suren-atoyan** [comment]
Hello @adarshaacharya,

Yes, to use types you need to install `monaco-editor`, please check the [declaration](https://github.com/suren-atoyan/monaco-react/blob/master/src/index.d.ts) file.

**Comment by adarshaacharya** [comment]
@suren-atoyan But it's working without installing. Any specific reason for this ?

**Comment by suren-atoyan** [comment]
Maybe, the `monaco-editor` package has been installed as a dependency of another package. Check your `node_modules`, it should be installed somehow.
